### ISSUE TITLE
Add auto-resizer component

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#100]
@tnajdek to auto-resize form elements (e.g. the textarea in the _Extra_ metadata field) I would like to use the same approach that we use in Tropy – I think it’s easiest if you just have a look at the code:

https://github.com/tropy/tropy/blob/master/src/components/auto-resizer.js

The auto-resizer basically keeps the text content of a control element in sync with a `div.content` element, which is used to stretch the control element to the desired size. So we would end up with a structure like that:

```
.editable
  .input-group
    .auto-resizer
      .content
      textarea.editable-control
```

The auto-resizer should be optional.

**Comment by flachware** [comment]
Looks good to me!

**Comment by flachware** [comment]
Could you add an option to the auto-resizer that let’s us switch between between _horiztonal_ and _vertical_ auto-resize?

I would just need a `.horizontal` or `.vertical` class on the `.auto-resizer` element (I think the two options are mutex). I don’t mind if we always set one of them or if there is a default (so e.g. just `.vertical` gets set as a modifier – whatever works best for you.

**Comment by tnajdek** [comment]
Done with 'horizontal' being the default mode, vertical is enabled with a switch, usage: 

```js
<Input resize={ true } />
<Input resize="horizontal" />
<TextArea resize="vertical" />
```

(first two are equivalent)

I've enabled vertical for a textarea in the ItemBox.
