### ISSUE TITLE
Add up/down functionality to Creators field

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#106]
@tnajdek the client provides a way to change the order of creators using a context menu. Similarly we could add up/down entries to the creators select. Ideally we would have a 'divider' element between the creators options and the up/down options (like in the client).

**Comment by dstillman** [comment]
That option is clumsy, though. I think ideally you'd just be able to drag creators to rearrange them.

**Comment by flachware** [comment]
This is being taken care of in #120. Closing.
