### ISSUE TITLE
Handle focus in edit mode

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#109]
@tnajdek Some time ago I prepared focus styles that are applied when `li.metadata` has the `.editing` class. Now that we have a permanent form in the edit mode I would suggest to use a `.focus` class instead, which could also be used to tab through the form.

Basically we would need an equivalent of the still not available CSS `:has :focus` selector – so if an input inside the `.metadata` element gets the focus, we set a `.focus` class on `.metadata`. 

![screen shot 2018-06-20 at 16 51 10](https://user-images.githubusercontent.com/419747/41666712-6cad77be-74ab-11e8-9260-30bd2f76396e.png)

This should work for most of the metadata fields, but there are expections. There are fields that will not have any focusable input inside, like the _Item Type_ field (which should open an overlay with the select options). I guess we can fix this by adding `tabindex="0"` to an element inside. 

![screen shot 2018-06-20 at 17 10 50](https://user-images.githubusercontent.com/419747/41667634-bce49328-74ad-11e8-8943-ebafd3c19655.png)

And there are fields like the _Creators_ field, which have a button inside, so we need a way to differentiate between `.metadata.focus` and `.metadata button:focus`.

![screen shot 2018-06-20 at 17 15 57](https://user-images.githubusercontent.com/419747/41667644-c276f330-74ad-11e8-91a4-7df4e776b733.png)

**Comment by tnajdek** [comment]
> @tnajdek Some time ago I prepared focus styles that are applied when li.metadata has the .editing class. Now that we have a permanent form in the edit mode I would suggest to use a .focus class instead, which could also be used to tab through the form.

I've introduced a new class `.has-focus` for all `.metadata` fields in 1070d0bf2842e7efa2d70d588135aef455ce97b6 as part of #120 but should work for this purpose as well?

**Comment by flachware** [comment]
@tnajdek yes I think this class could do the trick – but currently it doesn’t get set in edit mode on mobiles yet, but we would need it particularly in this case.

**Comment by flachware** [comment]
@tnajdek do we actually still need the `editing` class on the items?

**Comment by flachware** [comment]
When I tab from `title` to the first `creators-entry` and from the last `creators-entry` to the next field, two items get the `has-focus` class at the same time.

![screen shot 2018-08-07 at 14 39 24](https://user-images.githubusercontent.com/419747/43776312-bbc919b0-9a4f-11e8-838f-3a670f8c34ff.png)

**Comment by flachware** [comment]
@tnajdek I use `:focus-within` now, you can remove all instances of `.has-focus` (and close this issue then).

**Comment by flachware** [comment]
@tnajdek good to close?
