### ISSUE TITLE
Add citation tab to items

### ISSUE THREAD

**Issue by stakats** [zotero/web-library#113]
Rather than the current button, this seems like a good place to include a formatted citation, with style selector like we have at zbib.org. Selected styles could also be a user preference that gets stored.

**Comment by tnajdek** [comment]
@stakats: That would work for a single item, what about when multiple items are selected? I've anticipated this to work via a toolbar button in a similar fashion to how current version of web-library works.

**Comment by stakats** [comment]
I didn't know multiple items could be selected in web-library. In the desktop client when there are multiple items selected, the item pane just goes blank except for a count.

**Comment by tnajdek** [comment]
Closing in favour of #134
