### ISSUE TITLE
Creators

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#120]
**Preparations**
* [x] Add and hook up edit/done button in touch header on tablets
* [x] Toggle `editing` class on `.metadata-list` in `xs` and `sm` size

**Desktop**
* [x] Add Sortable component
* [x] Add AutoResizer to last name Editable

**Mobile / Touch**
* [x] ~~Disable editables in default and edit mode~~
* [x] Reuse (–) Delete button
* [x] Additional (+) Add Creator button
* [x] Add Modal component
* [x] Tap on creator opens modal
* [x] Modal content

**Comment by flachware** [comment]
Desktop:
![desktop](https://user-images.githubusercontent.com/419747/43005822-4560d796-8c34-11e8-8f14-ac1e486484bc.png)

Phone default:

![phone-default](https://user-images.githubusercontent.com/419747/43005851-5a06eb7c-8c34-11e8-9783-14962b59fa7c.png)

Phone edit mode:

![phone-edit-mode](https://user-images.githubusercontent.com/419747/43005864-68707e8a-8c34-11e8-8a76-642cfa6399f0.png)

Phone modal:

![phone-modal](https://user-images.githubusercontent.com/419747/43005872-6e0cee0a-8c34-11e8-805f-6c5a5b98f1bc.png)

Tablet default:

![tablet-default](https://user-images.githubusercontent.com/419747/43005888-799b6e22-8c34-11e8-81ea-67ee334f2003.png)

Tablet edit mode:

![tablet-edit-mode](https://user-images.githubusercontent.com/419747/43005894-7ff2338c-8c34-11e8-904a-02a8b988664b.png)

Tablet modal:

![tablet-modal](https://user-images.githubusercontent.com/419747/43005912-8907f772-8c34-11e8-936e-d90e70ccb1be.png)

**Comment by flachware** [comment]
@tnajdek I think it’s time to tackle the creators fields, above please find some mockups.

For starters I’d suggest to do some preparations that simplify testing: currently the metadata-list is always in edit mode in `xs` and `sm`, I’d say let’s fix this first – therefor we will need an edit/done button in the 'tablet header' first.

I would do the desktop version next, this involves mainly the Sortable component and I believe I could enhance the behavior of the editable layout if i had an AutoResizer in the last name editable.

The mobil/touch version will be the most complicated, so I’d save it until last. I guess the main part here will be the Modal component.

Let’s discuss the details for each to-do when we are on it.

**Comment by flachware** [comment]
I gave it a try and replaced the _tablet header_ with the `TouchHeaderContainer`. Currently the visibility classes are baked-in in the `TouchHeader` component. So the first thing we would need to even see the component in the tablet size would be configurable visibility classes. There are lots of combinations, I think it would be best if we just had something like a `visibility` prop in the `TouchHeaderContainer` component that lets us pass a string of arbitrary visibility classes?

**Comment by flachware** [comment]
@tnajdek looks good to me! I didn’t mean to complete the `TouchHeader`, just being able to switch the 'edit mode' is exactly what I had in mind. In the `sm` tablet size the `editing` class on `.metadata-list` doesn’t get toggled for some reason yet, could you have a look at this next?

**Comment by tnajdek** [comment]
@flachware seems like there was a discrepancy between js and scss breakpoints, should be fixed now.

**Comment by flachware** [comment]
Wait, now the `editing` class does not get toggled on `.metadata-list` in xxs anymore.

**Comment by tnajdek** [comment]
we can stick with the current one, just call the smallest one `xxs`. I've missed it in the conditions, should be ok now.

**Comment by flachware** [comment]
@tnajdek next thing we need would be a sortable component. I think for a sortable component it would be preferable if we could restrict the dragging to the vertical dimension. But if it is much easier to solve with the browser’s native drag and drop I think it would be fine choose this variant for the time being (like the sorting of the to-do lists here on GitHub or e.g. like the sorting of lists in Tropy’s sidebar).

In any case, there should be a drag-handle element as a direct child of `li.creators-entry`.

**Comment by tnajdek** [comment]
We already use `react-dnd` for dragging items to collections so it makes sense to re-use the same library for drag-sorting (it will work like sorting here on github). Also it needs some refactoring around creators (which are quite complex already) so it might take me a day or two.

Do we have an icon to use as a handle?

**Comment by flachware** [comment]
@tnajdek I encountered an issue with the native select in default mode in the tablet size: native selects always have the width of the longest option, thus the text of shorter options doesn’t look right aligned. Several solutions came into my mind:
* We use an editable and get rid of the disabled native select in this state. 
* We use a hack like this one: http://jsfiddle.net/FSsG8/444/
* I was wondering if we could remove all options except the selected one from the select in this state?

What do you think?

<img width="527" alt="screen shot 2018-07-25 at 17 12 58" src="https://user-images.githubusercontent.com/419747/43210296-fd19a57c-902e-11e8-8ed0-f122a5c85243.png">

**Comment by tnajdek** [comment]
Creators fields should now be sortable via drag-n-drop on desktops. Will figure out touch devices next.

**Comment by tnajdek** [comment]
> In the desktop version the handle should only show up on hover. This works basically, but when an adjacent creator item takes the place of the dragged-away item, the drag handle shows up for this item too (so it is in the hover state). Can we prevent this?

Sure, it's possible to add css class when item is being hovered over. In `<CollectionTree>` I've used `.dnd-target`, would that be ok here as well?

> If there is only a single creator, I think we should not show the handle / disable dragging.

Yes, I agree. Also if last item is "virtual" (i.e. it is newly-added and completely empty) it won't be draggable, otherwise it might be not clear why there is no "plus" icon.

> Could you set a dragging class on the dragged item instead of setting the opacity? This would give me more flexibility stylewise. Do we have any control over the drag preview? E.g. I would like to hide the border in the drag preview.

With HTML5 backend we're not responsible for rendering *ghost* browser is doing it. This guarantees much better performance but imposes some limitations. We can modify the item that stays behind (currently I reduce the opacity to 0 to make it disappear but keep space occupied), however we cannot modify the *ghost*. Thus I can set `.dragging` on the item but it will only apply to the item in the list, not the *ghost* that is being dragged. Alternatively it's possible to apply `.dragging` just before the item is dragged in which case it would apply to both the *ghost* and the item in the list.

It is possible to render a completely custom *ghost*, however that comes with performance penalty so I opted for browser-rendered *ghost* where possible. As a matter of fact we need to produce custom *ghost* for touch users (because of html5 native drag-n-drop support limitations), that's already implemented.

> One more issue that you are probably aware of anyway: using the creator’s + button crashes the web library.

That should be fixed now

**Comment by flachware** [comment]
> Sure, it's possible to add css class when item is being hovered over. In <CollectionTree> I've used .dnd-target, would that be ok here as well?

I fear I didn’t explain that well, please have a look at the screenshot below, it might explain it better. You can see two items in hover state, one is the ghost and the other is the item that moved to the former place of the item that is currently being dragged – although the cursor is _not_ hovering over that item. The `dnd-target` class could solve it in part, but not while you don’t actually hover over that item.

![screen shot 2018-07-30 at 12 24 47](https://user-images.githubusercontent.com/419747/43392562-52b0c3da-93f4-11e8-9770-72e2eaae4c5f.png)

**Comment by flachware** [comment]
>With HTML5 backend we're not responsible for rendering ghost browser is doing it. This guarantees much better performance but imposes some limitations. We can modify the item that stays behind (currently I reduce the opacity to 0 to make it disappear but keep space occupied), however we cannot modify the ghost. Thus I can set .dragging on the item but it will only apply to the item in the list, not the ghost that is being dragged. Alternatively it's possible to apply .dragging just before the item is dragged in which case it would apply to both the ghost and the item in the list.

Could we have two classes, like `before-dragging` (which I would use to remove unwanted borders from the item in the list and thus from the ghost) and `dragging` (which I would use to adjust the opacity and also as a selector to style subsequent items)?

**Comment by flachware** [comment]
>As a matter of fact we need to produce custom ghost for touch users (because of html5 native drag-n-drop support limitations), that's already implemented.

Is there a way I can block the custom ghost so I can inspect it better?

On my real iPhone the custom ghost isn’t positioned correctly, it permanently sticks to the top of the screen (screenshot below). In the Chrome emulator it works most of the time, but the ghost freezes frequently for me.

<img src="https://user-images.githubusercontent.com/419747/43393543-dc01175e-93f7-11e8-8591-d13595f1806a.png" width="320" height="568">

**Comment by flachware** [comment]
@tnajdek why do we actually disable all `+` buttons in creators except the last one? Wouldn’t it make more sense to keep them all enabled so the user can quickly add creators in between without resorting?

**Comment by flachware** [comment]
@tnajdek could we have a `has-focus` class on `.creators-entry` that gets set when _anything_ inside has the focus (including `.is-focused` of the Select)?

I’m hiding the buttons on desktops currently (they are still focusable), but they are always in place and take up space. With that class I could remove them entirely while they are invisible.

**Comment by dstillman** [comment]
> why do we actually disable all + buttons in creators except the last one?

Presumably because that's what the client does (I think mostly for simplicity), but the ability to add a new one at any position is a fairly common request, so yes, we should allow that. The new row should mirror the creator type and field mode of the row containing the + button that was clicked.

**Comment by flachware** [comment]
Sounds good to me.

**Comment by tnajdek** [comment]
> Is there a way I can block the custom ghost so I can inspect it better?

In Chrome, with touch device emulator enabled, while dragging press **f8** on the keyboard to start the debugger. At this point it should be possible to inspect `.drag-layer` element that contains the ghost. This will not work for native ghost (on desktops) because, I've mentioned before, we're not rendering that.

> On my real iPhone the custom ghost isn’t positioned correctly, it permanently sticks to the top of the screen (screenshot below). In the Chrome emulator it works most of the time, but the ghost freezes frequently for me.

On the iOS emulator it seems to work but scroll is not disabled on the first attempt so it's tricky to move a creator down (because it scrolls as you drag). Surprisingly it works on the second attempt. On hardware mobile chrome it works pretty well. At this point I'm not sure how to make this a better experience, needs more investigation.

> could we have a has-focus class on .creators-entry that gets set when anything inside has the focus (including .is-focused of the Select)?

Yes, that should be possible though not as trivial as it sounds. Will work on that today.

> Presumably because that's what the client does (I think mostly for simplicity), but the ability to add a new one at any position is a fairly common request, so yes, we should allow that. The new row should mirror the creator type and field mode of the row containing the + button that was clicked.

That was exactly the case, I'll tweak it to allow adding creators anywhere. There is a question of what happens when user adds a new creator and won't fill in the name. In the client you have to either enter the name or remove that creator to be allowed to add a another one, I've copied this behaviour here but it might be less obvious what's happening if the new "virtual" creator is not the last one on the list.

**Comment by flachware** [comment]
@tnajdek a minor issue, could we round the coordinates of the creator-drag-preview? Floats can lead to blurriness currently.

**Comment by flachware** [comment]
@tnajdek I just realized that you already set and use the `dnd-source` class, that’s great. Please forget what I said about the `.before-dragging` class, it makes no sense, I must have missed that we use our own preview on touch devices.

**Comment by tnajdek** [comment]
@flachware I've tested drag n drop on the actual iPhone (iOS 11.4.1) and it matches exactly what I'm seeing in the emulator i.e. the first drag causes scroll, afterwards it seems to work flawlessly (gif below). I've not seen the bug you've seen where ghost would be positioned incorrectly.

On Android Chrome I've not seen the scroll-to-refresh gesture being detected anymore so it works pretty well (it still hangs very occasionally, any touch clears it).

I've also tested Android Firefox, it seems to be fully functional though performance is abysmal (~1fps when dragging on Google Pixel 1).

I'd say we're good to go on Android but still need to fix the iOS issue.


![120-scroll-on-first-drag mov](https://user-images.githubusercontent.com/214628/43545249-5010c49c-95cd-11e8-82b5-ec9e40395d94.gif)

**Comment by flachware** [comment]
@tnajdek I can confirm that dragging hangs occasionally and touch clears it on any platform.

In the Chrome iOS emulator (Chrome v68.0.3440.84) it does not behave like in your screencast above, it works as expected for me. Why do we differ?

On my iPhone 5 running iOS 10.3.3 the creator-drag-preview immediatly jumps to the top of the screen whenever I drag a creator. Please have a look at the web inspector screenshot below. It looks like the creator-drag-preview is simply lacking the position inline styles. Note the empty `style` attributes on `body` and `#zotero-web-library` instead.

>I've also tested Android Firefox, it seems to be fully functional though performance is abysmal (~1fps when dragging on Google Pixel 1).

Why do we actually have a performance issue here? (To me it looks like we are just translating a very simple element around and now and then we need to reorder a rather short list – sorry for being naive  : )

Rounded coordinates look good to me.

![screen shot 2018-08-02 at 10 27 49](https://user-images.githubusercontent.com/419747/43572053-cb3be040-963e-11e8-8530-b875d3c1418f.png)

<img src="https://user-images.githubusercontent.com/419747/43571659-d3e9494a-963d-11e8-97a2-845ce00836d9.png" width="320" height="568">

**Comment by tnajdek** [comment]
> In the Chrome iOS emulator (Chrome v68.0.3440.84) it does not behave like in your screencast above, it works as expected for me.

If you refer to Chrome device toolbar (where you can select from multiple devices) while it can be used for testing across viewports and general touch vs mouse quirks, it won't emulate specific device/browser quirks. In reality iOS uses different rendering engine so what you see in Chrome, even with iOS device picked from the device list, will be more representative of that what you would see on Chrome Android.

> Why do we differ?
 
I'm using Safari on iOS emulator built-in in Xcode on macOS. It's generally very close to what you'd see on the actual device. The screencast above was identical behaviour to one I've seen on an iPhone 8 running latest iOS.

> On my iPhone 5 running iOS 10.3.3 the creator-drag-preview immediatly jumps to the top of the screen whenever I drag a creator. Please have a look at the web inspector screenshot below. It looks like the creator-drag-preview is simply lacking the position inline styles. Note the empty style attributes on body and #zotero-web-library instead.

While it's definitely worth investigating, I'd say it's not super urgent as it works fine on latest iOS. My guess is it's something to do with the lack of support for drag-n-drop api (https://caniuse.com/#search=drag)

> Why do we actually have a performance issue here? (To me it looks like we are just translating a very simple element around and now and then we need to reorder a rather short list – sorry for being naive : )

We also need to observe what's under cursor, decide whether it's valid drop target, re-arrange nodes to reflect the drop-zone etc. That being sait it Still should be possible to get it work relatively smoothly, definitely better than how it behaves right now. I'll investigate this, but again I'd say it's lower priority issue.

**Comment by flachware** [comment]
Oh, I didn’t realize that you are using the Xcode iOS Simulator – I can reproduce the behavior of your screencast on that one (I’m aware that the Chrome iOS emulator in the dev tools uses a different rendering engine).

If you prefer we can make the iOS 10.3.3 and performance glitches separate issues.

**Comment by flachware** [comment]
@tnajdek so for the AutoResizer in the _last name_ editable, can we have that without breaking ZBib?

**Comment by flachware** [comment]
@tnajdek could you add a `.single` class to `.creators-entry` for items with just one creator? I would need that to remove the padding on the right side so we can use that space where otherwise the handle would be.

**Comment by tnajdek** [comment]
@flachware it's done. Please bear in mind that virtual entries also do not render drag handle, these now get `.virtual` to make them targettable.

Virtual entry (maximum one allowed) is an entry that user has created but never entered any value. It always appears on the bottom of the list. It's not pernament and might disappear e.g. when you reorder the list or navigate away.

**Comment by flachware** [comment]
@tnajdek thanks!

**Comment by flachware** [comment]
@tnajdek I gave it a try and removed the creator buttons unless the `has-focus` class is set on the item. However, I suppose this creates kind of a race condition: the buttons can only be focused when they are displayed but in order to set the `has-focus` (which makes them displayed) class the buttons need to get the focus first.

Can you verify that this assumption is correct?

**Comment by tnajdek** [comment]
yeah, that seems to be the case. When you keep the cursor over the creator, tab will correctly jump to the button (because it's visible via the :hover path). Otherwise it seems browser blurs the field, repaints and moves focus to the next valid target (next creator/field)

**Comment by flachware** [comment]
Ok, I’m using different styles now to hide the buttons, this works principally. Tabbing to the plus button (only this one) does not set the `.has-focus` class on the creator item – could you have a look at that?

**Comment by flachware** [comment]
@tnajdek a little design update that might be of interest soon: originally I planned to put the creator select (_author_, _editor_, ...) into the modal on mobiles. But I realized that, properly speaking, the user wouldn’t have a clue that the creator type could be edited at all, as it would have looked like a regular label. So I figured it would be better to allow the user to directly use the native select in edit mode (that’s exactly how it works currently), with the only difference, that I would indicate the selects with our link color.

Do you approve of this approach? 

Phone edit mode:

<img width="320" alt="phone-edit-mode 2x" src="https://user-images.githubusercontent.com/419747/43884235-d95ee01a-9bb5-11e8-9b2a-66937c003335.png">

Phone modal:

<img width="320" alt="phone-modal 2x" src="https://user-images.githubusercontent.com/419747/43884236-d979af3a-9bb5-11e8-85e8-934eef8a57b2.png">

**Comment by tnajdek** [comment]
@flachware Personally I find it confusing that creator type can be changed on one "screen" (on mobile) but editing name(s) requires additional "screen". Perhaps instead we could somehow increase discoverability of the select box the editing modal? Either with color like here, or maybe with an icon (because there's more space)

**Comment by flachware** [comment]
@tnajdek I’m not worried about the select in the modal. Users might not realize that this is a select, but they would realize that this value is editable. I’m following the iOS approach here: elements that open a new screen (a modal) have a chevron. Inputs and selects (which open a picker) look identical by default (like in the calendar app).

But how would you know that you have to go to that screen to edit the creator type in the first place?

And isn’t it consistent that simple selects open a picker on screen and more complex elements open a new screen? E.g. in the contacts app there is a similar situation, you can edit both the left and the right part in the form. _Privat_ and _Österreich_ have a chevron here because they open a new screen – the address type on the left (_Privat_) opens a new screen because it is more complex than a simple select (you can create a custom label) and the country list opens in a new screen so you can have an index nav that allows you to quickly pick the first letter of the country.

We could open an new screen with the creator type select too, but that meaned we would lose precious space because of the additional chevron and we would have to create that new screen while we already have a working select element.

<img width="320" src="https://user-images.githubusercontent.com/419747/43892470-50c92870-9bcc-11e8-935c-a53fc4375fb3.png">

**Comment by tnajdek** [comment]
On the screen from contacts app, "complex" editable are clearly separated from the "simple" ones. On the suggested design there is no clear border between the author type and their name(s).

I'm not an expert in UX, it's just in my personal opinion that it could be frustrating going into creator edit mode and not finding creator type there.

**Comment by flachware** [comment]
That’s a fair point, according to the contacts UI there would have to be a border between the creator type and the name (mockup below).

I see two problems with this: a) we are running out of space, b) the 'rows' are less noticeable now, that could cause confusion where the handles actually belong too.

So maybe it would be best to stick to the original draft. It does contain a UX flaw in my eyes, but it might be the best compromise we can achieve here. 

<img width="320" alt="zeichenflache 4 2x" src="https://user-images.githubusercontent.com/419747/43945392-3a332fa0-9c82-11e8-82c1-0f2b5eff36b9.png">

**Comment by tnajdek** [comment]
@flachware yes, this should be ok.

**Comment by flachware** [comment]
@tnajdek Do I understand correctly that the `.creators-entry` element itself would be the modal trigger? If so, could you set `tabindex="0"` on `.creators-entry` whenever it has the `.creators-modal-trigger` class?

The creators field is more complex than the other fields, I think we can’t just use the `:focus-within` approach here, instead we could use the `:focus` state on `.creators-entry` to highlight the entire field and `:focus` on the remove button to highlight the button.

![screen shot 2018-09-12 at 17 00 42](https://user-images.githubusercontent.com/419747/45434094-dc837400-b6ad-11e8-8fc8-485ce1bf2571.png)
---
![screen shot 2018-09-12 at 17 02 28](https://user-images.githubusercontent.com/419747/45434100-de4d3780-b6ad-11e8-9708-0053afd82ab8.png)

**Comment by flachware** [comment]
@tnajdek Next step would be to add the _Add Creator_ button (have a look at the phone edit mode mockup on top). I think if we could have an additional `li.metadata.add-creator` containing a button after the last creator we should be fine.
