### ISSUE TITLE
Rework mouse, touch, and keyboard classes

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#123]
@tnajdek I think we didn’t get those classes completely right: let’s assume you are in touch mode on a touch device and hit the `tab` key. the `keyboard` class would be set instead of the `touch` class and the layout would immediately switch to the desktop version, because it’s the default layout mode. So basically the touch class decides upon desktop or touch layout.

We just have two layout modes but three classes, so I think the `keyboard` class should just be a modifier class. That means the `mouse` and `touch` class should still be mutex, but the `keyboard` class should be a modifier class that can be toggled independently. I think we can keep all the classes on the same element, we would have the following combinations: `.mouse`, `.touch`, `.mouse.keyboard`, `.touch.keyboard`.

The `mouse` and `touch` classes are used to decide the layout mode, the `keyboard` class is only used to show/hide focus states of specific elements.

As the styles require those classes to work consistently, I feel like we should prioritize this issue.

**Comment by tnajdek** [comment]
How it's done currently, it's not possible to unset keyboard class once **Tab** was pressed. Should there be? Perhaps pressing **Esc** could unset keyboard class?

**Comment by flachware** [comment]
I think the keyboard class should be unset once you click or tap?

**Comment by tnajdek** [comment]
ok, that makes sense, this should be done now. Please feel free to re-open if I got it wrong/misunderstood something.

**Comment by flachware** [comment]
Looks good to me!
