### ISSUE TITLE
Nicer items placeholders

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#127]
When loading items list, we're showing items placeholders to keep layout stable (see #49). This works well, but could be enhanced:

* [x] Use something nicer than `...` to represent item's value
* [x] Find a better way to estimate number of items in places where it is not known ahead of time (e.g. "Trash", "All Documents")

**Comment by tnajdek** [comment]
@flachware I could definitely use your help with the first one here.

**Comment by flachware** [comment]
@tnajdek I’ll have a look at it when we start styling the item table, I think abstract 'wireframe' placeholders like we use in the illustrations of the homepage could look nice.

**Comment by tnajdek** [comment]
Yes, I think that would look great. Let's put it on hold for now, once you get to it, let me know if you need any help.

**Comment by dstillman** [comment]
And why not use just use "Loading items…" like in the client or some other sort of spinner? The "..." is certainly no good, but I feel like even wireframe placeholders, though in vogue these days, are going to be distracting, at least when you have fewer items in the view than the full height.

**Comment by tnajdek** [comment]
My arguments for keeping placeholders:

* Stable interface: it's a big part of the UI that would become a spinner for half a second before becoming a table again
* I'd argue placeholders are nice when the items count is known and a spinner would hide this extra piece of information (i.e. how many items in the collection if less than screen's height)
* We need placeholders anyway to support loading new items via infinite scrolling

**Comment by dstillman** [comment]
What about when the count isn't known, though? Then you'd see a full screen of placeholders potentially turn into a few (or no?) rows.

**Comment by tnajdek** [comment]
Great designs, let's implement!

> I would need a `.placeholder` element in `.metadata.title` and `.metadata.creator-year` instead of the `...` in the list and a `.placeholder` element in each table 'cell' (plus an additional `.placeholder-icon` in the title cells).

Done for the `<ItemsTable>` component. In the `<ItemsList>` I'm reusing existing DOM nodes to display placeholders. Does that work fro you? I've also added temporary styling so I can see it's working, please feel free to make it nicer.

> if we want some irregularity this can be done with Sass’ `random()` function (varying width, empty cells).

I'd probably just hardcode the desired widths in px rather than use `random()`.

> It strikes me that currently it seems like the number of items isn’t known ahead of time in regular collections, is this meant to work like that?

That was a glitch, it should work now.

**Comment by flachware** [comment]
@tnajdek styles for the ItemsList placeholders are in place. Could you give me stable `nth-3` and `nth-4` classes in the ItemsTable analogous to the `odd` class? We would have four different type of rows then, that should be fine. If we wanted empty placeholder cells we would need the index of the item as class, but I realized that we probably shouldn’t 'promote' missing metadata in the table, so let’s go with the four different rows for now.

I noticed that the placeholders don’t always show up immediately (even in the build version), are they displayed as fast as possible?

**Comment by tnajdek** [comment]
`nth-3` and `nth-4` are in.

> I noticed that the placeholders don’t always show up immediately (even in the build version), are they displayed as fast as possible?

I can see a delay when scrolling, hopefully it can be eliminated. I'll investigate this when I get time.

**Comment by flachware** [comment]
@tnajdek ItemsTable placeholder styles are in place.

So for the 'special collections' case ('My Library', 'Trash', etc.), shall we switch to a spinner there (and show the items directly once they are loaded, without placeholders)?

**Comment by stakats** [comment]
This sounds good to me, and in line with what @dstillman was saying earlier.
