### ISSUE TITLE
Support for moving collections?

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#129]
We should probably support moving collections into and out from another collections (nesting). The most obvious thing to do this would be with drag-n-drop. Any suggestions, ideas?

**Comment by flachware** [comment]
Drag and drop should work fine on desktops, but on touch devices we will need something like a `...` icon for each collection that has a `move` option that opens a modal that lets you pick the destination.

**Comment by tnajdek** [comment]
- [ ] Support drag-n-drop for collections on desktop devices
- [ ] Support via "..." -> "move collection" menu with modal for picking destination on touch devices

**Comment by tnajdek** [comment]
Related: #227
