### ISSUE TITLE
Select options are not showing on "high density" desktops

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#130]
@flachware it seems at some point we've added `overflow:hidden` to `.form-control`. This breaks select boxes on high density desktops (div with options rendered by react-select is not visible). I suspect this rule was added as part of #122, so removing it would break native selects. Could you please have a look?

**Comment by flachware** [comment]
@tnajdek good catch! Just a minor regression due to leaking styles which I added to truncate text in native selects.
