### ISSUE TITLE
Upgrade to react-select 2.0

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#131]
https://react-select.com/upgrade-guide

**Comment by tnajdek** [comment]
@flachware react-select 2.0 is a complete rewrite and they've changed all the styles (they now use css-in-js). I've adapted our code to mostly work with the new version but styles are broken again. Would you mind having a look? I've pushed changes to a branch [131-upgrade-react-select](https://github.com/zotero/web-library/tree/131-upgrade-react-select).

**Comment by flachware** [comment]
Note: wait until the CSS-in-JS theme can be disabled entirely: https://github.com/JedWatson/react-select/issues/2706.

**Comment by tnajdek** [comment]
At this stage we might want to roll out our own select component, considering we need to heavily customize it anyway.

**Comment by tnajdek** [comment]
I've replaced `react-select` with our own custom component. From outside there should be no visible difference.
