### ISSUE TITLE
Colored tags incorrectly enabled/disabled

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#132]
With pagination it isn't possible to say whether given colored tag actually appears in given collection and thus whether it should be enabled or disabled.

Potential solutions:

1. Keep colored tags in natural sort (i.e. not move them to the top)
2. Only display tag selector when all tags are downloaded
3. Tweak api to allow sorting tags in such a way that colored tags are returned first.

**Comment by tnajdek** [comment]
#64 #104

**Comment by tnajdek** [comment]
4. For each colored tag, run a **HEAD** request to https://api.zotero.org/users/2769109/items?tag=red-tag and check if Total-Results is > 0

**Comment by tnajdek** [comment]
For each colored tag, run a HEAD request to https://api.zotero.org/users/$USERID/items?tag=tagname and check if Total-Results is > 0

**Comment by tnajdek** [comment]
zotero/dataserver#83

**Comment by dstillman** [comment]
Now that there's a tags-within-items request, I think you can do a regular GET for

`<userOrGroupPrefix>/collections/<collectionKey>/items/tags?tag=<colored tag 1> || <colored tag 2> || <…>'`

and just check for which tags are returned? You'd use the same other parameters as the main tags-within-items request, and you'd only have to do this when the tags were paginated.
