### ISSUE TITLE
Add remaining context menu actions to collections

### ISSUE THREAD

**Issue by stakats** [zotero/web-library#142]
To match the client we would need all of these. Some have a lower priority, e.g. "Delete collection and items" and "Generate report"

- [x] New subcollection
- [x] Rename collection
- [x] Delete collection
- [ ] Delete collection and items
- [x] Export collection
- [x] Create bibliography from collection
- [ ] Generate report from collection

**Comment by tnajdek** [comment]
@stakats I've created a separate issue #220 to track the "lower priority" ones for post 1.0 release.

**Comment by stakats** [comment]
Generate bibliography from collection currently includes child items (notes and attachments). It should only use top-level items.

**Comment by tnajdek** [comment]
@stakats thanks, that's a good point, should be fixed now. Should we do the same for export?

**Comment by stakats** [comment]
Yes, we should do the same for now. But later, if we wanted parity with the client, we would offer an option to include notes in the export.

**Comment by tnajdek** [comment]
Actually, based on few brief tests, API will include notes in exported data regardless of whether all or only top-level items are requested. But I've corrected the endpoint anyway.
