### ISSUE TITLE
Refactor touch header

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#149]
* [ ] Add options to touch header
* [x] Add previous icon to touch header
* [x] Fix keyboard navigation

Wireframes:
[touch-header-phone.pdf](https://github.com/zotero/web-library/files/2560830/touch-header-phone.pdf)
[touch-header-tablet.pdf](https://github.com/zotero/web-library/files/2568431/touch-header-tablet.pdf)
[touch-header-lg.pdf](https://github.com/zotero/web-library/files/2568432/touch-header-lg.pdf)

**Comment by flachware** [comment]
@tnajdek I realized that each touch header has to work a bit differently. I think it’s best if you browse through the wireframes above to see the differences.

Basically, the more touch headers a layout has, the less levels they have to handle. Another crucial difference is that we have an additional 'items' level on phones only (which we will hopefully get rid of at some point).

Here is an overview of all touch headers we will need:

Phone: `.library .touch-header`
Tablet: `.collection-tree .touch-header`, `.items .touch-header`
Large: `.collection-tree .touch-header`, `.items-container .touch-header`, `.item-details .touch-header`

To me it looks like the logic is pretty complex, please let me know if the wireframes look correct to you.

**Comment by tnajdek** [comment]
@flachware I've followed wireframes and implemented all the touch header variants. I hope it all matches but would appreciate if you could confirm, thanks!

Also for `.items-container .touch-header` we actually don't use the `TouchHeader` component, I've added some styling to make "fake" touch header appear as expected, please feel free to change as you see fit.

**Comment by flachware** [comment]
@tnajdek awesome!

On md and lg screens, when there is no selection in the sidebar, you set 'All Items' in the fake touch header – I think this is a good idea. Because on tablets we have the situation that there can be e.g. 'My Library', 'lots of subcollections', etc. in both touch headers at the same time. Could we prevent that and always set 'All items' in `.items .touch-header` when there is no selection in the sidebar? I think it looks weird and confusing currently.

How do you feel about the initial item list on tablets and large touch devices? I think we should not render an item list as long no library has been selected and show a placeholder instead.

**Comment by flachware** [comment]
@tnajdek I added a 'previous' icon to `TouchNavigation` as planned in the drafts. I would need your help to only insert that icon when there actually is a previous level. To make adding / removing look nice it would be cool if we could use react-transition-group to fade in / fade out the icon.

**Comment by tnajdek** [comment]
@flachware On tablets and desktops in touch mode, once a collection is selected, how should it be deselected? How to display "Items" in currently opened collection or "All Items" in current library?

In other words, if I'm in the scenario presented in *touch-header-tablet.pdf* on page 3, how do I list "All Items"? The only way I can find is to go back to Libraries and then again to "My Library".

**Comment by flachware** [comment]
@tnajdek good point. I think we will need the additional 'All Items' / 'Items' node on all touch devices.

**Comment by flachware** [comment]
@tnajdek when you select a collection in the collection tree there is a transition between 'next' and 'current' in the touch header. However, when you go back to the parent level the value in 'current' seems to be removed immediately, hence there is no transition back to 'next'. Is there a way to have a transition between 'current' and 'next' in both directions?

**Comment by flachware** [comment]
@tnajdek I believe we have to refine the touch-header for keyboard navigation: currently we have a tabindex on `.before-last`, `.previous`, `.current`, and `.next`. I just moved the tabindex to the `.truncate` element inside, so we get a proper outline. But we would still need a way to set the tabindex only on the `.truncate` element inside `.previous` and `.current` (otherwise hitting the tab key will break the touch-header layout). Could you have a look at that?

**Comment by tnajdek** [comment]
@flachware anything left on this issue or can we close it?

**Comment by flachware** [comment]
I think this one is good to close.
