### ISSUE TITLE
Refactor item list

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#150]
* [x] Split ItemList into ItemList and ItemTable component
* [x] Fixed position of first and second line
* [x] Add colored tags to item list
* [x] Attachments (#191)
* [x] Notes (#191)
* [x] Select UI
* [x] Export UI
* [x] Bibliography UI (#134)
* [x] Add to collection UI
* [x] 'No items' hint
* [ ] Keyboard navigation
* [x] Sorting
* [x] Style item list

**Comment by tnajdek** [comment]
@flachware I'd like to implement selection mode on mobiles and I'm wondering how it should work:

* Should it be triggered (e.g. via a dedicated button in touch header)
* Should it render checkboxes (when triggered or always?)

**Comment by flachware** [comment]
@tnajdek I would say there should be a selection mode on mobiles which should be triggered via an option in the '...' touch header menu. I would render checkboxes, but only in selection mode.

**Comment by flachware** [comment]
@tnajdek I think the `.odd` class doesn’t get set correctly – I guess this happens because the index in the modulo calculation probably starts with 0?

**Comment by tnajdek** [comment]
It's correct in the sense that the list is 0-indexed hence it `.odd`  doesn't get set for the first element of the sequence, but does for the second and every other then. Happy to swap it around, however this is consistent with items table if we change it we should probably do so in both places?

**Comment by flachware** [comment]
Yes, please swap in both places.

**Comment by flachware** [comment]
@tnajdek I think we should improve the UX of the selection of items (I believe currently it is as good as it gets with our existing set of UI components, but our set might simply be incomplete). The main flaw I see with our current workflow is that the user has to go back into the 'same' dropdown he/she picked the 'Select Items' from, unaware that the content of that dropdown has changed after the selection.

To me, the 'selection mode' is very similar to the 'edit mode' we have within an item. So I think what we could do is: switch to a 'selection mode' touch-header (change the content of the touch-header or show a different one, whatever is easier), to make it more clear that you are in a different mode now. And, most important here, introduce a new UI component, the 'touch-footer'. The 'touch-footer' does not appear until you are in 'selection mode', which makes it clearly a hierarchical part of the 'selection mode'. The icon buttons in the 'touch-footer' are disabled until you select at least one item, so it obvious that there are some actions available at this point.

What happens next when you tap a button in the 'touch-footer' is a different story which we will have to look at anyway, but I think for the actions that can’t be performed directly there will be a modal in the next step (Add to Collection, Export, Library).

What do you think?

Initial situation:

<img width="320" alt="select-items-1 2x" src="https://user-images.githubusercontent.com/419747/52416840-d376c180-2aea-11e9-88c0-db8d4b97390c.png">

Switch to selection/edit mode:

<img width="320" alt="select-items-2 2x" src="https://user-images.githubusercontent.com/419747/52416842-d671b200-2aea-11e9-9bee-1dd1f66a3408.png">

Selection/edit mode with touch-footer:

<img width="320" alt="select-items-3 2x" src="https://user-images.githubusercontent.com/419747/52416844-d96ca280-2aea-11e9-89fe-21650467f2d1.png">

Selected items:

<img width="320" alt="select-items-4 2x" src="https://user-images.githubusercontent.com/419747/52416848-dbcefc80-2aea-11e9-9502-bae4b603784c.png">

**Comment by tnajdek** [comment]
This is pretty and I very much like the concept. My only concern is how well this works on other touch devices, especially horizontal tablets (1024px where we have a horizontal split). But in general I agree, let's go ahead with this.

**Comment by flachware** [comment]
One common solution on iOS on the iPad is to place the icons to the left side of the 'touch-header'.

But this is going to be tight with 5 icons (if we do not want to hide some of them behind an '...' icon). So I’d actually suggest to hide the `.item-details` in 'selection mode' on horizontal tablets (1024px). I think I would also rather not show anything in `.item-details` in the largest touch layout while you are in 'selection mode', we could just show the info-view ('97 items in this view').

Ok, implementation – do you want me to add a dummy 'touch-footer'?

**Comment by flachware** [comment]
@tnajdek `.editing` class looks good to me. What’s the best way to hide the item-details when the items-list is in editing mode on landscape tablets? I think with CSS the only clean way would be a class on `.items` (similar to the active class).

**Comment by flachware** [comment]
@tnajdek I styled the touch-header in select mode and updated the structure of that touch-header.

The idea is that every touch-header gets a Toolbar with `toolbar-left`, `toolbar-center`, and `toolbar-right` inside (feel free to convert those to components). This way we already have a layout system and we don’t need any additional classes to position an icon button, link button, or heading left|centered|right. I’ll update the remaining touch-headers too (it should also be possible then to have a nav and a toolbar).

Currently we have just one kind of heading (X Items Selected), could we have 'Select Items' | '1 Item Selected' | '2 Items Selected'?

**Comment by flachware** [comment]
@tnajdek re select-mode: when an action like duplicate or delete has been chosen, I think we should leave the select-mode afterwards automatically.

I’m not entirely sure but I feel like 'selected' and 'active' items are not interchangeable. So I would suggest that if there is an active item to not automatically select it in select mode. And related, I think the item-details in select-mode should look the same as in default mode without any active item (it should never show metadata in select-mode, that is).

**Comment by tnajdek** [comment]
@flachware all good points, to recap:

- [ ] Leave "select mode" after user performs an action on selected item(s)
- [ ] Prior to entering select mode, clear currently selected item key
- [ ] Prevent item details pane from showing in "select mode" when single item is selected

I'll look into this.

**Comment by flachware** [comment]
@tnajdek sounds good to me (the items details should show the 'info view').

**Comment by tnajdek** [comment]
All actions go back to the items list with select mode off (still need to add context-based actions to the touch footer in order to test properly) with the following exceptions:

* "Duplicate" opens the new item details
* "Export" and "Bibliography" do nothing (select mode stays on)

@flachware do you think we should also leave "select mode" after succesful "export" action (when the modal closes)? What about "bibliography".

**Comment by flachware** [comment]
@tnajdek looks good to me. I think we should leave select mode after 'export' and 'bibliography' too.

**Comment by tnajdek** [comment]
@flachware export has a clear "success" point (when user confirms export), however "bibliography" won't have one - should we close when user opens the modal or closes it?

**Comment by flachware** [comment]
@tnajdek I think we should leave the select mode when the user closes the bibliography modal.

But let’s have a closer look: how is the bibliography dialog going to work?

**Comment by flachware** [comment]
@tnajdek re export: I think the export modals (in the touch-header and touch-footer) should both work like the 'better New Item modal' – showing the spinner instead of the modal-content after export confirmation.

**Comment by tnajdek** [comment]
> But let’s have a closer look: how is the bibliography dialog going to work?

Bibliography should work similarly to zbib (see #134). The 'confirm' action will probably be "copy to clipboard", we might use that as a signal to switch off the select mode as well maybe?

**Comment by flachware** [comment]
@tnajdek I added some dummy icons to the item list. I hope we will be able to show the attachment and note icons accordingly? Besides the logic of showing and hiding the correct icons and colorizing the tag icons correctly we need to swap `12/circle` and `12/crescent-circle` with `12/circle-active` and `12/crescent-circle-active` for active items.

I’m hiding the `.icons` container right now with CSS for `.item.placeholder`, just give me a shout if this isn’t necessary.

**Comment by tnajdek** [comment]
Tag circles are implemented and are looking great! For attachment/notes indicator we would need changes in the API, I've created a separate issue to keep track (#191)

**Comment by flachware** [comment]
@tnajdek looks good to me – we still need to swap the tag circle icons for active items, as described above.

**Comment by flachware** [comment]
@tnajdek re 'no items' hint, on phones it does not make sense to show the 'Items' node for empty collections. Could we instead insert a placeholder instead, like:
```
<li>
  <div class="item-container placeholder">
    <div class="truncate">No Items</div>
  </div>
</li>
```

The placeholder node should not be tapable (and thus not slide in `.items`).

**Comment by tnajdek** [comment]
> @tnajdek re 'no items' hint, on phones it does not make sense to show the 'Items' node for empty collections.

@flachware Currently, to add a new item, user needs to enter `Items` and then select `New Item` from the touch header. If we replace `Items` with non-clickable `No Items` how would one do that?

**Comment by flachware** [comment]
@tnajdek that’s a good question. Does anything speak against having a `New Item` option in the touch-header of empty collections?

**Comment by tnajdek** [comment]
It should be ok. Does it make sense to include `New Item` option when there are items in the collection for consistency?

**Comment by flachware** [comment]
I think that should be fine.

**Comment by flachware** [comment]
@tnajdek what about sorting in the item list? Could we add two entries in the touch-header menu 'Sort by: Title' and 'Sort Order: Ascending' that allow you to change sorting and the sort order? The first entry would have to open a modal with radios and the second would basically toggle the sort order.

**Comment by dstillman** [comment]
Can it be a drop-down menu instead of a modal?

**Comment by flachware** [comment]
Our current dropdown menus are a weak point on phones at the moment as they are not scrollable and thus can’t handle larger option lists. And dropdown submenus have basically been banned as UI elements for mobiles generally.

Our modals are scrollable on phones, that’s why they are the easiest solution at the moment.

That said, I have been thinking about two other approaches on and off: first, we could switch from the dropdown to a popup and make popups scrollable on phones (e.g. let them take the lower half of the screen). second, make dropdowns scrollable on phones (make them look like the phone version of a popup).

A third option would be to limit the number of sort options to say a handful of popular fields. This way we could just add those options to the existing dropdown, or add a dedicated sort icon next to the '...' icon in the touch header with its own dropdown menu.

So let’s clarify this first, which fields should be available for sorting? A handful? The ones we have in the web-library’s item table currently (9)? The ones in the client (11)? All client fields (including those from 'More Columns' (30)?

**Comment by dstillman** [comment]
One model is what GitHub does right here for comment menus — it's a drop-down-y popup on desktop and a modal with buttons on phone. The important thing is just that it's two clicks/taps either way, one to open and one to select, as opposed to a modal where you have to make a selection and then click a button to close it.

As for how many, it depends somewhat on whether we'll have a column picker like in the client. (I don't have web-library running, so I can't remember if we have that already.) But it would be limited to however many you have visible, at least.

**Comment by flachware** [comment]
Yes, we already have a column picker in the web-library. But, some user might always visit the web-library via a touch device, so would we limit to the default table columns in that case?

I agree that there shouldn’t be an additional confirmation step, but e.g. the 'move mail' modal in iOS doesn’t require that either. I think our options are:

1) We use a modal without confirmation
2) Make dropdowns scrollable on phones and put everything in one dropdown
3) Make dropdowns scrollable and put the sort options into a dedicated sort dropdown next to '...'

This is how a scrollable dropdown could look like on phones:

<img width="320" alt="scrollable-dropdown@2x" src="https://user-images.githubusercontent.com/419747/54759060-a0e1dd80-4bed-11e9-86db-806a722c471c.png">

**Comment by flachware** [comment]
@tnajdek I prepared some focus styles for the items list. Tab focus works fine for small viewports and larger, but the items never get the focus on phones for some reason – do you have any clue what’s going on there?

Apart from that the items list still lacks keyboard navigation: enter key to select focussed items, up/down arrows to move the selection, some browser allow scrolling via space/shift + space, I don’t know if the virtualized list is capable of that in general.

**Comment by flachware** [comment]
@tnajdek could you give me a `last-item-active` and `last-item-focus` class on `.items-list` when the very last (not the virtual last but actual last) item is active / has the focus? I would need that to remove the last hairline in those cases.

**Comment by tnajdek** [comment]
> @tnajdek I prepared some focus styles for the items list. Tab focus works fine for small viewports and larger, but the items never get the focus on phones for some reason – do you have any clue what’s going on there?

It seems that tabbing still goes over collection tree hence you don't see it on items list. I'll try to fix it (that logic is quite complex now)

> Apart from that the items list still lacks keyboard navigation: enter key to select focused items, up/down arrows to move the selection, some browser allow scrolling via space/shift + space, I don’t know if the virtualized list is capable of that in general.

Ok, I'll add keyboard navigation there. Do you think pressing space should work as scroll or as select?

**Comment by tnajdek** [comment]
> Yes, we already have a column picker in the web-library. But, some user might always visit the web-library via a touch device, so would we limit to the default table columns in that case?

Column picker doesn't make sense on touch, we always show the same set of information for each item. I believe for sorting we should offer all columns, even if that means that if user does switch from touch to mouse UI, tables will be sorted by invisible column. You can achieve the same effect in desktop version by hidding column with active sort (also works in the client). I'm not entirely sold on the scrollable dropdown UI thing, wouldn't that look odd on larger screens? That being said I can't think of anything else to fit the bill.

**Comment by flachware** [comment]
> Do you think pressing space should work as scroll or as select?
I think we should stick to the standard browser behavior, so space should work as scroll (unlike form elements).

**Comment by flachware** [comment]
Re sorting, I think we have two good options:

1) Use a modal that does not need confirmation with just a 'Cancel' button in the header. The long list of sort options is easily accessible this way but still does not bloat the '...' dropdown menu. It’s a good thing that the modal looks different than the dropdown, it makes it more clear to the user that the dropdown options and the sorting options are on two different levels.

2) Make dropdowns scrollable. On phones this could look like the mockup above, on larger touch devices we could keep the current appearance but set a max-height on the dropdown and flash the scrollbar a sec (and/or choose the max-height of the dropdown in a way that it clips the last visible option text). But if we want to offer all columns as sort options, I think we should put the sort options into a dedicated dropdown menu next to the '...' menu.

**Comment by tnajdek** [comment]
@flachware I'd say let's go with option 1. The list will need not only all the sortable columns but also order (ascending/descending)

**Comment by flachware** [comment]
@tnajdek ok, I thought about using radios as list in the modal, e.g.:
```
.form
  .radio
    input[type="radio"]
    label
```

I would style them similar to iOS.

In the '...' dropdown there would be two options, 'Sort by: Title' (which opens the modal) and 'Sort order: Ascending' (which toggles the sort order). I think we can put the ascending/descending directly into the '...' dropdown? It would save a step and the modal without confirmation only allows for one selection, I guess it would be annoying if you want to set both in there but the modal closes automatically after the first choice.

**Comment by flachware** [comment]
@tnajdek the sort modal looked good out of the box – that’s pretty cool!

Any chance to make it confirmless whenever the `.keyboard` class is not set (because in this case you use the up/down keys to 'move' the :checked state)?

**Comment by flachware** [comment]
@tnajdek the confirmless modal looks good to me.

**Comment by tnajdek** [comment]
Looks like the only thing remaining here is keyboard navigation which is generally limited on touch. I've created a more broad issue to track that #414 so I believe this issue can be closed.
