### ISSUE TITLE
Refactor item table

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#151]
* [x] ~~Implement _click to edit_ to allow for direct editing of metadata in the item table~~
* [x] Remove title column from column-selector (do not allow removal of the title column)
* [x] Style item table
* [x] Keyboard navigation (see #218)
* [x] Scrollbar clips item outline

**Comment by tnajdek** [comment]
>  Implement click to edit to allow for direct editing of metadata in the item table

@flachware I don't feel that's necessary. Any particular reason to allow editing this way? I don't think we have equivalent in the client either.

**Comment by dstillman** [comment]
Yeah, we don't have in-place editing for items in the client (only for collections). I think @stakats likes it in Tropy, but I'm not sure it makes sense for us — if you're editing an item in Zotero, you should probably be looking at the full data in the right-hand pane and making sure it's all correct, since there's no particular reason to think any problems are only in the fields that show up in the middle pane. (This is also what makes it different from, say, renaming files in Finder.)

I think you're more likely to just trigger this accidentally while working with items than to actually have a good reason to use it.

**Comment by flachware** [comment]
I just kept a record of the feature request. @stakats, from your user perspective, do you think the feature would be a gain for Zotero (I believe the relation between the table and the metadata pane is quite similar between Tropy and Zotero)? I think it could be a handy and intuitive nice-to-have feature to e.g. fix a typo. In any case it could be post 1.0.

**Comment by flachware** [comment]
@tnajdek I added a `.truncation` wrapper and thus changed `return String` to `return` in `table.jsx`. If that’s a security issue somehow, please have a look and recheck.

**Comment by flachware** [comment]
@tnajdek could you set a `.scrollbar-style-permanent` class on `html` when the browser uses non-overlay scrollbars?

Another class that would be helpful would be `.column-header` for the element that has `role="columnheader"`.

**Comment by flachware** [comment]
@tnajdek thanks for the two classes.

Could you have a look at the tag colors in the table and switch to the `-active` symbols for active items?

**Comment by flachware** [comment]
@tnajdek reordering does not work once a column has been resized. There is also an issue that might be related: when you resize a column the column gets picked as sorting column. If it helps, i can set `pointer-events: none` during `.resizing` on `.items-table-wrap` or `.column-header` (I don’t set it for now to not interfere with debugging).

**Comment by flachware** [comment]
@tnajdek could we prevent reordering of the title column, so that the item type icons are always in the first column (like in Finder)?

**Comment by flachware** [comment]
@tnajdek could we hoist the `.reorder-source` class to the `.column-header`? If so, I could adjust the position of the `.reorder-target` indicator to the right side. The indicator doesn’t make sense when you drag a column to the right side currently.

**Comment by tnajdek** [comment]
> @tnajdek could we prevent reordering of the title column, so that the item type icons are always in the first column (like in Finder)?

I'm not sure we should do that - I generally try to match the client behaviour where user can move title column (together with tags and item type icon) freely.

**Comment by tnajdek** [comment]
> The indicator doesn’t make sense when you drag a column to the right side currently.

Why is that? Currently if you drag to the right beyond 50% of the column width, column to the right becomes a "target" for re-ordering.

**Comment by tnajdek** [comment]
Relevant commit (forgot to tag with this issue): 68c373c6c95d8e9ec05f554f79b7e6c76e91dba1

**Comment by flachware** [comment]
@tnajdek have a look now. the reorder-target indicator now always indicates the spot where the reorder-source column will be droped 'between'.

The preview is accurate with the result. However, I think something is wrong with the calculation. It is most notable when you drag a narrow column over a very wide column to the right. In this case it can happen that you are still over the wide column but the indicator (and the actual drop) is already between the next and after next column.

**Comment by dstillman** [comment]
> could we prevent reordering of the title column, so that the item type icons are always in the first column (like in Finder)?

(It pains me that this is possible in the client, but some people — including @stakats, I think — like to have the creator first. It's an abomination.)

**Comment by flachware** [comment]
Then we could still do what we do in Tropy: the first column is always the 'main' column and gets the item type icon and the tags.

**Comment by flachware** [comment]
@tnajdek could we increase the min-width of the title column (about twice as large)? Currently the entire title text and all tags can get clipped.

**Comment by tnajdek** [comment]
> @tnajdek could we increase the min-width of the title column (about twice as large)? Currently the entire title text and all tags can get clipped.

That's done, the minimum size of the title column is now set to 10% (previously was 5% as all the other columns). You might need to run `localStorage.clear()` to see this actually working.

**Comment by flachware** [comment]
@tnajdek new min-width of the title column looks good to me.

**Comment by flachware** [comment]
@tnajdek could we remove the tabindex from the `.ReactVirtualized__Table__Grid` element? It inserts an additional step in the tab cycle.

**Comment by flachware** [comment]
@tnajdek re task 'scrollbar clips item outline': when you tab around in the item table and permanent scrollbars are enabled, the focus outline of the items is clipped by the scrollbar. This happens because react-virtualized adds the scrollbar width as padding to the items. Is there a way to tell react-virtualized to shrink the width of the items by the amount of the scrollbar width instead of the padding?

**Comment by flachware** [comment]
@tnajdek re keyboard navigation: in terms of accessibility I think it has to be possible to select focussed items by hitting enter.

In terms of power users key up and down should move the selection (active state). This seems to work to a certain degree already, but as far as I can tell up/down keys also scroll the table, which I guess should only happen once the selection reaches the top or bottom of the scrollable element (and then the selection should stay stable, I guess Finder is a good model here)? Moving the selection with up/down seems to stop at some point.

**Comment by flachware** [comment]
@tnajdek for some reason setting the tabindex to null does not work, `.ReactVirtualized__Table__Grid` still gets the focus. Apparently it can be removed by using `-1`, but I don’t understand why no tabindex does not prevent focussing.

**Comment by flachware** [comment]
@tnajdek just double checked, I still get this step between the table header and first item:

![Screenshot 2019-04-11 at 13 37 13](https://user-images.githubusercontent.com/419747/55954545-3ad1fe80-5c5f-11e9-8cd4-e21b54e7a59b.png)
![Screenshot 2019-04-11 at 13 38 18](https://user-images.githubusercontent.com/419747/55954554-3dccef00-5c5f-11e9-88e4-5b0da5f0236d.png)
![Screenshot 2019-04-11 at 13 37 37](https://user-images.githubusercontent.com/419747/55954561-41607600-5c5f-11e9-9eab-3c2d206cd172.png)

**Comment by tnajdek** [comment]
@flachware Turns out this is browser-specific, that's why I couldn't see it in Chrome. I tested in Firefox and in behaved as you described so I've decided to explicitly set `tabIndex` to -1 to get that behaviour inline across browsers.

**Comment by flachware** [comment]
@tnajdek now I’m even more confused, because the screenshots I’ve posted above are from Chrome. Do you have an idea why that div gets the focus without tabindex in the first place?

**Comment by tnajdek** [comment]
@flachware I'm guessing it's because of `overflow: hidden auto`. With no `tabindex` set on that element, removing that style causes Firefox to skip this item when tabbing.

It seems to be confirmed by: https://allyjs.io/data-tables/focusable.html

Not sure about Chrome, as I've mentioned before I see different behaviour.

**Comment by flachware** [comment]
@tnajdek Ah, I didn’t know that – thanks for figuring it out. So, I can reproduce this in Chrome 73.0.3683.86: When there is a div with `overflow-y: auto` and it actually has an overflow, then this element is tabbable by default.

**Comment by flachware** [comment]
@tnajdek I styled the items drag indicator. Two details I would like to change: currently, when a row is a drag source we set an opacity of 0.5 (via inline styles), could we leave that to 1? And could we remove the offset from `getNextToCursorStyles` (which would be `getToCursorStyles` then I guess), I think it would be more flexible and convenient if we did that in CSS.

**Comment by tnajdek** [comment]
I feel like this one is done? Please reopen if needed.
