### ISSUE TITLE
Attachment metadata missing

### ISSUE THREAD

**Issue by stakats** [zotero/web-library#152]
In the desktop client we show:
- original URL
- filename
- access time
- number of pages
- modified time
- index status
- related
- tags

Todo:

- [ ] Revisit attachments pane to enable viewing above metadata
- [x] Add missing metadata for stand-alone attachments

**Comment by tnajdek** [comment]
I suspect "number of pages" and "index status" are only available in the client and not propagate to the api (@dstillman please correct me if I'm wrong). Rest should be possible.

**Comment by dstillman** [comment]
> I suspect "number of pages" and "index status" are only available in the client and not propagate to the api

Correct.

**Comment by tnajdek** [comment]
I've included missing data on stand-alone attachments where we have an entire tab to display this data, however "tags" and "related" are displayed as separate tabs, as with other items.

For actual attachments that have a parent item, we had no plans in web library to provide any data other than title and the download url or the original url. We might need to redesign the "attachments" tab to accommodate for this data. Do we want to do this? Is it a 1.0 priority?

**Comment by dstillman** [comment]
We should have that eventually for client parity, but I don't think it's a 1.0 blocker.

**Comment by flachware** [comment]
@tnajdek I think this issue has been covered by #298, is this good to close?
