### ISSUE TITLE
Spinner variants

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#155]
@tnajdek could you add two spinner variants so we could have `<Spinner />`, `<Spinner small />`, and `<Spinner large />`?

**Comment by tnajdek** [comment]
@flachware it's already possible to pass an additional css class name to the spinner, e.g. `<Spinner className="small" />`, would that be sufficient?

**Comment by flachware** [comment]
@tnajdek if that works for you, it works for me too. I reworked the spinner styles, please keep an eye on spinner sizes or positions and let me know if if something looks strange to you – maybe I have overlooked an instance.

I removed some styles from `_react-modal.scss`, do we actually have the `.loading` state in the web library? I couldn’t find that instance of the spinner, if it exists, we would need a `<Spinner className="large">` now in there.

**Comment by tnajdek** [comment]
Looks good to me!
