### ISSUE TITLE
Refactor Item Actions

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#157]
Currently there are two sets of item-related actions: in the toolbar in mouse mode and underneath the "..." menu in touch mode. These will be merged into a single container component with different presentation components.

The following item actions are planned:

|Action|Icon|Label|Location: Mouse|Location: Touch|Comment|
|---|---|---|---|---|---|
|New Item|Yes|No|Toolbar|"..." Menu|On touch devices will use modal or item-details pane to select item type TBC|
|Trash|Yes|No|Toolbar|TouchFooter|Disabled when in trash or no items selected|
|Add to Collection|No|Yes|N/A|TouchFooter|Only visible on touch devices where it opens a modal|
|Remove from Collection|No|Yes|Toolbar|TouchFooter|Only enabled when in collection|
|Restore to Library|No|Yes|⚙️ Menu|TouchFooter|Only visible when in trash|
|Delete|No|Yes|⚙️ Menu|TouchFooter|Permanently deletes, Only visible when in trash|
|Select Items / Cancel|No|Yes|N/A|"..." Menu|Toggles selection mode, Only visible on touch devices|
|Export ▼|No|Yes|Toolbar|"..." Menu + TouchFooter|Dropdown on desktop, Opens modal on touch|
|Cite|Yes|?|Toolbar|"..." Menu|Opens modal|
|Bibliography|No|Yes|Toolbar |"..." Menu + TouchFooter|Opens modal|
|Duplicate Item|No|Yes|⚙️ Menu|TouchFooter|Not Implemented yet|
|~Show in Library~|~No~|~Yes~|~⚙️ Menu~|~"..." Menu~|~Not Implemented yet~|
|Merge Items|No|Yes|⚙️ Menu|"..." Menu|Post 1.0 feature|

**Comment by flachware** [comment]
@tnajdek I would like to unify the look of the toolbar (also in respect of the current and future client) and avoid the mix of icon and text buttons. Could we say item actions are accessible either via an icon button or a menu entry on desktops?

**Comment by tnajdek** [comment]
Personally I'm fine with that, I think icons you've added so far look good. Also we probably should disable "..." icon on desktops when no items are selected, I'll look into it.

**Comment by flachware** [comment]
Alright. Yes, we should disable the '...' button on desktops when no items are selected.
