### ISSUE TITLE
Tooltips for buttons

### ISSUE THREAD

**Issue by stakats** [zotero/web-library#159]
Following the (future) desktop client:

- [x] New Item
- [x] Move to Trash
- [x] Remove from Collection
- [x] Export
- [x] Create Bibliography
- [x] New Collection (next to personal and group libraries)
- [x] More (next to collections)

**Comment by dstillman** [comment]
These [are being simplified](https://github.com/zotero/zotero/pull/1535) in the client.

**Comment by stakats** [comment]
Thanks, fixed!
