### ISSUE TITLE
Load top-level collections in alphabetical order

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#164]
As collections load and are displayed in the left pane, new collections appear interspersed in the list, presumably from a subsequent request. We should load collections from the API in alphabetical order and using `collections/top` so that the initial display doesn't change.

**Comment by tnajdek** [comment]
We now show a spinner (either global for user library, or next to library name when opening a group library) and build a complete collection tree while spinner shows, hence this no longer applies.
