### ISSUE TITLE
Implement override for selecting touch or mouse interface

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#169]
Currently we detect user type based on `matchMedia` and touch/mouse events. It would be nice to offer user option to override detection and instead go with user preference.

Split from #45

**Comment by dstillman** [comment]
Do we know what iOS does for Request Desktop Website? Is there a way to respect that?

**Comment by tnajdek** [comment]
AFAIK this only changes browser's useragent. I believe it's meant as a fix for websites that sniff useragent and serve different content. That being said it's [probably possible to detect it](https://stackoverflow.com/questions/58019463/how-to-detect-device-name-in-safari-on-ios-13-while-it-doesnt-show-the-correct/58064481#58064481), just not sure if one is meant to.

**Comment by dstillman** [comment]
I don't know why not — I'd much rather use that native UI (which you can even make persistent for a site) than some custom toggle on every site, and I'm incredibly annoyed when that option just gives me the same mobile site I was trying to avoid.

**Comment by tnajdek** [comment]
No problem, we can also sniff for "Request Desktop Website" mode.

I believe we still need to have this as a user preference/swtich on top of that though. This is to cater for laptops/touch devices like Dell XPS and all the 2-in-1 laptops where web library switches from mouse to touch and vice versa depending on whether user happens to touch the screen or the touchpad/mouse. There is no "Request Desktop Website" mode on these devices, because these are already standard desktop browsers.

**Comment by tnajdek** [comment]
https://forums.zotero.org/discussion/104797/web-library-view-changes-when-clicking

In this scenario user should be able to lock one mode or the other (in this particular case user prefers touch mode on desktop) and "Request Desktop Website" would not be sufficient.

**Comment by tnajdek** [comment]
https://forums.zotero.org/discussion/109336/web-version-switching-constantly-between-old-and-new-page-design
