### ISSUE TITLE
Implement error handling

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#186]
- [x] Try to recover from API returning HTTP 500 by retrying
- [x] Display error when unable to recover
- [x] Handle HTTP 412  as an error until streaming api support is implemented
- [x] Handle HTTP 413 when trying to generate bibliography for more than 150 items (or a collection that contains at least that many items)

**Comment by tnajdek** [comment]
@flachware I'd greatly appreciate your input on how we should handle communicating errors to the end-user: where should errors be displayed, what sort of options should we offer to the user etc.

Here are some cases to expect:

* Library has been updated remotely and we're out-of-sync (needed until streaming api support is implemented)
* User has no access to given library (due to misconfiguration, url manipulation or "hacking" attempt)
* User has no access to a group library he tried to open (could be by following legitimate link to a private group and not being signed in or being signed in as a user with no access)
* User attempted to modify library he only has read-only access
* API returns "backoff" or 429 (meaning we're about to hit rate-limiting or we just did, unlikely to happen in normal library editing)
* API consistently returns 5xx for a request (we retry once or twice then give up and inform user)

**Comment by flachware** [comment]
@tnajdek I believe we have three different kind of errors here (at least):

- Out-of-sync error: I think we could have a sync icon in the toolbar (if manual sync is possible), a pie chart icon during sync, and an error icon with a popup if the library is out-of-sync or if the sync failed. have a look at these sync mockups: https://basecamp.com/2673480/projects/12077128/todos/358922505

- no access error: Does anything speak against loading https://www.zotero.org/user/login/ in these cases?

- 429 and 5xx errors: I think these errors require some kind of notification. The main question here is if it’s ok to only show one notification at a time (the last one) or if we need to show a list of notifications. Former would probably result in a (static positioned) bar in the interface, for the latter we could have a macOs-like (fixed positioned) notification list in the top right corner, whereas some notifications could require confirmation and others automatically hide after a delay – depending on the notification type. The notification list would cover part of the interface and would be scrollable.

**Comment by tnajdek** [comment]
@flachware web-library sync is different than desktop: we only keep subsets of data locally (in memory) and send off any updates as soon as they happen (rather than wait for explicit "sync"), thus we can't implement sync icon as per mockups. Also the best we can do when things get out of sync is throw away local data and refetch.

I've introduced a new sync icon on desktop: currently it has one of three states:

1. Green: library is in sync
2. Red: library is out of sync, i.e. we've received 412 during update
3. Spinner: there are ongoing requests

Clicking on the icon, if it's red, resets the library.

Let me know what you think.

**Comment by tnajdek** [comment]
@flachware I've implemented basic error handling where errors are processed and rendered. Could you please have a look at styling?

For testing purposes, you can spoof an error by running the following on the console:

`window.WebLibStore.dispatch({ type: 'ERROR_', error: 'error message' })`

**Comment by flachware** [comment]
@tnajdek re sync: I fear I don’t fully understand the differences in terms of syncing between the web-library and the client, so here is just a best guess from my side how it might work:

1. library is in sync: no icon
2. library is out of sync: orange warning icon
3. syncing: spinner or animated pie chart, depending on the possibility to show progress

On touch devices I’d put this icons to the rightmost position in the touch-header toolbar above the sidebar, respectively the only toolbar on phones.

**Comment by flachware** [comment]
>@flachware I've implemented basic error handling where errors are processed and rendered. Could you please have a look at styling?

Do we want to show one error notification at a time or a list of notifications?

**Comment by tnajdek** [comment]
@flachware not sure actually, probably a list. In current implementation (with basic html and no styling) we show a list, individual errors can be dismissed. On the other hand duplicate, consecutive errors are grouped into one, so to get more than one error, user would probably need to take multiple actions. I still think it makes sense to display a list, but we could go either way?

**Comment by flachware** [comment]
I’d say let’s go for a list then. In terms of styling I’d use the list approach as described:

> for the latter we could have a macOs-like (fixed positioned) notification list in the top right corner, whereas some notifications could require confirmation and others automatically hide after a delay – depending on the notification type. The notification list would cover part of the interface and would be scrollable.

**Comment by flachware** [comment]
@tnajdek I get this error when I try to raise an error – what am I doing wrong?
```
VM5139:1 Uncaught TypeError: Cannot read property 'dispatch' of undefined
    at <anonymous>:1:20
```

**Comment by tnajdek** [comment]
@flachware only thing I can think of is you haven't restarted `npm start`?

**Comment by flachware** [comment]
@tnajdek I’ve added some basic styles for the errors to make them a scrollable layer above the interface. How about using the 'errors' component for all different kind of notifications (warning, info, success, …)?

**Comment by tnajdek** [comment]
> How about using the 'errors' component for all different kind of notifications (warning, info, success, …)?

I'm not sure if we have any notifications, other than errors, but if we do (or will have), that's a good idea.

**Comment by flachware** [comment]
@tnajdek what about the syncing feedback (see my comment above)?

**Comment by tnajdek** [comment]
> 
> library is in sync: no icon
> library is out of sync: orange warning icon
> syncing: spinner or animated pie chart, depending on the possibility to show progress

Done, we might even consider not showing "syncing" state, especially on mobile where space is at a premium.

> On touch devices I’d put this icons to the rightmost position in the touch-header toolbar above the sidebar, respectively the only toolbar on phones.

I'm not sure if I understood correctly, please have a look and correct me if I'm wrong. Not sure if where I've placed it looks all that well, it makes the UI jumpy.

**Comment by dstillman** [comment]
Wait, why do we have a sync icon? This is a website. A sync icon isn't going to make any sense to people.

We obviously should have streaming support, but even without that, why would we need a sync icon? If there's a 412 on upload, it should be dealt with automatically.

(Sorry, should've commented on this thread sooner.)

**Comment by tnajdek** [comment]
Changed so it resets library to remote state + displays error. We might want to reword error and maybe tone it down (e.g. make it a warning?)

**Comment by tnajdek** [comment]
I feel like this one can be closed, please reopen if needed.
