### ISSUE TITLE
Firefox browser zoom mis-sizes viewport

### ISSUE THREAD

**Issue by fcheslack** [zotero/web-library#194]
When using zoom levels greater than 100% in Firefox, the viewport can extend vertically beyond the actual window which can cause parts of the interface to be inaccessible. This also happens when settings devPixelsPer > 1 in about:config. Chrome's zooming does not suffer from this problem.

**Comment by flachware** [comment]
@fcheslack I believe this has been a more general issue, the items in the collection-tree have been stretching the whole interface in Firefox (in all zoom levels). Does it look correct now?

**Comment by fcheslack** [comment]
Yes, works great now.
