### ISSUE TITLE
Long titles that trigger overflow hide colored tags in items list

### ISSUE THREAD

**Issue by fcheslack** [zotero/web-library#195]

**Comment by flachware** [comment]
I can’t reproduce this – do you mean the items table by any chance?

**Comment by tnajdek** [comment]
@flachware yeah, it's in the items table (it used to be called items list before touch/desktop split)

![web-library-195 mov](https://user-images.githubusercontent.com/214628/54026705-b212ff00-4196-11e9-85ae-3ded854b5ffe.gif)

**Comment by flachware** [comment]
Alright, thanks for clarification.
