### ISSUE TITLE
Feature: Cite

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#203]
@tnajdek something to think about: once we add the 'Cite' option to the touch-footer we will have 7 buttons in there. I can make those buttons fit in there, but it’s less than ideal (we might want to keep it like that for 1.0 though).

**Comment by flachware** [comment]
@dstillman @tnajdek I suppose the citation modal will roughly work like the one on ZoteroBib, plus

- citation style selector
- language selector

And, as you are able to select multiple items, I guess we need a list of the items that lets you specify page, book, chapter, etc. for each item?

**Comment by tnajdek** [comment]
https://forums.zotero.org/discussion/comment/343409/#Comment_343409
