### ISSUE TITLE
Items table: performance improvements

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#205]
Reduce the number of reconciliations, optimize so that it feels more snappy. Lag is very noticeable and quite annoying when using keyboard for selecting multiple items.

**Comment by flachware** [comment]
@tnajdek I’ve noticed some more regressions:
- [ ] When using the up/down keys the active item 'moves' out of sight
- [ ] When you click on an item and then hit tab, the items-table-body gets the focus, but the focus should directly jump to the tabs
- [ ] When you click on an item, then hit tab, then click another item, that item does not get the 'blue' focus state (as the styles expect the `.items-table` to have the focus, not `.items-table-body`. Where should I expect the focus to be?
- [ ] Currently, when you click an item and try to scroll using the page up/down keys it won’t work. The scrollable element (`.items-table-body`) or an element inside needs the focus for this to work.

**Comment by tnajdek** [comment]
Thanks, I'll have a look into these.

**Comment by tnajdek** [comment]
@flachware I wasn't able to reproduce issues with invalid focus. In current implementation `.items-table-body` shouldn't be getting focus at all. Could you please check if this still happens on your end?

**Comment by tnajdek** [comment]
@flachware actually I can see the issue with focus in Firefox so I guess it's browser specific. Let me investigate.

**Comment by flachware** [comment]
@tnajdek I still see the invalid focus issue in Chrome.

**Comment by flachware** [comment]
@tnajdek for styling reasons due to the rewrite, could we not render the `.items-list` in case it has no items (while items are being fetched or if a collection has no items)?

**Comment by tnajdek** [comment]
@flachware I had to change the approach as [some browsers make scrollable elements tabbable](https://allyjs.io/data-tables/focusable.html#scrollable-elements). The new apprach works in Firefox where previous one had issues with focus. I wasn't able to reproduce this in Chrome in either version so could you please check if the new version behaves as expected?

**Comment by flachware** [comment]
@tnajdek looks good to me. Making scrollable elements non-tabbable should simply work by setting a negative tabindex – but I guess it is a good practice to set the focus on the scrollable element instead of some other container?

**Comment by tnajdek** [comment]
@flachware I thought that would be the case but it turns out to be more complicated as such element then becomes focusable, i.e. clicking on a row (which is inert) puts focus on the scroll container.

Thanks for testing, I'm happy this finally works, closing the issue.

**Comment by flachware** [comment]
Make sense to me.

**Comment by flachware** [comment]
@tnajdek you can remove all code related to the classes `.last-item-active` and `.last-item-focus` – these classes are not needed anymore.
