### ISSUE TITLE
Style installer

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#208]
* [x] Enhance filtering
* [x] Prevent scrolling behind the modal (Addressed in #216)
* [ ] Sometimes backdrop with spinner slides in on touch devices

**Comment by flachware** [comment]
@tnajdek here are some mockups for the style installer modal:

<img width="1440" alt="citation-styles-desktop@2x" src="https://user-images.githubusercontent.com/419747/56303476-4f6d3580-613c-11e9-8793-53434c7f43bf.png">
<img width="320" alt="citation-styles-touch@2x" src="https://user-images.githubusercontent.com/419747/56303609-99561b80-613c-11e9-8320-fee75a0efbbd.png">

**Comment by dstillman** [comment]
I don't think we need the "three or more characters" bit — people will type three characters if they're not getting results. (I would also think we could start filtering, at least with `startsWith()`, with one or two characters. If someone wants Vancouver, they might as well be able to type "V".)

**Comment by tnajdek** [comment]
Personally I don't much like the remove icon on mobile, it looks like "do not enter" road sign. Could we maybe use an "X" instead of a "-", or perhaps change the shade of the red and/or make "-" more narrow? Other than that it looks great!

**Comment by dstillman** [comment]
That's pretty close to the standard delete icon on iOS after entering edit mode.

**Comment by dstillman** [comment]
Example: https://www.imore.com/sites/imore.com/files/styles/xlarge/public/field/image/2016/08/reminders-ios10-clear-reminders-screens-02.jpeg

**Comment by tnajdek** [comment]
Ok, didn't realize it's a commonly recognizable thing, please ignore my comment.

**Comment by flachware** [comment]
I would prefer immediate filtering too, starting with entering the first character (searching for words that start with that character) – so we don’t have to explain how the search works.

**Comment by stakats** [comment]
These look good to me.

**Comment by flachware** [comment]
@tnajdek I noticed that the `default|active|remove` buttons seem never to be in the `active` state – could you look into this?

**Comment by tnajdek** [comment]
@flachware @flachware I've changed the style search so the behaviour is as follows:

* if filter string **length is below 3 characters**, it will search for styles that **start with** given string
* if filter string **length is 3 characters or more**, it will search for styles that **contain** given string

I find it a bit weird that results appear to change completely when adding extra letter to the filter string but maybe isn't a problem, any thoughts?

**Comment by flachware** [comment]
I think the current behavior is problematic because you can enter two characters and end up with no results, but once you add one more character you get some results.

Would it be possible to search for words that **start with** the given string, no matter how many characters you enter (and probably sort the results in a way that styles starting with the string come first)?

**Comment by tnajdek** [comment]
I agree that it needs improvement but I'm not sure if filtering only for styles that start with given string is a solution.

I imagine there might be a case where user would search for "Biology" and pick from results. If we use "starts with" then the results are incomplete. Not sure if that's a real use-case though?

I'd rather use "contain" regardless of input length but then it makes very little sense with one or two letters. Perhaps use "contain" but sort in such a way that styles with name starting with filter appear on top of the list?

**Comment by flachware** [comment]
What I have been suggesting is actually a mix of 'start with' and 'contain' (but I don’t know if this is possible at all) – all style names that contain a **word** that starts with the string would be a match. E.g for 'Biology' you would get '**Biology** Letters' and 'ACS Chemical **Biology**' (but 'Annals of Microbiology' would not be a match).

If we have to choose between 'start with' and 'contain', then contain makes more sense to me – to me it looks like there is nothing wrong with a large list of results when your filter string is too vague.

**Comment by tnajdek** [comment]
@flachware I think we had more or less the same idea and I'm happy with the new implementation. Any feedback welcome!

**Comment by flachware** [comment]
@tnajdek filtering looks good to me. I have been wondering if we should scroll to top whenever you change the query and a new result list is displayed. But then again, this wouldn’t help if you are already at the top, so maybe that’s pointless anyway.

**Comment by flachware** [comment]
@tnajdek for the mobile version I need a new type of button that let’s me add an icon to a button without setting the `.btn-icon` class automatically. `.btn-icon` leads to transparent buttons with a certain padding etc. We might generally want the ability to add icons and text to colored buttons without that class being set.

In Tropy we solved this via an `icon` prop on the Button component that lets you pass an icon component, only in this case the `.btn-icon` class gets set. Or is there an easier way to override the `.btn-icon` class on demand?

**Comment by flachware** [comment]
@tnajdek I prepared the plus and minus buttons. Currently the buttons still show the strings of the desktop version (sorry, I couldn’t figure out how to swap the strings with icons without throwing an error).

In the `isTouchOrSmall` state *Active*, *Default*, and *Remove* should get the `24/minus` icon. *Add* should get the `24/plus` icon.

Re `.btn-icon` I’m not clear if we would lose a lot of stuff if we used a regular `<button>` element instead of the `Button` component, maybe that would be another option to bypass the `.btn-icon` class.

**Comment by flachware** [comment]
@tnajdek re `icon` prop, maybe this was a misunderstanding: In Tropy we pass the path of the icon as the value of the `icon` prop (thus you don’t have to insert an icon component into the button component anymore). I just realized that this prevents forgetting to set the prop whenever you want to create an icon button.

**Comment by flachware** [comment]
@tnajdek there are two issues with the style-installer modal:

1) Currently we set the `-after-open` class once the modal element is present so we can fade and slide it in on touch devices. However, when the modal has a loading state, the fade-in and the slide-in transitions are already fired once the `.modal-content` replaces the spinner, hence there is no slide-in animation anymore. Could we have another animation class that is immediately set after the `.modal-content` is inserted?

2) When reopening the style-installer modal for the second time and more often on a real phone, the modal animates to the top, revealing the item list behind. Honestly, I have no idea what’s going on there. Any clue?

<img width="320" alt="IMG_0106" src="https://user-images.githubusercontent.com/419747/56960853-73744200-6b52-11e9-9316-8536c3697d32.png">

**Comment by tnajdek** [comment]
>  Could we have another animation class that is immediately set after the .modal-content is inserted?

We currently remove `.loading` from `.modal` in that scenario, I can add `.ready` at that point, would that work?

> When reopening the style-installer modal for the second time and more often on a real phone, the modal animates to the top, revealing the item list behind. Honestly, I have no idea what’s going on there. Any clue?

I've tested on an actual device with both Chrome and Firefox and haven't seen this. Based on the screenshot looks like maybe something to do with the virtual keyboard not showing correctly (we focus search box so the keyboard should appear immediately)

**Comment by flachware** [comment]
I could use the removal of `.loading` to trigger the transition. However, it seems that `.loading` is removed before `.modal-content` is inserted. So, whatever class we use (removing `.loading` or setting `.ready`), the class must not be set before `.modal-content` is inserted.

I can reproduce the 'slide up' issue both in mobile safari and chrome on my iPhone. Did you test it on iOS or Android?

**Comment by tnajdek** [comment]
> I could use the removal of .loading to trigger the transition. However, it seems that .loading is removed before .modal-content is inserted. So, whatever class we use (removing .loading or setting .ready), the class must not be set before .modal-content is inserted.

Bit of a different approach: to help with the transition I've introduced a transition group on`modal-content` so it will receive `slide-*` classes, will that work?

**Comment by tnajdek** [comment]
@flachware Other than #270 I believe this is done? Please re-open if there is anything I've missed.

**Comment by flachware** [comment]
@tnajdek I think it is just the transition glitch that is left.
