### ISSUE TITLE
Item type icons

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#212]
* [x] Add license to SVGs (e.g. \)

**Comment by flachware** [comment]
@tnajdek I added about the half of the item type icons for testing. On low-res displays we need to switch to the 1x version of the 16px icons in the items table, could you add this condition? (The 28px icons don’t have a 1x version.)

**Comment by tnajdek** [comment]
> Add license to SVGs...

We can do this automatically during the build so that icons include extra comment when deployed. Would that work?

**Comment by flachware** [comment]
Sounds good to me.

**Comment by dstillman** [comment]
No, they should be licensed on GitHub.

**Comment by tnajdek** [comment]
I've added lincense header to all the .svg files. Also included a command that can be used to update future icons, it can be safely re-run as it checks for presence of license before injecting:

    npm run add-license

**Comment by flachware** [comment]
That’s great!
