### ISSUE TITLE
Notes pane

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#219]
**Notes pane desktop:**

<img width="360" alt="notes-pane-desktop@2x" src="https://user-images.githubusercontent.com/419747/57285663-f9910b00-70b3-11e9-9f47-7198c82b64e2.png">

**Notes pane desktop with editor:**

<img width="360" alt="notes-pane-desktop-editor@2x" src="https://user-images.githubusercontent.com/419747/57285729-1e857e00-70b4-11e9-810c-b690b7e10522.png">

**Notes touch device default mode:**

<img width="320" alt="notes-touch-default-mode@2x" src="https://user-images.githubusercontent.com/419747/57285960-9b185c80-70b4-11e9-9f16-603e31c8b0ae.png">

**Notes touch device edit mode:**

<img width="320" alt="notes-touch-edit-mode@2x" src="https://user-images.githubusercontent.com/419747/57285969-9e134d00-70b4-11e9-8577-13ddd5e587e7.png">

**Note modal touch device default mode:**

<img width="320" alt="note-modal-default@2x" src="https://user-images.githubusercontent.com/419747/57286024-baaf8500-70b4-11e9-835f-78a28c7c0224.png">

**Note modal touch device edit mode:**

<img width="320" alt="note-modal-edit-mode@2x" src="https://user-images.githubusercontent.com/419747/57286045-c8fda100-70b4-11e9-9eb1-03074da33679.png">

**Comment by flachware** [comment]
@tnajdek here are first mockups of the notes pane.

Desktops: By default you would only see the note list, when you select a note the editor pops up below the list. The editor would fill up the entire available space, the note list would have a max-height of 50% (in case there is an editor) and would be scrollable (as the editor). Duplicate and delete options would be behind the '...' icon.

Touch devices: In default mode there is just the list that lets you open individual notes, in edit mode '...' icons and an 'add note' button are added. Notes would open in a modal. Depending on the space the editor toolbars occupy (the editor in the mockups is just a placeholder), we could either always show the editor or save that space and provide for a default and edit mode in the modal.

Do we want a full-fledged editor on mobiles? Let’s discuss this in #62.

**Comment by tnajdek** [comment]
@flachware This is nice, especially on touch. On desktops I personally find there is too little visual separation between individual notes with no icon, but perhaps it's down to individual preference. Also on desktops the "..." menu seems oddly positioned, shouldn't that be vertically centered? Finally (also on desktops) does the "..." menu appear on hover (like in the tree) or on selection? Either way shouldn't there be margin left for it to avoid content shifting? In the mock up I imagine hovering/selecting first note would affect how the title is displayed.

**Comment by flachware** [comment]
@tnajdek Oh I totally forgot about single-line vs two-line notes in the list: I’d like to give it a try and use CSS line-clamp to truncate after the second line (decision based on a feature query). All browsers, mainly Firefox, that don’t support that feature would show single-line notes in the list.

So for the '...' icon, the idea was to show it on hover only and probably in a way that it covers the text behind it. I feel like it would be a waste of space to permanently reserve that area just for the icon. Re alignment, I think both variants are valid choices (and are used in apps), align to first line or center vertically, for some reason I chose to align the icon to the first line in this case, maybe because vertically centered can look odd when there is only a single line. I’ll recheck during implementation.

**Comment by flachware** [comment]
@tnajdek I prepared the note list on desktops. I would need your help here with some issues:
- I added the dropdown to the individual notes, that broke the functionality – sorry for that. Currently all dropdown menus will open at the same time (and the actions do not work anymore).
- Then there is the question which element will get the focus in the tab cycle, `.panel`? This is relevant for the focus styles.
- Keyboard navigation: whichever element will get the focus, once you hit the down arrow key you would be able to move the selection in the note list, right? In keyboard mode I would show the options icon for selected notes – I guess it would be most intuitive if the right key selected the dropdown toggle?

**Comment by flachware** [comment]
@tnajdek we have an `editing` state for the `metadata-list` currently. But 'edit mode' should actually transform all tab panes on touch devices. Would it make sense to have one edit mode for the entire panel (`.panel.editing`) instead of multiple edit modes/classes for each tab pane (or list inside)?

And could you conditionally insert the dropdown menu and the toolbar only in edit mode on touch devices?

**Comment by tnajdek** [comment]
> @tnajdek we have an editing state for the metadata-list currently. But 'edit mode' should actually transform all tab panes on touch devices. Would it make sense to have one edit mode for the entire panel (.panel.editing) instead of multiple edit modes/classes for each tab pane (or list inside)?

You're correct, I've changed it so it's as you've described and consequently I've broken the layout in edit mode on touch devices.

**Comment by flachware** [comment]
@tnajdek alight, the metadata-list layout should look alright again in edit mode – please let me know in case you still spot regressions.

**Comment by flachware** [comment]
@tnajdek I commented out L107–119 in notes.jsx – could you show the button (L100–105) on touch devices and the toolbar (L107–119) otherwise?

On touch devices the selected notes should open in a dedicated modal, could you create that modal? I think I would go with default/edit mode in the modal for now.

**Comment by flachware** [comment]
@tnajdek I’d like to rethink the notes layout. The modal approach doesn’t make a lot of sense to me anymore, I think we should add another level to the item-details. I feel like there is no point in putting a note in a modal, just for viewing or even editing, as we have enough space to do that directly in the interface and all the more as it goes well with the hierarchy.

Re the touch-header, I think this could work out: item-details touch header as it is; when you pick a note, 'All Items' translates out of view, 'current' is blank, 'Note' translates from 'next' to 'current'; I’d like to avoid having item titles in the touch header for now as they are very long (and the title is the first heading in item-details anyway). '< Notes' isn’t really correct either. So, just using the chevron (we would have to make it a clickable button) and 'Note' looks promising to me.

Sorry for this change request, but on larger touch devices the modal approach doesn’t seem right, to me it looks like we simply need one more level in our stacks on touch devices. (I think I can make the two toolbars fit into the available space.)

Does that make sense to you?

<img width="768" alt="note-1 3-1@2x" src="https://user-images.githubusercontent.com/419747/60820142-2095b700-a1a1-11e9-840c-b41e69af7842.png">
<img width="768" alt="note-1 3-2@2x" src="https://user-images.githubusercontent.com/419747/60820146-225f7a80-a1a1-11e9-9ccc-2a7626cd9631.png">
<img width="768" alt="note-1 3-3@2x" src="https://user-images.githubusercontent.com/419747/60820150-24c1d480-a1a1-11e9-9eb6-0d60df0b605f.png">

**Comment by flachware** [comment]
@tnajdek I prepared a container for the rich editor on touch devices. the container slides in when `.view-note-active` is set on `.library-container`. I believe things get easier if we set this class additionally and not mutex to `.view-item-details-active` etc.

Could you add the editor to this container so I can start tweaking the toolbars?

**Comment by tnajdek** [comment]
@flachware this isn't a trivial change, so we need to figure out how to best approach it. Most importantly: do you think this should become part of the url? i.e. when you navigate into a note, should the url change to reflect that (and also include note id)?

In current version opening note-editor modal is not reflected in the url (none of the modals are). However with this change we may want to keep track of the change in the url. If we don't, it might feel weird at times, e.g. when you hit browser refresh on mobile, you'll end up in details view instead of notes.

**Comment by flachware** [comment]
@tnajdek I agree that we should think this through carefully. Well, I think the note view does not need to be part of the URL. Like, in the desktop version when you view a note in the notes tab and hit reload you will be back on the info tab too. I feel like reloading while reading/editing a note is not a regular use case (and by going back to the item details you are not completely out of context) and we can stick to the desktop behavior.

**Comment by tnajdek** [comment]
@flachware it's a tricky case, the main reason I thought it should be tracked in the url is because otherwise we break the back button on mobiles - browser's "back" will take you straight to item list and not item details as one could expect. Is that acceptable?

**Comment by flachware** [comment]
@tnajdek I agree that reflecting the note in the URL would be preferable with regards to the back button. But on phones it would be an issue with both approaches, modal and new level. On phones a modal would slide in from bottom and the level from right, using the back button would bring you back to the item list. So, the URL handling seems to be a question on its own.

So I guess yes, the ideal solution would be having URLs for notes and using the new container for the editor on touch devices.

**Comment by flachware** [comment]
@tnajdek I think the `loading` class is not set on `.tab-pane.notes` for standalone notes, could you look into this?

**Comment by flachware** [comment]
@tnajdek could we autoselect new notes in the note-list and focus the editor (on desktops)? And could we automatically delete unselected notes without any content?

**Comment by flachware** [comment]
@tnajdek latest changes to notes look good to me.

But I realized that not showing the editor is questionable: when you have a lot of notes and select one of the last notes the editor will pop up and hide the selected note in the list. I think the easiest way around this would be to permanently show the editor.

Once we show the editor permanently I think it would make sense to allow creation of new notes by simply starting to type in the editor.

**Comment by tnajdek** [comment]
@flachware  I've came up with an alternative solution for now: if selected note would disappear from the viewport within scroll container, it is scrolled into view. This also helps with a scenario where user changes the first line of the not, causing it to appear elsewhere in the list of notes (because of alphabetical sorting).

We can consider changing the layout post 1.0.

**Comment by flachware** [comment]
@tnajdek I think that should work for now, but it strikes me that the note list does not fully scroll to the top. So when a note jumps to the first position due to a text change, the note list scrolls up, but the first line of the first note is not visible for me.

To fully scroll up, the list would need to scroll further by 31px (I guess it’s no coincidence that the tab navigation is 31px high). The list is also not fully scrolling down when a note jumps to the end, but it’s less noticeable here, it’s only 11px off (I don’t know where this could come from).

**Comment by tnajdek** [comment]
Thanks! Should be fixed now
