### ISSUE TITLE
Add item by identifier

### ISSUE THREAD

**Issue by fcheslack** [zotero/web-library#22]
This will require access to a running translation server, but other than that it should be straightforward. Direct requests to a translation server probably belongs in libZotero. Other than that this is just a bit of UI and glue.

**Comment by dstillman** [comment]
This is just the same as https://www.zotero.org/save, so we can do this with just a button in the toolbar and a popup panel for the identifier/URL. For an initial implementation, this can just add directly to the library, selected, the same as in the client, without the sort of confirmation that we have on /save or ZoteroBib.

**Comment by flachware** [comment]
@tnajdek I agree with @dstillman, this should just be a simple popup without preview. Could we use a reactstrap popover on desktops and keep the modal for touch devices? In the popover there would only be an input element, like in the client.

**Comment by flachware** [comment]
@tnajdek the popover looks good to me now. There seems to be an issue though: when an identifier cannot be found, then the input gets stuck in busy mode and stays there, even when you close and reopen the popover. In the client the popover is being closed and the input gets cleared. We could either do that or just clear the input but keep the popover open – that might be even more useful?

Re error messages: currently I get two error messages, 'Unexpected error' and 'No identifiers found'. Would it be possible to just show the latter message? And, we already talked about this at one point, I think we should have different kinds of notifications. 'Error' doesn’t seem appropriate here, even when you enter a valid ISBN it could be that this book is just in no database, so no search results should be rather a warning (like in the client) or even an info message (like in ZoteroBib).

**Comment by flachware** [comment]
@tnajdek looks good to me – I renamed 'errors' to 'messages' in SCSS, you might want to do the same in JS on your side for the sake of consistency.
