### ISSUE TITLE
Double scrollbar in collections tree (desktop + mouse only)

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#221]
@flachware I've noticed this today, I suspect it's caused by scope issues, most likely introduced in b12ae36

<img width="513" alt="Screenshot 2019-05-14 at 21 53 18" src="https://user-images.githubusercontent.com/214628/57731642-0654c680-7693-11e9-845d-c47d01629145.png">

**Comment by flachware** [comment]
Thanks for spotting, fixed with 2d0b495.
