### ISSUE TITLE
Duplicate Item shouldn't be a toolbar button

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#222]
Duplicate Item is a rarely used action that shouldn't be anywhere near as prominent as it is now. Wasn't there talk of having a "…" button with more options?

**Comment by flachware** [comment]
I believe we moved it out of '...' because it was a single item menu so far.

**Comment by dstillman** [comment]
Yeah, I think it'd be better to keep it in a menu, even if it was the only thing there so far. It really doesn't make sense as a toolbar button.

**Comment by flachware** [comment]
@tnajdek could you bring back the '...' dropdown menu with the duplicate option on desktops (in a tool group at the end)?
