### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#231]
On the homepage we have the following nav items:

- My Library
- Groups
- Documentation
- Forums
- Get Involved
- Log In / Username (dropdown)
- Upgrade Storage (button)

Which ones do we need/want in the web-library?

**Comment by flachware** [comment]
@dstillman @tnajdek here is my first stab at the header (large desktop, small desktop, tablet, phone): so one question would be how to handle small desktops. On the one hand it might be fine to collapse the menu items into the hamburger icon in this size. On the other hand we could reduce the search input to a search icon that transitions to a search input on focus and hide the menu items while searching (we would probably have to show an x icon in this case to cancel searching, which is not in the draft). Another simple option would be to drop some menu items in the web-library – if that’s an option I would be fine with that too. 

There is an astonishing number of websites that does not indicate the selected menu item, but I’d rather opt to indicate the selected item with blue color and indicate the user dropdown with a little caret (I would update the homepage header accordingly).

<img width="1440" alt="header-1 0@2x" src="https://user-images.githubusercontent.com/419747/59056882-6f49eb80-8899-11e9-90ee-ae0ffde2d1ed.png">

Variant small desktops:

<img width="1440" alt="variant@2x" src="https://user-images.githubusercontent.com/419747/59056903-7bce4400-8899-11e9-9213-b99cd4b1a5fa.png">

**Comment by dstillman** [comment]
Late on this, and not the main question, but it actually strikes me as somewhat odd to show this in the website header rather than as part of the web library. This isn't searching the website, and it's not even actually searching your library — it's specifically a filter of the current items list, which is why we put it in the middle toolbar in the client.

**Comment by dstillman** [comment]
This is obviously somewhat borrowed from the current version, where the search box is context sensitive — and, e.g., becomes a documentation search when you're in the documentation section — but this seems even more detached from the items list. I guess I'd want to see it in context, but are we sure we don't just want to put it in the middle pane toolbar on desktop?

**Comment by flachware** [comment]
Briefly speaking, I would be fine with the search box in the toolbar.

But what about the documenation section then (and other searchable areas), where would the search box be there? And what about phones, would we keep the loupe icon in the navbar although the search box is in a different place on larger devices?

**Comment by tnajdek** [comment]
Another issue to consider is the fact that on touch devices we don't have the toolbar where search input could go. I don't think we want to use the two-step search here like we do on mobiles so search input would still need be placed in the header unless we can come up with an alternative layout.

**Comment by flachware** [comment]
I have been thinking about the small desktops issue and concluded that having a search icon instead of a search box causes a lot of questions / usability issues / effort. So I would go with the search box and a hamburger icon in this size. There is one thing I have to change – but I guess this should be changed on the entire website anyway – the mobile nav currently fills the entire screen except for a narrow column with the slided out interface. I will tweak that in a way the mobile nav will never take more space than it actually needs, there is no point in a full screen nav, let’s restrict it to a sidebar on the right side that can be toggled with the hamburger icon:


<img width="992" alt="header-1 1@2x" src="https://user-images.githubusercontent.com/419747/60099715-83765f80-9758-11e9-9072-a29a5d2fac0e.png">

**Comment by flachware** [comment]
@tnajdek could you replace the 'User Name' dummy in the navbar with a real dropdown?

The dropdown menu would have the same items as the one on the homepage:

My Profile
—
Inbox
—
Settings
Log Out

**Comment by flachware** [comment]
@tnajdek there is a little glitch I think we should take care of: when you open the sidebar nav in a small viewport and then enlarge the viewport, the nav-cover will still be present.

My suggestion would be to set the .no-transitions class, remove .navbar-nav-opened, then remove .no-transitions when the viewport is resized to lg size.

I have been wondering if this couldn’t be achieved in an easier way, like simply hiding the nav-cover on large screens, but as long as the .navbar-nav-opened class is set, the slide out transitions will be fired once you resize the window down again.

**Comment by tnajdek** [comment]
> when you open the sidebar nav in a small viewport and then enlarge the viewport, the nav-cover will still be present.

@flachware I've decided to close the navbar instead, it's much simpler and I don't see a reason why it should persist across device size/orientations. I think realistically you will only see this when rotating an iPad Pro.

**Comment by flachware** [comment]
@tnajdek that’s actually what I wanted to achieve – but I was wrong about the need of the .no-transitions class, we don’t need that as the transitions are just defined for smaller screens anyway.

We could even get rid of the nav-cover fade out when switching to a lg screen, but I guess there is nothing wrong about the fade out here.

**Comment by flachware** [comment]
@tnajdek the dropdown menu in the navbar seems laggy for some reason, is this a known issue?

**Comment by flachware** [comment]
@tnajdek on the website we use Boostrap instead of reactstrap for the dropdown menu, which allows selecting the first menu item with the arrow down key after you clicked the dropdown-toggle. I believe reactstrap dropdowns don’t work that way and it’s not a big deal as you can tab to the menu, but I have been wondering if there was an easy way to achieve that behavior.

**Comment by flachware** [comment]
@tnajdek now we’ve got two main navs. Any chance to get the links, the search box, and the Upgrade Storage button into one nav (otherwise landmark navigation would suffer)?

**Comment by tnajdek** [comment]
@flachware I've reorganized nav to match how I believe it was originally designed, could you please have a look if it's ok now?

If everything is as expected, can we close this issue?

**Comment by flachware** [comment]
@tnajdek looks good to me now.

After realizing that the search box should not be part of the navigation, honestly, I don’t know what the correct approach is here. Having just one navigation seems good to me somehow, but that might make it easy to miss the (important) Upgrade Storage button on screen readers. Having a second singleton nav doesn’t help much here I guess (basically what you had, a valid approach). Alternatively we could hide the 'button' with `aria-hidden` from screen readers and add an `.offscreen` menu item with the upgrade storage link to the main nav, so you couldn’t miss it when you step through the entire navigation.

Apart from that I realized that we have a 'Zotero' link in the mobile nav on the website, I’m inclined to say that can remove that one in favor of the Zotero brand link?

Other than that we can close this issue.

**Comment by flachware** [comment]
@tnajdek ok the aria-hidden + offscreen thing doesn’t work out. We cannot differentiate between a screen reader and keyboard navigation, so the 'invisible' link would always be in the way. And VoiceOver seems to ignore aria-hidden. So I guess we should revert 39a4ce6.

**Comment by flachware** [comment]
@tnajdek I see you fixed my latest request in 347e7f4 in a much better way, excellent.
