### ISSUE TITLE
Allow uploading files as top-level items

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#235]
Allow dragging file onto items table to create top-level attachment item. Probably also a dedicated modal for this feature to help with discovery and also support this on touch devices.

**Comment by flachware** [comment]
In addition to drag and drop I think we should also add the 'Link to File…' and 'Store Copy of File…' entries to the 'New Item' dropdown like in the client.

**Comment by tnajdek** [comment]
@flachware "link" and "search and replace" will not work on some devices. This apparently done "[by design](https://www.tiny.cloud/docs/mobile/#configuringtheplugins)" in tinymce... 

Since we're not using their "mobile" theme, we could modify tinymce to always assume desktop, but that probably means we will need to restyle modals they produce. It also adds maintenance as we will need to do this anytime there is an update.

Thus I think we could just hide this functionality on touch/small devices?

**Comment by tnajdek** [comment]
'Link to File…' does not apply here, it only works in client where it points at a file (usually in the local file system) without storing it anywhere else.

I've added 'Store Copy of File' which we might need to reword as in this context it's more like 'Upload File'.

**Comment by flachware** [comment]
I agree that 'Upload File' would be very intuitive and would not leave any questions, but I think it might be worth a thought to keep the exact wording of the client, otherwise users that switch between the client and the web-library might start wondering 'what’s actually the difference between Upload File and Store Copy of File?'.

**Comment by flachware** [comment]
@tnajdek could you also set the `.dnd-target` class on `.items-table-wrap` whenever `.dnd-target-top` or `.dnd-target-bottom` is set on an item?
