### ISSUE TITLE
Attachments pane (desktops)

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#248]
- [x] Use specific attachment icons
- [x] Revisit standalone 'Store Copy of File' (see #235)

**Comment by flachware** [comment]
@tnajdek could we streamline the process of uploading files a bit? Currently you have to click the plus icon which creates the file input, then you click that input, then you choose a file in the OS dialog, then you click the upload button.

Ideally, I think we could use one of these CSS hacks where the file input lies invisibly on top of a regular button (the plus button), which triggers the OS dialog and I believe there are also ways to immediately upload the file you have chosen in the OS file dialog?

**Comment by flachware** [comment]
And three more questions:

Which icons can we have there in the list, would it have to be a generic 'attachment' icon or could we differentiate e.g. between 'pdf' and 'document'?

What should happen when I click on an attachment (currently I see a 'Not found' view)?

I know there is #152, but what about the file name for now? Should we use an editable to allow renaming plus an icon to view the file?

**Comment by tnajdek** [comment]
> Which icons can we have there in the list, would it have to be a generic 'attachment' icon or could we differentiate e.g. between 'pdf' and 'document'?

Yes, we know the content type of a file and should be able to display a relevant icon

> What should happen when I click on an attachment (currently I see a 'Not found' view)?

This currently only works when using dev api because of changes done for #95. Basically it behaves exactly as clicking on a link to a file, so it will either preview image/pdf in a browser or show download dialog for other file types.

> @tnajdek could we streamline the process of uploading files a bit? Currently you have to click the plus icon which creates the file input, then you click that input, then you choose a file in the OS dialog, then you click the upload button.

> Ideally, I think we could use one of these CSS hacks where the file input lies invisibly on top of a regular button (the plus button), which triggers the OS dialog and I believe there are also ways to immediately upload the file you have chosen in the OS file dialog?

Yes we should make this nicer. We can do the css trick, we can support drag and drop and we can display details of a selected file but I'm not sure if we should upload immediately? Also have a look at "Store Copy of File" dialog (#235) which shares some of this functionality.

**Comment by flachware** [comment]
>Yes, we know the content type of a file and should be able to display a relevant icon

Ok, what content types do we have? PDF, document, … what about 'Link to URI'?

>Yes we should make this nicer. We can do the css trick, we can support drag and drop and we can display details of a selected file but I'm not sure if we should upload immediately? Also have a look at "Store Copy of File" dialog (#235) which shares some of this functionality.

Ok, let’s do the CSS trick then. Regarding the upload, as we are now more and more leaning towards the client’s behavior (e.g. right click) I don’t see why we shouldn’t upload immediately. It’s not that you publish something that is out of your control then, so if you happen to upload something wrong, you can still correct that afterwards.

I’m aware of the 'Store Copy of File' dialog but see it in a similar way: choosing 'Store Copy of File' could immediately open the OS dialog and then upload immediately. As for the drag and drop, couldn’t we have different drop zones that are available all the time? Like dragging a file from outside the browser on a collection in the sidebar adds it to that collection; dragging onto the items table adds it to the currently selected collection; dragging onto the attachment pane adds it to the selected item?

**Comment by tnajdek** [comment]
`Ok, what content types do we have? PDF, document, … what about 'Link to URI'?`

I think we need the following 6 types:

* PDF + Linked variant
* Fallback document + Linked variant
* Snapshot
* Linked URL

I've attached various examples to "_Has Attachments" item in the test library. For comparison here is how it looks in the client:

<img width="669" alt="Screenshot 2019-08-26 at 13 25 43" src="https://user-images.githubusercontent.com/214628/63690659-2bfe7980-c805-11e9-891b-543dfbab376f.png">

**Comment by flachware** [comment]
@tnajdek now we have
- `icon-pdf` + `icon-pdf-linked`
- `icon-document` + `icon-document-linked`
- `icon-web-page-snapshot`
- `icon-web-page-linked`

so I think we should be able to display all different kinds of attachments.

**Comment by flachware** [comment]
@tnajdek I believe adding a new tag used to work a bit different – could you not render the 'remove' button for new/virtual items?

**Comment by flachware** [comment]
@tnajdek in the test library we have a standalone web page snapshot (latin9.pdf). Can there ever be a standalone web page snapshot? That specific PDF would result in a Journal Article with attached web page snapshot in the client.

**Comment by dstillman** [comment]
You can definitely have a standalone PDF, if that's what you're asking. (Just turn off automatic PDF metadata retrieval in the prefs, or try a non-academic PDF.)

In ancient times it used to be possible to create a standalone HTML snapshot, but that hasn't been possible in many years, and even if a few people still have those in their libraries we don't really need to worry about them.

**Comment by flachware** [comment]
Yes I’m aware of standalone PDFs, I was wondering about standalone HTML snapshots. So I guess it’s good that we can display those ancient standalone snapshots.

But as this URL https://www.cs.tut.fi/~jkorpela/latin9.pdf results in a Journal Article with attached snapshot (when you save it via connector in the client) I’m still wondering if everyting works as expected in the web-library? Also, when I try to add this PDF via the 'Add Item by Identifier' feature in the web-library I get this error currently: `Invalid response from translation-server: The remote document is not in a supported format`

**Comment by tnajdek** [comment]
That file, which IIRC was made artificially via API for testing, has `"linkMode": "imported_url"` and `"contentType": "application/pdf"`.

Web-library currently displays this as a snapshot (because it's `imported_url`), from what I gather in the client `contentType` [takes priority](https://github.com/zotero/zotero/blob/26ee0e294b604ed9ea473c76bb072715c318eac2/chrome/content/zotero/xpcom/data/item.js#L3697) so a pdf icon is displayed.

We should probably tweak web-library to match client's behaviour for consistency.

**Comment by tnajdek** [comment]
@flachware can we close this issue?

**Comment by flachware** [comment]
@tnajdek yes the attachments pane looks good to me.
