### ISSUE TITLE
User dropdown causes library to refresh

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#251]
Easiest solution would be for it to become a `button` instead of a link.

**Comment by flachware** [comment]
@tnajdek I can’t reproduce the issue, but we are using a button on zotero.org and it makes more sense here anyway, so I’ll replace the link with a button.

**Comment by tnajdek** [comment]
@flachware actually I've replaced that already just needs styling fix :)

**Comment by flachware** [comment]
@tnajdek this should be fixed.
