### ISSUE TITLE
Selected item in the items list/table is not always scrolled into view

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#253]
Currently items are only scrolled into view if already fetched for given data set. If item is not yet known locally, it cannot be scrolled into view because its position is unknown

There is currently no option to ask API where given item would appear in a given data set

The only solution I can think of right now is to try and fetch pages of the data set until target element is found so that it's possible to scroll it into view.

Any suggestions appreciated.

Related: #193

**Comment by dstillman** [comment]
This makes providing an online library link, as we're doing in https://github.com/zotero/zotero/pull/2893, a bit awkward. We show the item in the right-hand pane, but the items list just stays at the top.

It's not super optimal, but couldn't you make an identical `format=keys` request to get the sorted position of the key in question? That actually doesn't even have a maximum `limit` (for better or worse — we probably haven't tested that with a 300K-item library).

**Comment by tnajdek** [comment]
Thanks for the suggestion, this approach seems to work very well.
