### ISSUE TITLE
Standalone notes

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#254]
I think we need a way to add standalone notes in the web-library too?

**Comment by tnajdek** [comment]
That's already possible: 

new item (leftmost "+" icon on desktop) -> more -> note

**Comment by flachware** [comment]
Ah, could we put that option before 'Store Copy of File' in the menu (with dividers on top/bottom)?

**Comment by flachware** [comment]
Ok, one more request: could we have the same label text ('New Standalone Note') like in the client?

**Comment by dstillman** [comment]
Is this not getting a toolbar button, as in the client? People generally shouldn't need to use the New Item menu, because they'll (hopefully) save things other ways, but people who use standalone notes might do so regularly. In the client it's a contextual button that also allows creating a child note (which is likely more common than standalone notes).

**Comment by flachware** [comment]
Well that relates to this topic https://basecamp.com/2673480/projects/12077128/todos/361101343 and also to #22.

I still think all stuff that you can add to your library should go into one menu. I also think the magic wand icon is not self-explanatory (I admit that i can’t think of a better one) so having 'Add item(s) by identifier' in a menu might be easier to understand anyway.

**Comment by dstillman** [comment]
I don't think we need to overthink this. If something is frequently used, it should be available via a toolbar button. That's how pretty much every program works. A mostly empty toolbar doesn't do anybody any good. There's no way that Add Item by Identifier would ever not be a toolbar button — if you're using the web library at all, that's how you should be adding most things. (Same in the client if you're not using the connector.)

Conversely, functions that people almost never use, such as manual regular item creation or "Duplicate Item", should be in submenus and/or context menus.

**Comment by dstillman** [comment]
Really, in the name of finishing this thing, we should just follow the client except where there's a strong, probably technical reason for not doing so. We don't need to reinvent the wheel here. Generally speaking, the client reflects what's appropriate for active usage of Zotero. We can make further refinements later, but we need to get this out.

**Comment by tnajdek** [comment]
On small/touch this is currently:

"..." -> New Item -> Note

Should we add "New Standalone Note" directly under "..." menu?

**Comment by dstillman** [comment]
Yeah, I guess so. A little weirder in that case, since a note is still an item, but it's the closest parallel.

**Comment by flachware** [comment]
Looks good to me.
