### ISSUE TITLE
Feedback when loading collections on touch

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#262]
When user selects a library (group or his own) it might need to load collections inside that library. On desktop we show a spinner next to library name, then open a tree, that works well.

On touch, up until #260, we would show empty tree (with "Items" node) and let collections appear when fetched. While doing #260 I opted not to re-implement that behaviour so currently it appears slightly broken. @flachware what would you suggest as correct behaviour here? My thoughts:

1. Animate in next level with only a large spinner visible while fetching collections (I believe we discussed this previously as preferred way but then didn't implement it? It might have been for some technical difficulties)
2. Show spinner next to library name, then animate-in collection tree (similar to desktop)
3. Re-implement old behaviour though I think that's not ideal.

I believe we've previously touched upon this in https://github.com/zotero/web-library/issues/147#issuecomment-437159830

**Comment by flachware** [comment]
I think 1. would be the preferable way.
