### ISSUE TITLE
Note saving breaks after note sync conflict

### ISSUE THREAD

**Issue by mrtcode** [zotero/web-library#267]
After getting that error about note conflict you can still write in the note but nothing is saved, which means you might lose your writing.

**Comment by tnajdek** [comment]
Thanks @mrtcode , I've attempted to replicate this but for me note editor disappears after error. Do you remember what browser/resolution/device it happened on? 

![267-note-saving-replicate-attempt mov](https://user-images.githubusercontent.com/214628/65450345-311f0a80-de3d-11e9-94e6-af2b16b7c4c6.gif)

**Comment by mrtcode** [comment]
Well, actually it's a strange anomaly. Chrome (76.0.3809.132) is randomly queuing the request for unknown reason. In the screenshot below it's 44s. It might be related with the previous 412 error response.

![](https://s3.amazonaws.com/upldat/web-library-request-queueing.png)

Anyway, I think we can ignore this for now.

**Comment by tnajdek** [comment]
Lately I've seen API requests (very) occasionally hanging for 40+ seconds, I suspect this might have been one of these? It probably makes sense to implement timeout for fetch (via the new abort feature which is now quite well supported).

Anyway thanks for looking into this!
