### ISSUE TITLE
Open "best" attachment if item is double clicked in the table

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#268]
First click will always select item if it's not selected yet. Second click will open "best" attachment for given item.

This depends on zotero/dataserver/issues/87

Most likely there will be a minimal delay before the attachment is actually opened because a time-limited, pre-authorised url for the attachment needs to be fetched from the api.

**Comment by fcheslack** [comment]
Reopening as this stopped working at some point.

**Comment by tnajdek** [comment]
Thanks for spotting this regression, should be fixed now.
