### ISSUE TITLE
Add Note/Tag/Attachment should appear at top of pane

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#276]
Currently, if you click on the Notes/Tags/Attachments pane on items without those things, the pane looks broken, since nothing appears, and it's very easy to miss the Add button at the bottom. Those should move to the top of the panes, as in the client.

**Comment by flachware** [comment]
I beg to differ. The pane does not look broken but empty. We can add a placeholder text to overcome this (as we already do when no item is selected) and make the button stand out more. It is a common and useful pattern to move functionality to the bottom when the header is 'occupied'. The Add button in the client does not work for me, it conflicts with the tabs and its position between tabs and lists seems to be out of place.  

<img width="360" alt="empty-tab-pane@2x" src="https://user-images.githubusercontent.com/419747/67091996-6b669800-f1ae-11e9-81d4-8447c0b90f44.png">

**Comment by dstillman** [comment]
It doesn't make sense to put an add button way at the bottom of a pane that's almost never going to be filled, far away from the tab bar you clicked to take you there and that you need to take you back to the Info pane. It's just an objectively slower layout, moving the button that you're almost always going to need to click next way out of the way for no good reason.

The vertical alignment of the button in the client is slightly off, but it forms a row with the count header. I think we could drop the colon and make the button feel even more like part of that row. But most importantly, it's right next to the tab, making it very quick to move between tags and add new things. We shouldn't do away with that.

![add](https://user-images.githubusercontent.com/783082/67113638-060fa880-f1a8-11e9-802c-3ace08053d9d.png)

> It is a common and useful pattern to move functionality to the bottom when the header is 'occupied'.

FWIW, 1Password puts the + button to add new entries at the bottom, and it's bothered me for years. I find it annoying — and have to remember where the far-out-of-the-way button is — every single time I go to add something.

**Comment by dstillman** [comment]
> Do you want the Add button to scroll away with the pane content like in the client?

Hmm, good question. I think it mostly doesn't matter — it's very rare to fill the available space with any of these objects, and for the one that's most likely, tags, you can just keep hitting Enter once you're already in the text field even if the Add button is out of frame. But no, the header should probably be fixed, with the scrollbox below it. I can make that change in the client.

**Comment by flachware** [comment]
@tnajdek I moved the Add buttons to the top of the pane in branch `issue/276` – could you hook up the counters?

And could you make `device.isTouchOrSmall` available in `item-details/tags.jsx` and `item-details/attachments.jsx`, like we have it in `item-details/notes.jsx`? Once the device object is availabe I think I find my way around to fix the layout for touch devices.

**Comment by tnajdek** [comment]
> For some reason the 'Add Tag' button always shows up, although it should just show up in edit mode on touch devices

My bad, should be fixed now. Also I've merged `issue/276` into master.

> Fyi I’ve changed the Add File Attachment button, it can now be reached and triggered via keyboard. Please check if that breaks anything on your side.

I'm not sure what is the correct approach here. We have inconsistent behavior in item details pane: most tabs are "like forms" except for attachments. Attachments pane seems to be more in line with the rest of the UI though (it uses arrows for navigation instead of tab).

If we decide we want to stay with arrows, then "add attachment file" should probably be an arrow-stop, not extra tab-stop. Or we can convert it to be in line with other tabs and then the button and each attachment would be a tab-stop.

Any thoughts on that?

**Comment by flachware** [comment]
My change to the btn-file really just covered the input element inside to be focusable at all.

I think keyboard navigation is a tricky thing and we should approach it systematically. If that’s fine with you I’ll open a 'master issue' to keep track of the overall progress and individual keyboard navigation issues.

But up front my logic would be:
- Use tab to switch between components
- Keep the number of tab stops as small as possible
- Use arrow keys to initiate (if necessary) and perform navigation within components
- Use tab to navigate between form elements within a component

So in the case of attachments:
- Use right key to navigate to the Attachments tab
- Hit enter to select the Attachments tab
- Hit arrow down to focus the Add File Attachment button
- Hit arrow down to focus the first attachment in the list (and probably auto select to show its metadata and note)

**Comment by tnajdek** [comment]
@flachware I think we're actually handling keyboard quite well on desktop version everywhere except item details pane. There was quite a lot of work in that area in #218 and I think we have came up with basic principles similar to one you've described above. Please feel free to open an issue to keep track of places where keyboard support is lacking.

> Hit arrow down to focus the first attachment in the list (and probably auto select to show its metadata and note)

Not sure about auto select, but whether we have it or not, it should probably work the same with notes.

**Comment by flachware** [comment]
@tnajdek yes I’m aware of the work we have already done and I won’t cover UI elements that already work well. But changing the behaviour of the keyboard navigation in the item table was kind of a paradigm shift, so I think it’s worth revisiting the interface.

I think this is good to close/merge?
