### ISSUE TITLE
Ongoing

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#281]
@tnajdek would you mind if we moved the Ongoing component to the bottom of the sidebar?

**Comment by tnajdek** [comment]
@flachware sure, no problem.

**Comment by flachware** [comment]
@tnajdek could you pluralize 'Uploading 1 file' / 'Uploading n files' in the message?

**Comment by flachware** [comment]
Regarding your thoughts: yes the sidebar is more busy, but the item details pane belongs to a specific item most of the time, whereas the ongoing pane shows all kinds of processes (like importing a PDF as an item), that’s why I think the sidebar is a better place for it. And yes we can end up with two spinners, but the ongoing pane is a pretty temporary element generally and at some point we might show multiple processes individually anyway (each with a spinner).

**Comment by tnajdek** [comment]
Much nicer with animation :)

**Comment by flachware** [comment]
Well the idea is that the movement catches your attention. Once we show multiple processes in parallel we will need to adapt the height of the ongoing-pane accordingly, e.g. by setting a CSS variable with the number of processes on it, then I can calculate the height in CSS for the transitions.
