### ISSUE TITLE
Errors with creating collections

### ISSUE THREAD

**Issue by fcheslack** [zotero/web-library#286]
A couple of different errors, both related to creating new collections in different states.

1. Click the "+" to create a collection.
2. Without entering a title, click away to another part of the interface.

There is an error and the empty collection with loader remains.

1. Have the collections for both "My Library" and a group library open.
2. Click the "+" to create a collection.

There is an error and new collection inputs with loaders appear under both libraries without focus.

Interestingly these inputs do still work if you re-focus them and put in your title (though when there are multiple it generates another error from the one that doesn't get used).

**Comment by tnajdek** [comment]
Thanks, should be now fixed.
