### ISSUE TITLE
PDF icon doesn't include chain for linked URL

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#288]
A linked_url PDF attachment shows a PDF icon in the Attachments tab, but the icon doesn't include a chain, so it's not clear it will take you off the site (unless you look for the URL at the bottom of the page).

**Comment by tnajdek** [comment]
I've tweaked it to display pdf with chain icon.

Interestingly this differs from what client does, where a generic document with chain icon is used. Should we match that in web-library?

![Screenshot 2019-11-21 at 20 10 23](https://user-images.githubusercontent.com/214628/69368961-67410500-0c9b-11ea-9f5a-f8c841eef5a7.png)
<img width="327" alt="Screenshot 2019-11-21 at 20 10 18" src="https://user-images.githubusercontent.com/214628/69368962-67410500-0c9b-11ea-8a15-e5822199bb58.png">

**Comment by dstillman** [comment]
Ah, yes, sorry, it should use the generic linked_url icon. It's more important that it's an external URL than that it's a PDF, so it should be differentiated from linked-file PDFs (even if those don't make sense in the context of the web library anyway).
