### ISSUE TITLE
Allow viewing attachements meta & notes

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#298]
General idea is:

For child attachments, allow selecting an attachment to see meta and a note in rich editor.
For standalone attachments, add rich editor to display a note.
For touch & small we will probably need extra depth level, same as for notes.

**Comment by flachware** [comment]
@tnajdek re keyboard navigation in the attachments pane: I think it should be possible to move the selected state up and down with arrow keys, once the attachment-list has the focus. The buttons in each attachment list item would be focusable by using the right/left keys. I’m not entirely sure about that, but I guess that means that we want to focus the individual items (or their buttons) as opposed to setting the focus on the entire attachment-list (like in the item table).

Currently, when the attachment tab has the keyboard focus and you hit tab or arrow down the Add File Attachment button gets skipped. I think we should focus the button in this case and hitting tab or arrow down another time should focus and auto select the first attachment. (Unlike in the item table, where we skip the table header, we cannot assume that skipping the button is a wanted behavior in case you want to add new attachments to an item.)

In Tropy we have a very few steps in the tab cycle, so you can easily tab to the search field after the panels. For that reason we can’t use the tab key to move the focus into a panel. However, in the web-library the tab panes are a special case, it is the last tab stop in the app. So I think we can make use of the tab key more liberally – and let the user use tab OR key down to move the focus between the tab list and the attachment-list. In any case, I think Shift + Tab should move the focus from the attachment-list to the Add File Attachment button.

**Comment by flachware** [comment]
@tnajdek I’ve added an attachment-details container, which should show up whenever an item has attachments. While no attachment is selected it shows a placeholder, otherwise the placeholder has to be replaced by the metadata-list and the rich-editor (and the `.no-selection` class has to be removed in this state). 

This is similar to #271. The more I think about it the more sense it makes to me to split the pane even before an attachment has been selected.

**Comment by flachware** [comment]
This issue is related to #152.

**Comment by tnajdek** [comment]
@flachware "open link" button icon should really be a link because in some cases we actually use `href` attribute on it. I currently wrapped the entire button with an `<a>` tag which breaks the layout. Let me know whether you'd prefer fixing it in styles or merging `<Button>` and `<a>` into a single element.

**Comment by flachware** [comment]
@tnajdek yes like I said the other day, we can just set the btn classes on the anchor element – these classes are element agnostic.

**Comment by flachware** [comment]
@tnajdek attachments pane looks good so far. I noticed that you have to click on the `.truncate` element to select an attachment – I think we should make `li.attachment` itself clickable so you can click wherever you want.

**Comment by tnajdek** [comment]
> I think we should focus the button in this case and hitting tab or arrow down another time should focus and auto select the first attachment

I'm not sure about that. Now that we include note editor, selecting an attachment comes with a heavy performance cost because of TinyMCE. Auto-selecting first attachment might make the experience sluggish. I'd prefer current implementation where attachment needs to be actively selected with "enter" key. It's also in line with how we do notes.

**Comment by tnajdek** [comment]
@flachware This looks great to me. Are we happy with close this (and include in next beta release)?

**Comment by flachware** [comment]
@tnajdek I’m sorry but I think navigating within lists in the item-details panes should be as comfortable as in the items-table for the user. I’d like to work all interactive lists like that basically. Of course, if we encounter performance issues we need to have a closer look, but from what I can see in the beta from loading TinyMCE for standalone notes it does not look slower than anything else. I didn’t find the time yet to tweak the keyboard navigation within the note list, it’s still in a work in progress state. Would you mind to give auto-selection on focus a try?

**Comment by tnajdek** [comment]
@flachware With a tweak to re-use RichEditor (711014b) performance might be acceptable. It seems to work ok, let me know if you can spot any problems here or anywhere else RichEditor is used.

**Comment by flachware** [comment]
@tnajdek looks good to me so far. There are some more issues I’d like to address/discuss:
- Item type icons of focused attachments have to switch to the white version
- When you click on the attachment tab and hit key down, the Add File Attachment button gets the focus as expected – but the attachment list is also scrolling a bit, which is unfortunate, as another key down will select the first attachment which is out of sight then. I’m wondering why the list is scrolling in this case (I think it has to do with the button being contained by the scroll-container, but still)? It doesn’t fix the issue for some reason, but I think we can set a negative tabindex on scrollable elements that contain focusable elements, as you can use the page up/down keys in this case.
- When using the up key to navigate to the top while the list is scrollable the selected attachment gets hidden by the toolbar. The toolbar is 42px high, is there a way to include the toolbar height in the select/scroll logic? To explain this a bit: the sticky toolbar is part of the scroll-container because the design tries to avoid another horizontal border between the toolbar and the list. When you use permanent scrollbars, the scrollbar goes all the way up to the border of the tabs, which means the toolbar ends with a border. If the toolbar was outside of the scroll-container, the scrollbar would just end without a distinct boundary, which looks odd.
- When one attachment is selected the behavior seems to be inconsistent: when I click on the Attachment tab and hit the tab key the focus either gets set on the button or the first attachment. Shouldn’t the tab/down always focus the button in this case?
- When the button has the focus and I hit tab I would expect the first attachment to get the focus if there is no selection, in case there is a selection I would expect the selected attachment to get the focus. As said before, I think as there are no further tab stops I think we can use the tab key to do that.

**Comment by flachware** [comment]
>Are we happy with close this (and include in next beta release)?

I think the feature is fully functional for mouse users, so I guess it’s better to have it in the beta than not to have it. But I’d keep the issue open until we have addressed the remaining tasks.

**Comment by tnajdek** [comment]
> When using the up key to navigate to the top while the list is scrollable the selected attachment gets hidden by the toolbar...

Scrolling behaviour is actually default browser behaviour, it isn't controlled by the JS. We could try to come up with a JS hack to work around this problem but I'd rather avoid it if possible.

> When one attachment is selected the behavior seems to be inconsistent: when I click on the Attachment tab and hit the tab key the focus either gets set on the button or the first attachment...

If you haven't interacted with the list yet, focus should always go to the button. However if you did, last-focused element is stored in focus manager (same as toolbar, tags selector, collections list etc.). This means that on later interaction focus will go to the last-focused item. Could that be the problem you've been seeing?

**Comment by flachware** [comment]
>Scrolling behaviour is actually default browser behaviour, it isn't controlled by the JS. We could try to come up with a JS hack to work around this problem but I'd rather avoid it if possible.

@tnajdek ok I concluded that I should rework the layout in a way that the toolbar is outside the scroll-container and eventually rework scrollbars generally. I think there are three available options for scrollbars: 1. overlay scrollbars in macOS – they work with the current layout and are the best option generally in terms of aesthetics. 2. permanent scrollbars – for those I’ll add a border between toolbar an attachment-list. 3. custom scrollbars in webkit browsers – support for custom scrollbars (purely done with CSS) is pretty good in webkit browsers, which is basically everything except Firefox nowadays. So we could consider having custom scrollbars like in Tropy (please have a look at them), they work fairly well. They look close to the kind of permanent scrollbar Apple uses in sidebars.

I think it was a good decision to go with custom scrollbars in Tropy, but it’s a desktop application, I’m a bit undecided when it comes to web applications. What do think about custom scrollbars in browsers?

**Comment by flachware** [comment]
>If you haven't interacted with the list yet, focus should always go to the button. However if you did, last-focused element is stored in focus manager (same as toolbar, tags selector, collections list etc.). This means that on later interaction focus will go to the last-focused item. Could that be the problem you've been seeing?

No what I see is that the first attachment in the list gets focused although a different one has been selected before – I would expect what you describe above.

**Comment by flachware** [comment]
@tnajdek I’m giving custom scrollbars for Webkit browsers with permanent scrollbars a try – please let me know what you think about it.

**Comment by tnajdek** [comment]
> @tnajdek I’m giving custom scrollbars for Webkit browsers with permanent scrollbars a try – please let me know what you think about it.

It definitely needs to work in Firefox so I'm not sure if that's an option? What would be the fallback for nonsupporting browsers?

> No what I see is that the first attachment in the list gets focused although a different one has been selected before – I would expect what you describe above.

Ok, I'll see if I can reproduce.

**Comment by flachware** [comment]
@tnajdek of course it has to work in Firefox, the fallback for all non-Webkit browsers (including Firefox) are the default scrollbars + additional borders where needed.

**Comment by flachware** [comment]
When I click on the `.scroll-container-mouse` element (either below the list or in the scrollbar) the first attachment gets focused and thus selected, is this intended behavior (possibly related to #335)?

**Comment by flachware** [comment]
Could we also switch back the item type icon to the regular version while one of the icon buttons within an attachment has the focus?

**Comment by tnajdek** [comment]
> When I click on the .scroll-container-mouse element (either below the list or in the scrollbar) the first attachment gets focused and thus selected, is this intended behavior.

While this is implicit behaviour (we handle focus on that element), I believe it is correct. It's identical to how items list behaves, both in web-library and the client.

**Comment by tnajdek** [comment]
> No what I see is that the first attachment in the list gets focused although a different one has been selected before – I would expect what you describe above.

I've made some tweaks, could you please re-test if you're still seeing this behaviour?

**Comment by flachware** [comment]
When I select an attachment other than the first one, switch to another tab and then back to the Attachments tab and then hit 2 x tab or key down the first attachment in the list gets focused – so I think I’m still seeing this behaviour.

**Comment by flachware** [comment]
I think the focus behaviour needs to be tested thoroughly (with and without overflow in the list), I’m seeing really inconsistent sequences. Like, sometimes the Add button is omitted in the tab cycle, sometimes the first attachments gets the focus although a different attachment has already been selected before (the case I describe above), but sometimes even an attachment before or after the one that has been selected gets focused.

**Comment by tnajdek** [comment]
@flachware I've hopefully fixed these issues. The logic currently is:

1. When you have attachment selected, when focus is brought onto attachments pane, selected attachment is focused. Exception: if you've previously moved focus onto the "Add File Attachment" button, and did not change attachment selection in the meantime, it will go back to that button because focus manager remembers your focus.
2. When you have NO attachment selected, when focus is brought onto attachments pane, "Add File Attachment" button is focused. When you press tab or an arrow down/up focus will move to the first/last (respectively) attachment and it will auto-select. 
3. While attachment pane has focus, pressing up/down arrows will iterate attachments (and auto-select them) AND "Add File Attachment" button. Pressing tab moves focus to the editor, pressing shift+tab moves focus back to the tabs strip. 

Let me know if you see anything different.

**Comment by flachware** [comment]
1. Looks good to me.
2. Looks good to me too. Although I’m wondering if we really want to 'loop' the focus/selection? This behaviour seems rather unusual to me, we don’t have it in other lists, nor does it the client, Finder, or native menus.
3. That works except the shift + tab case: when I select an attachment and then hit shift + tab, the scroll-container gets the focus. Hitting shift + tab again sets the focus back on the attachment. Hitting shift + tab again sets the focus on the scroll-container. Hitting shift + tab finally sets the focus on the tab-list. I set the focus styles for `li:focus` lacking better knowledge, if the logic would be easier using `.scroll-container-mouse:focus li.selected` I would be fine with that – I really just don’t know how the focus handling works internally.

Related to #328, I guess shift + tab should bring the focus back to the active Attachments tab?

**Comment by tnajdek** [comment]
@flachware I've tweaked focus manager logic and also disabled carousel.

Could you please retest 3? I can reproduce something similar but only in Firefox and only when div is overflowing and requires scrolling. This is tracked as #339.

**Comment by flachware** [comment]
@tnajdek shift + tab still sets the focus on `scroll-container-mouse` in Chrome. Shouldn’t we use that scroll container to manage the focus like you just did in the items-table (and as proposed above)?

**Comment by flachware** [comment]
@tnajdek shift + tab looks good to me now (except that the Info tab gets the focus instead of the Attachment tab – but I guess this is something that has to be handled in the tabs?). But the Add File Attachment button is skipped when hitting tab/arrow down when one of the tabs has the focus.

**Comment by flachware** [comment]
@tnajdek looks good to me, I think we can close this issue?

**Comment by flachware** [comment]
@tnajdek I think there is an issue: when I choose the _Has Attachments item and scroll to the last attachment and click on it, the first attachment gets selected. When I choose an attachment in the middle of the list, the first attachment gets selected for a moment and then the selection jumps to the correct attachment.

**Comment by tnajdek** [comment]
@flachware I can see this, I'll have a look (tracked in separate issue)
