### ISSUE TITLE
See what collections an item is in

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#299]
We could implement this feature in web-library (at least for desktops) exactly how it works in the client:

https://www.zotero.org/support/kb/collections_containing_an_item

* [x] Highlight collection an item is in
* [x] Expand all parents of any collection an item is in

**Comment by flachware** [comment]
@tnajdek I’ve added a block version to the folder icon. To highlight a collection simply pass `folder-block` as symbol to its icon.
