### ISSUE TITLE
Incorrect hover effects on fields in read-only libraries

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#302]
(The Add buttons also appear and are clickable on production. I think that might have been fixed already on master, but if not I can create a separate issue for that.)

**Comment by tnajdek** [comment]
> (The Add buttons also appear and are clickable on production. I think that might have been fixed already on master, but if not I can create a separate issue for that.)

There was a bug (regression) detecting read-only libraries. This has been fixed as of 53ee8ad2c75ee333eb50604880d7749903430d04 but not yet released.

Hover effect still needs fixing.

**Comment by flachware** [comment]
@tnajdek I need a way to differentiate regular and read-only libraries in the first place. Could we have a `.ready-only` class on `.items`?

**Comment by tnajdek** [comment]
@flachware new class names should be there now.

**Comment by flachware** [comment]
@tnajdek the creator editables and the abstract editable do not get the disabled class yet.

**Comment by tnajdek** [comment]
@flachware thanks, these should now have disabled class as well. Creator type still has a hover effect while read-only. Currently there is `.is-disabled` class on `Select.form-control` which can be used to distinguish disabled state - this is added by `react-select` library - not much I can do about it. I can however add another class either to that element or to parent `input-group.select` - let me know what works for you.

**Comment by flachware** [comment]
@tnajdek the existing `.is-disabled` class is fine, I just missed that one.
