### ISSUE TITLE
Long fields other than URL shouldn't be truncated

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#305]
As in the client, they should wrap around in non-textbox mode.

In edit mode in the client, we switch back to a single-line textbox for fields other than Title, Abstract, and Editor. That means that there can be some shifting of the rows, but those fields generally don't span multiple lines anyway, so it doesn't really matter. If we have auto-resizing here anyway, we can just use that for edit mode (and we can adopt that in a future client version).

**Comment by flachware** [comment]
@tnajdek could we switch to auto-resizing textareas for all fields except item type, URL and creators (I believe we want to keep those in one line?)?

And if I’m not mistaken abstract and extra should be the only fields where return does not confirm but creates a newline.

**Comment by tnajdek** [comment]
Changed inputs to "single-line textareas" (previously we only used that for "title" column). Are we happy with this implementation?

**Comment by flachware** [comment]
Works for me.
