### ISSUE TITLE
Text in tag list editables gets selected when suggestions show up

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#309]
This 'clears' the text when you type one more letter.

**Comment by flachware** [comment]
@tnajdek this breaks the layout of the tag selector filter box.

**Comment by tnajdek** [comment]
@flachware Not sure if I've correctly recognized the issue you've described. The only one I can see is a "jumpy" input in the tag selector, which I've fixed it in ee0c7d21ddf92bb8228d870551531d0395d16399. Could you please test if that was it?

**Comment by flachware** [comment]
@tnajdek the filter box used to fill the entire width and the spinner was (visually) inside the box. Whenever the spinner shows up the width of the filter box changes. I suppose this is because of the dropdown in the input-group – do we actually have 'suggestions' in the tag selector?

**Comment by tnajdek** [comment]
@flachware thanks for explaining in details, I didn't notice it, should be fixed now.

**Comment by flachware** [comment]
Looks good to me!
