### ISSUE TITLE
Hide empty fields in read-only libraries

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#314]

**Comment by flachware** [comment]
@tnajdek I’m hiding metadata fields that have the `.empty` class in read-only libraries. The class is missing on `.creators-entry` currently – could you set it there too?

**Comment by tnajdek** [comment]
@flachware these will be marked as `.virtual`. Creator field cannot be empty as it will be automatically removed as soon as you finish editing, unless it's the only entry, in which case it will remain as `.virtual`. In other words there will be at most one `.virtual` entry.

I can add `.empty` to `.virtual` fields if you think that makes sense, but logic behind these classes will be the same.

**Comment by flachware** [comment]
@tnajdek I totally missed this detail, the `.virtual` class is fine. Thanks for looking into this.
