### ISSUE TITLE
Tag Selector on touch is missing

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#318]
We should probably come up with something, perhaps partially re-using designs from #250?

**Comment by flachware** [comment]
@tnajdek I’ve tried to wrap my head around this issue, here’s what I came up with so far: the general idea is to reuse the search field as tag filter and extend its functionality towards something like a multi select.

1. After entering a search query on phones we would show a mixed result list containing both tags and items. The list lets you either pick a tag or a search result (item). On larger touch devices the matching tags would be in a dropdown, similar to our existing suggestions, but on phones they would have to be in the result list due to lack of space. My first and foremost question is if we can have a virtualized mixed list, containing elements of different (known) heights?
<img width="320" alt="tag-selector-1@2x" src="https://user-images.githubusercontent.com/419747/70804108-537e4f80-1dbe-11ea-8761-ed0f7cca1552.png">

2. Once you have picked a tag we would show it in the search box in the way that is common for multi selects.
<img width="320" alt="tag-selector-2@2x" src="https://user-images.githubusercontent.com/419747/70804869-364a8080-1dc0-11ea-94d7-1e5f428ec471.png">

3. However, our search box would have to work a bit different: in a typical multi select the selected options (and the actual input element) get stacked vertically, the search box grows vertically. But if I’m not mistaken we can’t have that because a) the stacked navigation requires the touch header to be the same height on all levels (the navbar has a fixed height on larger devices too) and b) even a temporarily enlarged touch header would either overlap search results or push them down (which means the results would jump upwards once you start scrolling in the result list. So what we would need is a search box that has just one row but lets you navigate to the left/right within the box. I can’t be sure at this point, but I think it could work out using contenteditable on the outer container, so you can use the cursor to get e.g. back to the first tag in the box (as shown in the mockup). This is especially true for long tags. Moving the cursor on touch devices is a bit cumbersome, I do have usability concerns, but I couldn’t find a better solution so far (apart from smart users turning the device to landscape orientation – which really makes a difference). Please let me know what you think about those obstacles.
<img width="320" alt="tag-selector-3@2x" src="https://user-images.githubusercontent.com/419747/70804942-6f82f080-1dc0-11ea-9f14-5ab50b61395b.png">

**Comment by dstillman** [comment]
Enhancing searches with some token-based functionality (for tags and other things) is probably something we want to do in general, but I think it would be a shame to lose the ability to view and scroll through tags without filtering — particularly (but not exclusively) for colored tags, which are meant to always be visible.

I think something closer to what you had in #250 would make more sense, where you can pull up the full tags list, filter that as necessary, and then collapse it, with a visual indication of how many tags are selected. That would allow us to use the full height for the tags list on phones.

On phones, neither of these approaches would work for assigning multiple items to tags, as you can in the client, so I guess we'd need something else for that. (I don't think we support that in the web library on desktop yet, but we should.)

**Comment by flachware** [comment]
@tnajdek @dstillman here are new drafts for the tag selector that allow browsing through the tags.

**On phones:**

1. We would show the footer with the tag icon only in search mode on phones.

2. Tap on the tag icon slides in the tag selector which lets you browse through the tags.

3. Tags can be filtered.

4. Selected tags are rendered between the filter box and the tag list. Tap on 'Done' closes the tag selector.

5. Tap on '2 Tags Selected' reopens the tag selector to alter the tag selection. Tap on the filled tag icon disables the tag selector. 

<img width="1728" alt="tag-selector-phones@2x" src="https://user-images.githubusercontent.com/419747/70999645-7bcdbd00-20e2-11ea-95bf-52d3709ceaf7.png">


**On larger touch devices:**

1. On larger touch devices we would permanently show the footer with the tag icon in the sidebar.

2. – 5. as on phones.

<img width="1728" alt="tag-selector-touch@2x" src="https://user-images.githubusercontent.com/419747/70999238-ac612700-20e1-11ea-902b-4d80ce199be2.png">

**Comment by tnajdek** [comment]
This looks good, if @dstillman approves I'd say we go ahead with it.

When just one tag is selected should it actually say what the tag is (e.g. "red-tag") instead of saying "1 Tag Selected" in the footer?

**Comment by flachware** [comment]
>When just one tag is selected should it actually say what the tag is (e.g. "red-tag") instead of saying "1 Tag Selected" in the footer?

That makes sense to me. But I guess we should keep a good distance between the tag icon and the tag name then to make it clear that those are two different options?

<img width="320" alt="variant-1@2x" src="https://user-images.githubusercontent.com/419747/71015803-decc4d80-20fc-11ea-9935-ec678e62070b.png">

Alternatively we could list all tags in a smaller font size generally (which would provide space for about 4–5 short tag names).

<img width="672" alt="variant-2@2x" src="https://user-images.githubusercontent.com/419747/71015834-ec81d300-20fc-11ea-8af8-8f5f9e827c89.png">

**Comment by flachware** [comment]
@dstillman do you approve?

**Comment by dstillman** [comment]
I think this works in general, but I'm a little concerned that people won't realize that the tag icon and the rest of the bar are separate and will either not know how to clear all tags without doing it manually or will accidentally clear all tags when trying to open the selector. It might be better to just put a clear button of some sort in the selector itself.

**Comment by flachware** [comment]
There is a clear button at the top left of the selector ('Deselec...' [Deselect All]). If I understand correctly you would like to treat the entire footer as one button, which always just opens the tag selector, right?

**Comment by dstillman** [comment]
Ah, I didn't see that. We should figure out a way to not have a truncated label, though. I'm not sure the top left corner is going to work.

But yes, I think having the footer be one button would be better.

**Comment by flachware** [comment]
How about moving the 'Deselect All' to a more prominent footer while the tag selector is open?

<img width="1728" alt="tag-selector@2x" src="https://user-images.githubusercontent.com/419747/71912254-d4422880-317d-11ea-9333-51c46c874a21.png">

**Comment by dstillman** [comment]
Yeah, I think that's right.

**Comment by flachware** [comment]
Alright. @tnajdek I think we are good to go ahead. Would you like to build the touch version inside the tag-selector component or as a separate one (in the former case let’s set a different class, e.g. `tag-selector-touch`)?

**Comment by tnajdek** [comment]
@flachware I think we need a new component, it probably should be called `TouchTagSelector` (because we already have `TouchNote`, `TouchHeader` etc.).

Also the number of items displayed next to a tag might be confusing so just want to double check if we want to show it. The reason for it that we only know the total number of items tagged with given tag. However if you go to collection "foo" and select items tagged with tag "bar" you may only see a portion of items (e.g. it will say 10 because there are 10 items tagged "bar", but will only show 5 when clicked because only 5 of them are in collection "foo"). Is that OK?

**Comment by flachware** [comment]
@tnajdek ok `TouchTagSelector` is it then. Would you like me to add some dummy markup for starters or would you prefer building the component from scratch yourself?

Re the counter, if we cannot show the 'actual' number regarding the current collection I’m inclined to say that we should not show the counter. But in the mobile version of the old web library the counters do not update either, so I think @dstillman should make a call on this.

**Comment by tnajdek** [comment]
@flachware I don't want to block you so please feel free to put dummy markup straight into `library.jsx` and I'll move it into separate components later.

I believe each tag row will be of fixed height in this case, is that correct? It would give us opportunity to virtualize the list on mobiles which would offer better performance.

**Comment by flachware** [comment]
@tnajdek alright, yes we will be able to virtualize the tag list.

**Comment by flachware** [comment]
@tnajdek I’ve added a basic dummy. Let’s work on the tablet size first and do the special case on phones at the end. First thing that would be helpful: could you wire up the tag icon button to toggle the rendering of the `.pane`? We will want the pane to slide in using react-transition-group at some point, but for now a hard toggle is fine.

**Comment by tnajdek** [comment]
@flachware nice one! I've moved the dummy to a separate file and wired open/close buttons. I've already included css transition logic but for now it doesn't do anything (other than delay closing by 200ms) - let me know what classes should be there and I'll tweak this.

I'll also work in parallel to replace dummies with real tags and virtualisation.

**Comment by flachware** [comment]
@tnajdek while adding some dummy tag colors I came to think about the current tag colors in production – what needs to be done to update those to the ones we have locally?

**Comment by tnajdek** [comment]
@flachware not sure if I follow. Zotero, by design, supports [9 fixed tag colors](https://github.com/zotero/zotero/blob/1a790c0c3f2a395efeced7dc84722b6412da0709/chrome/content/zotero/tagColorChooser.js#L54). In web-library we display these but don't have an option to change a colour of a tag yet, this is tracked in #238.

**Comment by dstillman** [comment]
Yeah, I don't think the counter makes sense in a filtered context, since as @tnajdek says it's not clear whether it's referring to the unfiltered or filtered view, and either one would be sort of confusing.

**Comment by flachware** [comment]
@tnajdek sorry, my bad – I still had the old tag colors in my test library. After assigning the current colors in the client the colors in my test web-library are up to date, nevermind!

**Comment by flachware** [comment]
@tnajdek I realized that the touch-footer that contains the tag icon could theoretically provide non-tag related functionality and therefore should probably not be part of the touch-tag-selector component. Would you agree to make it a standalone touch-footer in the sidebar (and the `.pane` would be the `.touch-tag-selector` then)?

Should we show a spinner in the empty space while the tags are being loaded? And should we show placeholders while scrolling the tag-list like in the items-list?

**Comment by tnajdek** [comment]
> @tnajdek I realized that the touch-footer that contains the tag icon could theoretically provide non-tag related functionality and therefore should probably not be part of the touch-tag-selector component. Would you agree to make it a standalone touch-footer in the sidebar (and the .pane would be the .touch-tag-selector then)?


I've created a new component named `TouchSideFooter` (we already have `TouchFooter` used when in items selection mode), but didn't  merge `.touch-tag-selector` and `.pane` into a single `div`, because not sure if that's what you meant? I recon it would need some re-adjustments in styles to make it work that way.

> Should we show a spinner in the empty space while the tags are being loaded?

That's done. Bear in mind tags are being loaded every time a tag is selected/unselected (because affects the query thus changing what tags are available for selection)

> And should we show placeholders while scrolling the tag-list like in the items-list?

Yes, placeholder `<li>` elements now have `.placeholder` css class.

**Comment by flachware** [comment]
>I've created a new component named TouchSideFooter (we already have TouchFooter used when in items selection mode)

That looks good to me, although I’m wondering if the component needs to have a different name than TouchFooter as the one for the items selection mode is in the items-container, not in the sidebar.

>but didn't merge .touch-tag-selector and .pane into a single div, because not sure if that's what you meant?

Yes that’s what I meant, no need for an additional container with a single child, that’s done.

Spinner and placeholder look good to me.

**Comment by flachware** [comment]
@tnajdek When you open the touch-tag-selector for the first time and e.g. filter for 'green', a spinner shows up in the input-group, 'green-tag2' stays in the view, and placeholders show up while filtering.

Could we use the spinner in the center we already had instead of the one in the input group? The results would show up all at once then and we would not show the placeholders (I think we should only show placeholders for items that we know that they exist). Instead of the spinner in the input-group I’d like to show a clear button (like in the draft) – I don’t know if we could reuse the search component we use on phones? The current spinner in the input-group shows up when you select a tag, which duplicates the spinner in the center. So basically I would like to have just one spinner but a clear button.

**Comment by flachware** [comment]
Oh and I guess the filter should not be applied to the selected-tags list?

**Comment by tnajdek** [comment]
`Could we use the spinner in the center we already had instead of the one in the input group? The results would show up all at once then and we would not show the placeholders`

I've tweaked the implementation to this, except for the `results would show up all at once`. For now results will display gradually as the search progresses. This will be fixed once I can do #346.

> Oh and I guess the filter should not be applied to the selected-tags list?

That's done (on touch).

**Comment by flachware** [comment]
In order to avoid the spinner from overlapping with the gradual results I’ve tweaked the tag-selector list to not show up while the spinner is in place (we could also just hide it with CSS if that would be a performance benefit).

**Comment by flachware** [comment]
I’ve prepared styles for the filter/search box, but they don’t work with the current Input component. The styles assume the search structure we already have in two places:

```
.input-group.search
  input.form-control
  button.btn.clear.btn-icon
```

Could you update the structure in this respect?

**Comment by tnajdek** [comment]
> In order to avoid the spinner from overlapping with the gradual results I’ve tweaked the tag-selector list to not show up while the spinner is in place (we could also just hide it with CSS if that would be a performance benefit).

That's fine for now, thanks. Once #346 is done we will be able to tell how many results to expect, and fetching first page of results will be much quicker - we might want to revisit this implementation then.

> Could you update the structure in this respect?

Done

**Comment by tnajdek** [comment]
I believe the next major milestone for this issue is to make this work in tandem with "select mode" on small screens, where I suspect select mode should simply overlap this, perhaps with an animation to make it clear?

Once that's done I'd like to make a new beta release, if that's ok with you?

**Comment by flachware** [comment]
The design always planned to show the TouchSideFooter in search mode only on phones – so there is no conflict with the select mode. I’ve added a CSSTransitionGroup to fade in the TouchSideFooter on phones, but render it permanently on larger touch devices.

I think there is a bug that we should fix before a new beta release (otherwise I’m fine with it): when you select a tag, then select a search result to view its item details and then tap '< Search Results' in the touch header, the selected tag gets cleared. I guess you would like to see the same list of search results again, so the selected tags must not change in this case.

**Comment by flachware** [comment]
Looks good to me, is this good to close?

**Comment by tnajdek** [comment]
@flachware thanks, this is neatly done and works excellent on tablets and above.

I've found couple of flaws on mobiles (aka single column devices):

1. You've opted to not show `TouchSideFooter` in `item-details` view which caused anomalies when rendered (didn't appear correct). I've removed that extra condition and it seems to work fine, was there any particular reason why you didn't want tag selector in that view?
2. Current strategy has a rather substantial discoverability issue. On real device, when you press magnifying glass for search, search input gets focused, consequently triggering virtual keyboard which overlaps bottom of the screen, completely covering `TouchSideFooter`. This means that most users may never realize there is tag selector available on these screens. Not sure how to deal with it, I think we will need to either make `TouchSideFooter` permanently visible, prevent auto-focus on search input or add another icon to the header - none of these solutions is ideal.

**Comment by flachware** [comment]
@tnajdek re 1., yes I’d like to treat the TouchSideFooter identically to the SearchBar, which fades out when you switch to the item-details. So basically, whenever the SearchBar is not visible, the TouchSideFooter shouldn’t be there either. I didn’t recognize any issues, what anomalies did you see?

Re 2., I have to think about this a bit more (any solution to this might also solve 1.).

**Comment by flachware** [comment]
@tnajdek I’ve added a tag icon to the navbar on phones, I believe this is the least painful variant. We are basically decoupling the selector from search, like it works on any other device. I think it should work like this on phones:

- When you tap the tag icon button in the navbar, the touch-tag-selector should open
- When you select a tag in the touch-tag-selector, the touch-side-footer should be rendered, this happens behind the touch-tag-selector.
- We need to set a class on the `.library-container`, e.g. `.touch-tag-selector-active` when there are selected tags and the touch-side-footer is in place. We need this class to modify the height of the search backdrop, the items-list, etc.
- We do not need the CSSTransitionGroup anymore, as showing/hiding of the touch-side-footer will always happen invisibly behind the touch-tag-selector.
- Re 1., there is no need anymore to fade out the touch-side-footer in the item-details, I’ll solve this with a CSS transition.

**Comment by tnajdek** [comment]
@flachware I've implemented required tweaks. I think we only need that last final change to fade out the touch-side-footer in the item-details and we're good to go? Let me know what you think.

**Comment by flachware** [comment]
@tnajdek ok I think that should be done. It’s a bit hacky layoutwise, at some point I’d like to refactor the structure and break up the nesting. Having `.item-details` as a sibling of `.items` would make things easier (less semantic, but much easier to work with for the stacked metaphor on touch devices).

**Comment by tnajdek** [comment]
@flachware Nicely done, thanks. I understand, there is lots of accumulated stuff that evolved over the course of development and could use some refactoring. I think we should be ok to start addressing things like that immediately post 1.0 release.
