### ISSUE TITLE
Item details pane disappears on non-touch small devices

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#319]
When selecting multiple items on non-touch, desktop device at resolution 1024x768, item detail pane disappears. It can be brought back by selecting another collection.

**Comment by flachware** [comment]
@tnajdek I believe the styles worked correctly at some point, I guess we did not set the `select-mode` class on `.items` on non-touch devices before? As there is no explicit select mode on desktops I think we should not set this class on those devices.

**Comment by tnajdek** [comment]
thanks @flachware, that was it
