### ISSUE TITLE
Rich editor disappears on reload on touch devices

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#321]
@tnajdek when I’m viewing a note on a touch device and reload, it seems that TinyMCE does not get re-initiated.

**Comment by tnajdek** [comment]
@flachware I've fixed that issue, however the spinner does not appear while waiting for relevant fetches to come back, because it renders behind `.rich-editor-container`

**Comment by flachware** [comment]
@tnajdek the rich editor does not disappear anymore – that looks good to me and was my main concern currently, as it slowed down working on the editor.

What I can see there are more issues left than the hidden spinner, primarily the layout being unstable during reload: when you reload, the touch-header in the item-details disappears for a moment and during this time the note does not fill the entire height.

Not sure if we should address this right away, but if you find the time you could look into this, otherwise we’ll fix it once we focus on touch devices.

**Comment by tnajdek** [comment]
This isn't a regular scenario, and it doesn't affect functionality, we can address this later.
