### ISSUE TITLE
Keep or cancel edit mode on desktops?

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#322]
@tnajdek when you switch to edit mode in the item details on a tablet sized viewport and then enlarge the viewport (or switch from touch to mouse) the `.editing` class on `.panel` persists, which breaks some styles. I could fix that but I’m wondering if we should not cancel the edit mode in this case?

**Comment by tnajdek** [comment]
Resizing viewport doesn't switch off edit mode - after all we don't want rotating a tablet to affect edit mode. However switching user should so I've implemented a tweak so that when user switches from touch to mouse, edit mode will automatically switch off. Do you think that does the job?

**Comment by flachware** [comment]
Right, yes that looks good to me.

**Comment by flachware** [comment]
@tnajdek I think the tweak has to be refined. When you shrink the browser window to tablet size, click edit and then try to edit a field the edit mode is switched off. So I guess on 'small' devices we never want to switch off the edit mode.

**Comment by flachware** [comment]
@tnajdek 455fc65 seems to break some things:

When loading the web-library on desktops the touch spinner shows up in the left edge of the item box. 

Loading the item details view of an item in a tablet sized viewport (same in the dev tools emulator) results in a mixture of desktop and touch components, the 'All Items' node in the sidebar is missing, etc. Once you click inside the web-library the layout is correct (although the mouse or touch class does not change).

**Comment by tnajdek** [comment]
@flachware pushed too early, should be fixed now.

**Comment by flachware** [comment]
@tnajdek yes, looks good to me now.
