### ISSUE TITLE
Revisit keyboard navigation on desktops

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#327]
- [x] Navbar
- [x] Collection tree
- [x] Tag selector
- [x] Toolbar
- [x] Item table
- [x] Tabs (#328)
- [x] Info pane
- [x] Notes pane
- [x] Tags pane
- [x] Attachments pane (#298)
- [x] Related pane
- [x] Rich editor (#336)

**Comment by tnajdek** [comment]
This is mostly done, major ones tracked as #218, #336, #388.
