### ISSUE TITLE
Notes editor broken on landscape tablet

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#332]
On iPad, in landscape mode, selecting a note breaks the interface. It's also impossible to go back without changing selected item.

<img width="771" alt="Screenshot 2019-12-02 at 20 58 07" src="https://user-images.githubusercontent.com/214628/69990678-7a2ec180-1546-11ea-964c-fad08b089ba2.png">

**Comment by flachware** [comment]
This issue has already been solved and has been superseded by #349.
