### ISSUE TITLE
Standalone Notes Editor not visible on touch

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#338]
Everything is rendered but `.editor-container` has height of 0px.

**Comment by flachware** [comment]
@tnajdek to clarify, this is not a bug, it is `work in progress` as some other touch/small issues (should we create a label for that?).

So what we need to do here is to show the editor, the tag list, and related items at the same time. I suggest to keep the scrolling panel-body like it is and use a plugin like this https://www.tiny.cloud/docs/plugins/autoresize/ to resize the editor to its content.

Alternatively we can restrict tags and related items to one row each like in the client and allow editing in modals. I’m not sure the edit mode would make a lot of sense then.

**Comment by flachware** [comment]
@tnajdek I’ve added a min-height to the rich-editor to make the content of the note accessible. We still need to autoresize the rich-editor (like described above) in order to avoid double scrollbars.

**Comment by tnajdek** [comment]
@flachware I can't see double scrollbars so I can't exactly confirm in which scenarios we would need autoresize. Could you please explain where I can see this i.e whether it's on touch or desktop and does it only apply to standalone notes or also other views like standalone attachment?

**Comment by flachware** [comment]
@tnajdek I’ve added some tags to '_Standalone Note with Tags' to clarify the situation. The item-details view of standalone notes can also contain tags and related items. In this case both the editor and the whole view can be scrollable (double scrollbars). I’d like only the view to scroll in this case and the editor to autoresize based on its content. If I’m not mistaken we have this issue only with standalone notes, as we show the note directly instead of a note list.

**Comment by tnajdek** [comment]
@flachware thanks for explaining, I guess I was looking for actual visible scrollbars before. Could you please check if now it behaves as expected? If that's the case, can we close this?

**Comment by flachware** [comment]
This is great, except that the calculated height is a bit off. For me `.tox-tinymce` is 50px too height (once I have removde the border at the top, currently it’s 49px).

**Comment by tnajdek** [comment]
@flachware I believe maybe tinymce does this on purpose to show that the next line is empty? I've set `autoresize_bottom_margin` to 0, does that work?

**Comment by flachware** [comment]
@tnajdek we need to limit the `autoresize` to touch devices.

We might rather want a min-height instead of a permanent margin, like we already have it on phones. On touch devices it looks really odd when the toolbars are higher than the editable area. I’m having a look at it.

**Comment by tnajdek** [comment]
Agreed, definitely should have been touch only, fixed now. Not sure which styles to remove you refer to.

I think this now works as expected?

**Comment by flachware** [comment]
Looks good to me now. You are right, we need the autoresize styles in `_rich-editor.scss`, I didn’t test with long notes before. I think this is good to close.
