### ISSUE TITLE
Update default APA style to 7th edition

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#341]
Not sure how styles are updated in web-library (maybe like ZoteroBib where it just needs to be rebuilt?), but we should pull the latest styles.

**Comment by tnajdek** [comment]
Yes, this should happen automatically during the build.

**Comment by tnajdek** [comment]
Turns out it would only refresh styles during development but not during the production build. I've fixed that and it should automatically during for next release.

**Comment by tnajdek** [comment]
Styles have been updated in the latest deployed build.
