### ISSUE TITLE
Items table columns are misaligned with permanent scrollbars

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#345]
This is especially visible if some titles are not truncated. The items-table-body has a scrollbar, the items-table-head not – so the widths of the columns are out of sync. We need to subtract the actual width of permanent scrollbars from the CSS variable of the last column.

**Comment by tnajdek** [comment]
@flachware Could you please have a look if the way I did it is OK? Instead of subtracting that much, I actually add that value, pushing all the columns into place without creating additional separator at the end. Let me know if this works for you?

**Comment by flachware** [comment]
@tnajdek sorry, this doesn’t solve the issue. Please have a look at the screenshot below – the columns are still misaligned. We have to subtract the scrollbar width from the CSS variable of the last column that is set on items-table. This adjusts all rows below, we can’t just modify the header. The reason is that rows with and without truncation have a different spacing otherwise.

<img width="286" alt="Screenshot 2020-02-07 at 08 43 17" src="https://user-images.githubusercontent.com/419747/74010548-0b2a7a80-4986-11ea-9f7e-4487dd4d79f5.png">

**Comment by tnajdek** [comment]
@flachware Thank you for explaining, screenshot helped! I believe this is now sorted but please reopen if you can still see the issue.
