### ISSUE TITLE
Rework landscape tablet layout

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#349]
@tnajdek I think the stacked layout (item-list on top, item-details at the bottom) on landscape tablets does not work as good as on desktops (mainly because there is less space in relation to the element dimensions). As we already have a stacked navigation on other touch devices (item-details sliding in and covering the items-list, not showing both at the same time) we could simply treat the tablet landscape layout like the portrait layout. Would you agree?

**Comment by tnajdek** [comment]
Yes, it makes sense, let's do that.

**Comment by flachware** [comment]
@tnajdek ok the basic adaption should be done. This might cause some more regressions I haven’t noticed so far, but there are at least two I would need you to fix:
- On portrait tablets we use one spinner in the item details instead of multiple spinners in the tab panes – on landscape tablets it should work the same now (if I’m not mistaken we can use the single spinner on touch devices and multiple ones on mouse devices?)
- We hide empty tab panes on portrait tablets in default mode, it should work the same on landscape tablets.

**Comment by tnajdek** [comment]
That should do it. I had a quick look, seems to work well!

**Comment by flachware** [comment]
Thanks, looks good to me – but let’s keep an eye on regressions …
