### ISSUE TITLE
Dispatch ZoteroItemUpdated events

### ISSUE THREAD

**Issue by fcheslack** [zotero/web-library#361]
ZoteroItemUpdated event should be dispatched when an item is selected, or the current library, collection, or tags change.

https://www.zotero.org/support/dev/exposing_metadata#force_zotero_to_refresh_metadata

**Comment by tnajdek** [comment]
Summary of changes done to make the translator work again:

* Web Library exposes data directly: 8024ddf31945b95d85101dea30064a9084b6abfb
* Web Library adds exception for a hidden browser: 1d236b23fb73c006897a4017ee2cd95c12b561cb
* Tweaks to the translator to distinguish new/old web library: zotero/translators/pull/2129
* Tweaks to the hidden browser to enable `window.history` zotero/zotero@8f1acad2d8c07912b52182b79b97063ed1630098
