### ISSUE TITLE
tags are not component-encoded in API requests

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#363]
https://forums.zotero.org/discussion/comment/349467#Comment_349467

**Comment by tnajdek** [comment]
Should be fixed now.

**Comment by tnabtaf** [comment]
@tnajdek Thanks.  However, I'm not seeing the fix at https://www.zotero.org/groups/1732893/galaxy/library.  See the +Methods tag for an example.  Any estimates on when this change might make it to the website?

**Comment by fcheslack** [comment]
Sorry about that. It was deployed this morning but I missed a dependency. Should be fixed if you reload the library now.

**Comment by tnabtaf** [comment]
Thanks @fcheslack !  I can confirm that all now appears well.  And issue #364 is also fixed.  I'll post a followup to the forum.
