### ISSUE TITLE
Typing "today" in Date field results in "YYYY-MM-DD today"

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#366]
Instead of just YYYY-MM-DD

(I don't think this is something the API tries to do, but correct me if I'm wrong.)

**Comment by tnajdek** [comment]
From what I can see web-library sends a POST request to make an update with `"date":"today"` and receives `"date": "YYYY-MM-DD today"` from the API.

**Comment by tnajdek** [comment]
@dstillman I'm quite convinced this is APIs doing. As described above it seems to concatenate the actual date and the relative day description together, it happens for "today", "yesterday", "tomorrow". Please let me know how best to approach this.

**Comment by dstillman** [comment]
Sorry, fixed. The web library should convert these on its own, [as the client does](https://github.com/zotero/zotero/blob/0b9f463b9f1a7bf5d59a7ce5fa00a97f5ea019d9/chrome/content/zotero/xpcom/date.js#L717-L731), though it's not a high priority.

**Comment by dstillman** [comment]
Here are the two places we do this in the info pane:

https://github.com/zotero/zotero/blob/5bb2486040fa1fc617c81b4aea756ba338584f6b/chrome/content/zotero/bindings/itembox.xml#L1927-L1934

https://github.com/zotero/zotero/blob/5bb2486040fa1fc617c81b4aea756ba338584f6b/chrome/content/zotero/bindings/itembox.xml#L1973-L1977
