### ISSUE TITLE
Remove "Export Collection" and disable for >100 selected items

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#367]
Currently, Export Collection [seems to be limited to 25 items](https://forums.zotero.org/discussion/81584/for-a-collection-with-71-items-the-bibtex-export-has-only-25), and I believe the API itself will only generate a export with up to 100 items.

This is something we need to fix on the API side — possibly by returning a 202, performing the export asynchronously, and having clients poll for updates from a URL given in a Location header — but until then we should probably 1) remove Export Collection as an option and 2) disable export if more than 100 items are selected.

Similarly, we should probably remove "Create Bibliography" for collections, and disable when >150 items are selected (which I think is the limit).

**Comment by tnajdek** [comment]
Disabled for now, will revisit once API changes are done (#368)
