### ISSUE TITLE
Link to publication from Web Library entry

### ISSUE THREAD

**Issue by tnabtaf** [zotero/web-library#369]
I don't see a way to link to a publication from a publication entry in the web library.  

There are two fields under the Info tab that could be a link:

* **URL**: Also, the full URL isn't displayed, which means people can't even copy and paste it.
* **DOI**: If present, then this could also be a link.

Right now, if a pub has a DOI then people can build a URL.

Thanks,
Dave C

**Comment by dstillman** [comment]
As in the desktop app, you can click the DOI or URL labels to follow the links.

(Also note that we [don't use these trackers](https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md) for general troubleshooting. Feature requests and bug reports should be posted to the [Zotero Forums](https://forums.zotero.org), where we're best able to help.)

**Comment by dstillman** [comment]
> Also, the full URL isn't displayed, which means people can't even copy and paste it.

BTW, if you do want to copy the URL in a read-only library without following it, you can just double-click the value to select the whole string and copy it — browsers select the whole string even when part of it is visually truncated. (And in an editable library you can obviously just click on the field to edit it, copy it, and Esc out.)

**Comment by tnabtaf** [comment]
Thanks @dstillman.  I apologize for the extra noise.
