### ISSUE TITLE
Double-clicking item should open DOI/URL/link-attachment if no file attachment

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#376]
As in the desktop app. Here's the logic:

https://github.com/zotero/zotero/blob/c22b6ae68a15778d9e75584be5141fc18e429fb5/chrome/content/zotero/zoteroPane.js#L3931-L3976

https://forums.zotero.org/discussion/82219/double-clicking-entry-in-web-library-doesnt-open-webpage

**Comment by tnajdek** [comment]
New logic included in 0.12.24
