### ISSUE TITLE
Extra column is not sortable

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#380]
https://forums.zotero.org/discussion/comment/352526/#Comment_352526

**Comment by tnajdek** [comment]
We can only do sorting on columns where there is API support for it, as far as I can tell `extra` is not supported so this would require API change?

**Comment by dstillman** [comment]
`extra` should now be sortable

**Comment by tnajdek** [comment]
Nice one, thanks!

**Comment by dstillman** [comment]
@fcheslack: Let me know when this is rolled out and I'll notify the user.

**Comment by fcheslack** [comment]
0.12.22 now pushed with this.
