### ISSUE TITLE
Dropdown menu partially obscured in the rich editor on touch

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#384]
<img width="387" alt="Screenshot 2020-04-20 at 22 49 13" src="https://user-images.githubusercontent.com/214628/79798358-2b4cc180-8359-11ea-940d-78ebf2f7f3e5.png">

**Comment by flachware** [comment]
This has been a regression due to the lastest changes in the note pane. In general, the attachment pane should be our model – toolbar outside of the scroll-container (without position sticky), just with a height set and a border-bottom for Firefox with permanent scrollbars.

**Comment by tnajdek** [comment]
Got it, thanks for looking into it!
