### ISSUE TITLE
Strip trailing whitespace from URL in the "Add By Identifier" field

### ISSUE THREAD

**Issue by AlexisPrel** [zotero/web-library#385]
Adding a document through the "Add By Identifier" button of the Web Library is such a convenient tool! 
Sometimes I copy-paste links from a page by manually selecting the link's text (because I don't want to copy the fbclid and so on), and accidentally end-up selecting an extra whitespace at the beginning or end of the URL. In that case, the addition fails with the message

> Zotero could not find any identifiers in your input. Please verify your input and try again.

I think a very simple enhancement would be to strip extra whitespace before processing the identifier.

**Comment by tnajdek** [comment]
Thanks, that's a good point. I've implemented a fix and it will be part of the next release.
