### ISSUE TITLE
Keyboard-only alternative to drag-and-drop functionality on desktops

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#388]
- [x] Adding items to collections & copying items to other libraries
- [x] Re-ordering authors.

First could be done with an extra toolbar button. Second is bit more tricky, dropdown perhaps?
These extra controls should probably only appear when keyboard user is detected so that by default users prefer drag-and-drop.

https://forums.zotero.org/discussion/82071/switching-an-item-s-folder-in-webview

**Comment by dstillman** [comment]
For reordering creators, we just need Move Up/Move Down/Move to Top in the item type drop-down, as in the client.

**Comment by dstillman** [comment]
For the former, I'm not sure what detecting a keyboard user would mean, but I think this can just be a permanent UI element for everybody.

**Comment by tnajdek** [comment]
Thanks for suggestions, will add toolbar button visible for everyone. 

(keyboard interactions other than text input toggles "keyboard" user. We use this to slightly adjust visuals, such as adding outline on focus. There is `.keyboard` class added to the `<html>` element)

**Comment by tnajdek** [comment]
Re-ordering authors as described in the [comment above](https://github.com/zotero/web-library/issues/388#issuecomment-626880388) requires separators in the select box, which is not something we currently support.

It's quite tricky to add separators to a legacy version of react-select we're currently using. It might be possible using `optionsRenderer` however, given we want to upgrade or roll our own (#131) let's do that first.
