### ISSUE TITLE
WebDAV support

### ISSUE THREAD

**Issue by quoc-ho** [zotero/web-library#393]
I use WebDAV to sync pdf files from my zotero library.  The web interface, however, doesn't seem to support viewing pdf files that are stored on an external WebDAV server.  Is WebDAV support planned in the future?

Thank you!

**Comment by tnajdek** [comment]
Please use [Zotero Forums](https://forums.zotero.org/) for enhancements requests.

There are multiple issues with implementing WebDav access from the web-library, such as networking access (WebDav might be on your internal network and/or behind firewall), security (you would most likely need to transmit WebDav credentials to Zotero) and Cross-Origin Resource Sharing (browser might not allow accessing resources on your WebDav server) thus making the implementation unlikely to happen.
