### ISSUE TITLE
Restore feed access

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#395]
I'm not sure how best to do this, but we should restore this before removing the old web library.

Given the new interface and the removal of browser feed support, it doesn't really make sense to use feed autodiscovery links, but we could add a button somewhere. Do we want to add a three-dot menu in the toolbar and hide this in there? Then in could work for any kind of view — libraries, collections, even filters (search/tag).

**Comment by tnajdek** [comment]
Included in 1.0.0-rc.0
