### ISSUE TITLE
Improve discoverability of the "select mode" on touch devices

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#399]
Currently hidden behind "..."

https://forums.zotero.org/discussion/comment/359917/#Comment_359917

**Comment by tnajdek** [comment]
We will work towards moving it out from under the "..." menu on larger touch devices (tablets etc.). On mobiles the UI is already very busy so it will most likely remain underneath the "..." menu.

**Comment by tnajdek** [comment]
https://forums.zotero.org/discussion/87173/documenting-mobile-web-functionality

**Comment by tnajdek** [comment]
We could also, as an alternative, support a really-long-press (~1s) on an item to toggle select mode (with that item being selected to start with). Not sure how common such gesture is but I've seen it in both iOS and Android apps.

**Comment by dstillman** [comment]
> Not sure how common such gesture is but I've seen it in both iOS and Android apps.

Yeah, I could see doing that. Looks like the Gmail app does that on iOS.
