### ISSUE TITLE
Add base-mapped fields to items list table

### ISSUE THREAD

**Issue by fcheslack** [zotero/web-library#40]
https://forums.zotero.org/discussion/56920/adding-publisher-column-does-not-show-institution-field/#Comment_249557

**Comment by dstillman** [comment]
Depends on https://github.com/zotero/dataserver/issues/23

**Comment by fcheslack** [comment]
Ideally it would be done using that, but doesn't seem like a bad idea to hard code it before then. Would likely need to be aggressively cached anyway if custom item types makes the mapping sprawl to a greater degree.

**Comment by dstillman** [comment]
Yeah, that's fine.
