### ISSUE TITLE
Confirm that unavailable attachments don't show error message

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#402]
https://forums.zotero.org/discussion/84454/cant-access-child-items-when-using-web-browser

I haven't tested this, but it sounds like this person was getting some sort of error for unsynced files. Those should just be unavailable, or, perhaps better, display a clearer message explaining that the files aren't available, possibly because they haven't been synced — but they shouldn't display a "Not found" sort of error.

**Comment by tnajdek** [comment]
This will now say: "Requested file is not available. It might not have been synced yet." Does that work or should I change the wording?

I believe this only actually happens when user double clicks on a top-level attachment where file is missing or hasn't synced.

**Comment by dstillman** [comment]
Shouldn't that just not do anything, though? Don't we know whether there's an attachment file available at the time they click?

**Comment by tnajdek** [comment]
Sure we can, fixed and released as of `v1.0.0-rc.5`
