### ISSUE TITLE
URL is incorrectly truncated on mobile

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#403]
If URL field is too long and doesn't contain a character that would allow line break, it triggers vertical scrolling on mobile devices while in read-only mode.

**Comment by flachware** [comment]
@tnajdek the truncation logic is tied to the `.editable-content` element, which is missing in this case. Could you wrap the link in an `.editable-content` element?

**Comment by tnajdek** [comment]
That's a good spot, thanks @flachware
