### ISSUE TITLE
Attachment column improvements

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#448]
- We should basically mirror iOS and show whatever will happen on double-click, including a link icon for URL/DOI.
- For snapshots, we should show the snapshot icon instead of a white page.
- For standalone attachments, I guess we should show another PDF icon when the file is available — it's a little more awkward here because we only have one icon size, so there'd be a PDF icon on the left and on the right, whereas on iOS there's a bigger main icon on the left, but otherwise there's no way to tell if a standalone attachment file is available without just trying to double-click it and having nothing happen.
- Since this is no longer strictly about attachments (DOI/URL), maybe there's something else to call the column, but I'm not sure what, so maybe we stick with "Attachment".

Once we've done these things, we should probably force this on for all users with a migration step, since it's pretty useful and consistent with iOS.

Related to some of the confusion in https://forums.zotero.org/discussion/90784/cant-access-videos-in-web-library

**Comment by tnajdek** [comment]
@dstillman One thing that cannot be done is to show an icon for when the "best attachment" is a linked URL. There is no mention of it in `links` but we have this fallback behaviour on double click where we download child items and open linked URL if present.

Other than that I believe it's all done.
