### ISSUE TITLE
Implement touch mode

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#45]
As already concluded it does not make any sense to blindly detect touch devices, the user has to be in control of the information density.

Nevertheless a best guess seems feasible, therefore a modernizr test detecting `touchevents` could already be implemented.

As the user should be able to toggle density modes in the settings, I will not use modernizr’s `touchevents` class directly but rather our own `touch` class~~, either~~ on the ~~`html`or~~ `body`element.

Our class would reflect the modernizr test unless the user decides against it.

We don’t have the settings dropdown yet, but it will be available soon.

**Comment by tnajdek** [comment]
Do we still intend to implement settings where users can disable "low density" mode?

**Comment by flachware** [comment]
Yes, I still believe we should add an option to the navbar that allows toggling between desktop and touch devices. Let’s address this once we are working on the navbar – that toggle could be a post 1.0 feature.

At any case, I suggest to refine the logic when we set the `touch` class by checking the media feature `pointer: fine|coarse` – this way we should be able to e.g. set the `touch` class on landscape tablets even before the first tap happens.

**Comment by flachware** [comment]
@tnajdek I know that it was me who wanted the touch class in the first place … however, as using a class already comes with some troubles in terms of selector specificity I’m questioning it now.

I think the main reason behind the touch class was the concern to not being able to reliably detect touch devices, right? Unless someone is using IE support for `pointer: fine|coarse` is pretty good, so do we have any doubt that we can detect mouse|touch devices reliably?

Because if we have no doubts, I would actually suggest that I don’t use the `.touch` class and use a `pointer: fine|coarse` media query directly in CSS (in combination with viewport widths), with the advantage that it does not increase specificity. We would also remove the mouse/touch mode override then.

**Comment by tnajdek** [comment]
I don't mind, however we might need a way to override which mode is used from within js. I remember we've discussed having a preference allowing user to override which mode is used, which would come handy on laptops with touch where user might experience constant UI switching whenever they touch the screen to scroll while also using a touchpad etc.

**Comment by flachware** [comment]
I think it boils down to the question if there is a need for a user preference. If we want that preference, we have to stick to the class (I’m really longing for this CSS4 feature here: https://css4-selectors.com/selector/css4/specificity-adjustment-pseudo-class/). Is it a legit requirement that users can mix touch and mouse inputs with one layout mode? Why would you scroll via touchscreen but use the touchpad/mouse for the rest?

I’m not against the preference per se, I’m questioning it on the one hand because I have the feeling that we might have gone this way because back in the time when we conceptualized the web-library there haven’t been reliable methods to detect touch devices (we figured that viewport widths would not be good enough). And on the other hand the 'touch-or-small' vs 'mouse-and-large' dichotomy is arguably the hardest permanent issue in the stylesheets, and in part it is because of the `.touch` class.

So I’m fine with using the touch class as long the user preference is not just a hypothetical thing and there are valid use cases (which might very well be the case).

**Comment by tnajdek** [comment]
Use case example I've provided is based on me actually seeing someone using their laptop (Dell XPS 13) like that. I don't know how common it actually is.
