### ISSUE TITLE
Icon component

### ISSUE THREAD

**Issue by johanneskrtek** [zotero/web-library#46]
I would like to have a shared set of icons for both Zotero and Tropy.

I guess it makes sense to implement them in a similar manner: all icons will be inline SVGs, in order to keep the components clean we decided to put them in an icon component themselves for Topy (have a look at the repository in components/icons.js). The icon component does not need any logic.

The rationale behind this approach is the ability to control the icons with CSS. Every SVG (or at least where needed) will contain a 'linear' and a 'block' version, which can be selected and colorized (or even animated) then.

**Comment by stakats** [comment]
I like this idea.

**Comment by tnajdek** [comment]
Tropy uses an Icon component where SVGs are inlined onto page. This makes perfect sense for Tropy as it is a electron-powered desktop app.

However for the web-library we need a cachable approach. Hence I've opted to implement our own icon component (d27a39550be76f857ce2bfb29fb9b8c46651ef8e) where we still use inline svgs (to be able to specify color etc.) but the actual content is delivered as a separate .svg file.
