### ISSUE TITLE
Creation of a publication list for the own curriculum

### ISSUE THREAD

**Issue by Zack-83** [zotero/web-library#466]
The [Zotero CV generator](https://www.zotero.org/settings/cv) allows creating a full résumé including a publication list exported by one of the own libraries.  
Why is the list "My publications" not counted as a library? Normally it is the only one which people would like to include into the own cv.
![grafik](https://user-images.githubusercontent.com/37865804/149509245-a5e3203a-16e7-41dd-9705-50c52f6ea059.png)

As a workaround, one might use the automatically generated publication list on the own home page, but it offers no publication to control the citation style.
![grafik](https://user-images.githubusercontent.com/37865804/149509845-eccf0baa-47d5-4e37-8559-a37a5aec529a.png)

Which is the solution?

**Comment by tnajdek** [comment]
Thanks for letting us know. There is no need to double post here and on the forums and it's actually not the right repo so I'm going to close this issue. Let's keep the discussion on the forums.
