### ISSUE TITLE
DOI as URL not recognized

### ISSUE THREAD

**Issue by rgrenz** [zotero/web-library#472]
Zotero Web throws an error ("Zotero could not find any identifiers in your input.") when trying to Add By Identifier the following DOI:
https://doi.org/10.1016/j.tele.2010.09.001

However, it works fine when just adding the DOI as:
10.1016/j.tele.2010.09.001

**The Zotero standalone application can handle both cases.**

It would improve my workflow if I could simply enter the DOI in the URL format, as this is shown on many pages and can be easily copied using the "copy link address" functionality within the browser.

**Comment by tnajdek** [comment]
Thank you for reporting, indeed an oversight on our part, pasting DOI URLs should definitely work. I've fixed this problem now and this fix will be deployed in the next release of web library (most likely at some point next week).
