### ISSUE TITLE
Separate presentation and logic, use redux

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#48]
Since we're converting the library so it doesn't depend on Bootstrap, I'm going to suggest few additional tweaks as part of this work:
1. Add Redux as a global state container
2. Use Container and Presentation components for separation ([1](https://medium.com/@learnreact/container-components-c0e67432e005#.ifcqldw7n), [2](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.76a6u08gk), [3](http://redux.js.org/docs/basics/UsageWithReact.html))
3. Remove dependency on jQuery
4. Expose all components (aka widgets) under **Zotero.ui** namespace
5. Expose static **init()** methods on components for quick DOM mounting
6. Avoid any side-effects of including the library. e.g. avoid a situitation where just including the library would inject/replace component (aka widget) into the DOM based on its attribute/id.
7. Avoid using ids (for component styling or otherwise) to allow multiple instances of the same component on a page.
8. Potentially: split of non-core functionality/components into separate library/libraries

I've done some initial work in a branch called **redux**, any thoughts and comments welcome.

**Comment by johanneskrtek** [comment]
Re 7: I’m fine with that, I would have used IDs only for components that would not have been supposed to have multiple instances on a page anyway.

**Comment by fcheslack** [comment]
1. As discussed in irc, still not entirely sure it's a good idea at the top level, depending on how we approach it. It may still require having a separate set of active Library objects that are referenced from the redux state.

2. Yes. Especially if we hope to share any of the presentational components.
3. Yes. Was already in progress with the React WIP. I believe most of the remaining dependency is not actually in the web-library, but in the pages used in other parts of the site that are included in the repo for convenience. Those should also mostly be switched to react components and jquery dependency removed though.
4. I've gone back and forth on exposing all widgets/components in a namespace on the Zotero object. It was necessary before modularization. I'm not sure it is anymore, and seems to conflict with 8(?) which would be necessary for shared components.
5. can you elaborate?
6. Yes. This should be how it works with react (as far as the DOM anyway).

**Comment by tnajdek** [comment]
`1.` Potentially, hard to say at this point. I would like to spend some time working on it, see how it works out.

`4.` The idea here is to let end-users of the library build their own tools easilly by just including the library on the page and attaching components to their DOM elements. For this to work we need to to expose some key components, we might as well expose them all. We can see how this pans out and re-visit later.

`5.` The idea behind the *init()* method is to make it easier for the end-users to mount the components. For someone who just wants to build a tool using our library, it would be a significant shortcut as opposed to using ReactDom to mount the node. We would still be able to use the components within jsx and/or mount them using ReactDom, init() would just be a shortcut, you can see it in this [concept demo](https://github.com/zotero/web-library/blob/redux/src/demo/index.html)

`8.` This might not conflict with 4, what I had in mind is to extract anything that is not stricte library to other packages (these packages could still expose them under Zotero.ui namespace if included). Candidates for this are page-specific components such as ProfileGroupsList, SiteSearch etc. that are not part of the. Just a thought.
