### ISSUE TITLE
Dropping a file onto attachments pane will still try to upload even if not allowed in that library

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#481]
For libraries where file upload is not allowed, most options of uploading files are disabled but dropping a file from desktop onto attachments pane will still try to upload, resulting in "Unexpected error" or "Write access denied" error  - depending on APIs response.

**Comment by dstillman** [comment]
A weird number of people seem to be hitting this — there've been like 3 or 4 reports in the last few days — so we should fix this soon.
