### ISSUE TITLE
Open PDF reader in separate tab

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#482]
Is it possible to do this? We were previously opening PDFs in separate tabs, so this would be a fairly major regression. People are going to want to continue opening multiple tabs.

Presumably it has to load the whole web library in the new tab, but maybe there's a way to optimize it? The new tab doesn't need the ability to display the web library at all — you would just close the browser tab when done, the same as before.

**Comment by tnajdek** [comment]
I've left it as a choice, i.e. normal click opens in the same tab, ⌘ click/middle click opens in a new tab. 

Do we want to force new tab?

**Comment by dstillman** [comment]
I think so — same as it was before, closer to the desktop experience, doesn't lose your place in the list (which probably could be fixed but why bother?), and Cmd-click is inherently weird (deselect/reselect) in a multi-select list (which is why we don't do anything special with that on the desktop).

**Comment by tnajdek** [comment]
Done in b8166e9f
