### ISSUE TITLE
Can't start web-library (Ubuntu 22.04)

### ISSUE THREAD

**Issue by gavieira** [zotero/web-library#484]
Hi,

I've followed the install instructions to run the web-library in a Ubuntu 22.04 machine. When running `npm start` both `"build:mappings"` and `"build:prepare"` are giving errors. I've attached a file with the output: 
[npm_start_error.txt](https://github.com/zotero/web-library/files/9716895/npm_start_error.txt)

The same error happened on another machine (Manjaro Linux). Maybe the install instructions are not up to date as suggested in [this post](https://forums.zotero.org/discussion/76864/web-library-on-own-server)? Or could it be something else?

Thanks in advance!!

**Comment by tnajdek** [comment]
Yeah, it seems instructions are bit outdated, try running: `git submodule update --init --recursive` in the cloned repo.

**Comment by gavieira** [comment]
Thank you very much! The aforementioned errors are not happening anymore.

However,  now errors are coming from `build:pdf-worker` and `build:prepare`. Please refer to [npm_start_error_2.txt](https://github.com/zotero/web-library/files/9717983/npm_start_error_2.txt) for more info.

Any help would be much appreciated!

**Comment by tnajdek** [comment]
This error is coming from [zotero/pdf-reader](https://github.com/zotero/pdf-worker) build which in turn comes from a nested dependency, the solution is apparently this:

https://github.com/Automattic/node-canvas#compiling

However node-canvas offers pre-built binaries for some os-cpu-node version combinations, I'd try switching to node version `lts/gallium` (which is what we recommend in `.nvmrc`).

**Comment by mrtcode** [comment]
More recent versions of `pdf-reader` have updated `pdf.js` submodule with no canvas package, as it was causing too much pain for everyone, but wasn't needed for our build.

**Comment by tnajdek** [comment]
@gavieira I've updated submodules which should make building web library easier
