### ISSUE TITLE
Optimize ItemsList layout while loading

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#49]
@tnajdek i know that the web library, especially its redux incarnation, still is at the very beginning and therefore not every minor issue i come across while working on the interface can or should be handled right away (and of some issues you might be aware anyware). With that said i will probably open some issues here in order to keep track of the them in the first place.

When a selection on a collection is made, the ItemList’s layout does not show up until the items are fetched. For a more stable experience it would be preferable to show the table header and the striped `item-list-body` right away, placing the spinner inside the `item-list-body` until the `item-list` shows up (so only the `item-list` would be blocked while the items are loaded).

**Comment by tnajdek** [comment]
Since then this has changed a lot and now we show a list with "fake" items until real items are loaded. I believe this is much nicer (and stable) solution. Closing in favour of #127
