### ISSUE TITLE
Added By missing from column picker

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#490]
https://forums.zotero.org/discussion/comment/421950/#Comment_421950

**Comment by tnajdek** [comment]
I can see and select "Added By" in web library on zotero.org in Firefox. Could you please confirm the following:

* You're looking at a group library (it doesn't show in My Library)
* Whether it works in another browser or in "private window"

**Comment by dstillman** [comment]
Sorry, I was stupidly trying in My Library.
