### ISSUE TITLE
Consider dropping support for Safari 10

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#511]
* Libraries increasingly start dropping support which forces us to re-transpile their code
* Some features have to be disabled (e.g. locale-aware date parsing) due to lack of support
* According to [can I use Safari 10 has 0.01%](https://caniuse.com/usage-table) (+0.07% mobile)
* On desktop, users should be able to upgrade to High Sierra which comes with Safari 11

**Comment by dstillman** [comment]
We can definitely do this.

All Macs running 10.10 can be upgraded to 10.11, which supports Safari 11, and you'd have to have an iPhone 5 or an iPad (4th Generation), both released in September 2012, to not be able to upgrade to iOS 11. All other iOS devices compatible with Safari 10 can be upgraded.
