### ISSUE TITLE
Web PDF reader annotations support

### ISSUE THREAD

**Issue by dmadisetti** [zotero/web-library#517]
Hi,

Thanks for launching the web reader about a year ago. The thread requesting annotations in web is still very much active: https://forums.zotero.org/discussion/99390/web-pdf-reader-annotations-support#latest

I just wanted to see where this was on your radar.
If this is just adding to the noise, feel free to delete this issue.

Thanks

**Comment by tnajdek** [comment]
As mentioned in the forum thread this is planned. I can't say much more, only that this is very much on our radar.

**Comment by kydchen** [comment]
I really need this feature, thanks for your work.
