### ISSUE TITLE
Add support 'deleted' property on collections

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#545]

**Comment by dstillman** [comment]
We should hide collections with `.deleted` ASAP. We don't need to display them in the trash at this point — they just need to not appear in the collections list, so we can roll out https://github.com/zotero/zotero/pull/3307 on the beta.

**Comment by tnajdek** [comment]
"deleted" collections are now hidden in web library so this should not block https://github.com/zotero/zotero/pull/3307

Remaining functionality will be implemented in #547
