### ISSUE TITLE
Configure path prefix for the API server

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#558]
_(I've split this from another issue, as it pertains to configuring the API server and not the web library's routing.)_

Dear @glorieux-f  and @tnajdek, 

I run into a  similar problem: the current zotero-webapp implementation allows to configure the apiAuthorityPart in index.html, like below. But how is it possible to change the API path of the API server ? So, e.g., in the case of @glorieux-f , 
how would I set https://www.unige.ch/piaget/api/ as the route to the zotero API endpoint ?
(We do not want to set up a second domain, just for the zotero server).

Thanks and merci !

```
<script type="application/json" id="zotero-web-library-config">
		{
			"userSlug": "zotero-user",
			"userId": "475425",
			"apiConfig": {
				"apiAuthorityPart": "api.zotero.org"
			},
			"libraries": {
				"include": [
					{
						"key": "g729",
						"name": "All Things Zotero",
						"isGroupLibrary": true
					}
				],
				"includeMyLibrary": true,
				"includeUserGroups": false
			}
		}
	</script>
```

_Originally posted by @markdoerr in https://github.com/zotero/web-library/issues/534#issuecomment-2286432956_

**Comment by markdoerr** [comment]
@tnajdek,
thanks for opening a new issue :+1:  - I hope it can be easily solved :)

**Comment by tnajdek** [comment]
So basically `apiConfig` is passed to `zotero-api-client` and eventually used [here](https://github.com/tnajdek/zotero-api-client/blob/785f9fef37011ebcfe52a30c5c6812c6d4be2ab1/src/request.js#L260) and [here](https://github.com/tnajdek/zotero-api-client/blob/785f9fef37011ebcfe52a30c5c6812c6d4be2ab1/src/request.js#L333).

It should be trivial to add support for `apiPathPrefix` or something along these lines.

**Comment by markdoerr** [comment]
Thanks, @tnajdek, for pointing at the positions in the code. Yes, indeed it would be trivial to add this extra option here, like, e.g. :

`const url = https://${options.apiAuthorityPart}/${path}${query};` 

-> `const url = https://${options.apiAuthorityPart}/${options.apiPathPrefix}${query};`

Will you do this please ? (I am heading for holidays tomorrow, so I would only have time to make a PR in September :( )

**Comment by markdoerr** [comment]
or better  (?) :
`const url = https://${options.apiAuthorityPart}/${options.apiPathPrefix}${path}${query}; `

**Comment by markdoerr** [comment]
Thanx, @tnajdek,
for adding this small, but important feature :) - I will test it in the next days ...

**Comment by tnajdek** [comment]
Please note that this feature is currently only available in the underlying `zotero-api-client` dependency and is not yet included in the web library. To use it, you will need to update the dependency locally in your build. I will update the web library before the next release.

**Comment by markdoerr** [comment]
Thanks for the hint, Tom (I guessed so ;) - looking also forward to the next release....

**Comment by tnajdek** [comment]
Resolved in https://github.com/zotero/web-library/commit/2553365060d84f8ab23e1322eabf012413419162
