### ISSUE TITLE
Add settings menu instead of Color Scheme menu

### ISSUE THREAD

**Issue by dstillman** [zotero/web-library#564]
Dark Mode doesn't merit this level of prominence. Most people will be happy with Automatic.

And we may want other web-library settings later anyway.

We have "Settings" as a menu option in the account menu, but that of course takes you to the account settings. We could potentially have a Web Library section in there and pass the settings into the web library, but some sort of gear menu within web library would probably be fine.

**Comment by tnajdek** [comment]
> We could potentially have a Web Library section in there and pass the settings into the web library,

I believe dark-mode setting should be device-specific.

> some sort of gear menu within web library would probably be fine.

I'll do that and add #169 there (we cannot use 'Request Desktop Website' for this, as I explained in my comment on that thread). In the future, we can use it to allow overriding the detected locale.
