### ISSUE TITLE
Feature: select visible columns

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#59]
Interface for selecting visible columns in the item list (#56). Currently we're using a pop up for this in the web-library and a menupopup in the client.

**Comment by decasia** [comment]
Regarding this issue: I was hoping to set a public default for selected columns on zotero.org and was disappointed that this is currently a missing feature, found [this forum post](https://forums.zotero.org/discussion/33731/public-group-and-displayed-columns) and eventually ended up here.

As a possible suggestion: If the current column selection values became part of the URL (the way that [sorting currently is](https://www.zotero.org/academography/items/order/creator/sort/asc)), then it would be possible to link publicly to the desired UI state, without needing to support customizable UI settings. (Apologies in advance that I'm not familiar enough with your codebase to know how feasible this is.)
