### ISSUE TITLE
Revisit components used by Zotero.Pages

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#65]
Web Library contains few components that are used on various pages on zotero.org but are not part of the library interface, (earlier discussion: #48 list item 8). I believe these, along with Zotero.Pages, should be extracted to a separate package(s). This however is still open for discussion/opinions.

**Comment by fcheslack** [comment]
Yeah, these should definitely be pulled out of web library. Most of it should also be contained in their own (sometimes very minimal) react components. I've started doing some of it at https://github.com/zotero/web-components

You can remove the Zotero.Pages on your working branch of web-library now.

**Comment by tnajdek** [comment]
Cool, thanks!
