### ISSUE TITLE
Tweak level-root active state

### ISSUE THREAD

**Issue by johanneskrtek** [zotero/web-library#67]
Our combination of `.level-root.active` and `.has-open.level-last` works so far, but there is an edge case in which it does not work on tablets: when the first collection level already is the last level. in this case the `.level-last` class is set correctly, but the `.active` class is removed from the level root nonetheless.

I think we have to treat this case specially and do not remove the `.active` when the selected level is `.level-1.level-last`.

**Comment by tnajdek** [comment]
That should do it :)

**Comment by johanneskrtek** [comment]
I fear this tweak broke the 3rd collection tree level on touch devices:

![bildschirmfoto 2017-03-07 um 18 45 36](https://cloud.githubusercontent.com/assets/419747/23669973/6cc20c04-0366-11e7-811a-b3eec8539443.png)

**Comment by tnajdek** [comment]
Nice catch, I should probably think about some sort of test coverage to avoid regressions like that.
