### ISSUE TITLE
Folder & folders touch icons

### ISSUE THREAD

**Issue by johanneskrtek** [zotero/web-library#71]
I added two icons (`folder-28.svg` and `folders-28.svg`) that should replace the desktop folder icon in the touch version of the web library.

Switching the visibility between desktop and touch icons can be achieved with generic classes like `.icon-touch` / `icon-mouse`(#66).

However, the `folder-28` icon should show up when the collection has no subcollections and the `folders-28` should show up when the collection has one or more subcollections.

So what we would need would be some kind of logic that inserts either the one or the other icon (and this can change obviously, as you can create subcollections). Currently this logic should insert one of the two icons as the first element in the `.item-container`.

**Comment by tnajdek** [comment]
If I understand correctly, this should hopefully do it. If it's not, please feel free to re-open this issue @johanneskrtek
