### ISSUE TITLE
Code organization

### ISSUE THREAD

**Issue by johanneskrtek** [zotero/web-library#75]
@tnajdek you already started to organize the js code in folders, I’ll do the same with the stylesheets in `scss`.

Wherever possible I will switch to granular class names (e.g. `.item.details` instead of `item-details` and I will also minimize the file names (e.g. `item/details.scss` instead of `item-details.scss`) – you might want follow that logic of naming files in the `js` folder too.

**Comment by tnajdek** [comment]
yeah that and some serious refactoring + code de-duplication is much needed. Will do.

**Comment by tnajdek** [comment]
I'm going to call it done. It's better than before though I'm not entirely happy with one-file folders (for container.jsx files) but let's keep it this way for now.

**Comment by johanneskrtek** [comment]
@tnajdek Cool. I’m really not the one who should give an advice here – but couldn’t we have something like

```
collection-tree
  container.jsx
  view.jsx
```

instead of having `collection-tree.jsx` outside in order to avoid one-file folders?

**Comment by tnajdek** [comment]
I'm not 100% sold on that. Not every component needs a container and this would introduce new dirs as well (e.g. `item/details.jsx` would become `item/details/view.jsx`).

Let's leave it as it is for now, see how it pans out and adapt/revisit later on.

**Comment by johanneskrtek** [comment]
Alright – as I said, I’m actually not the one who should give advices here …  : )
