### ISSUE TITLE
Selecting collection within an open tree branch closes all its childs

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#78]
Best illustrated by a screencast, selecting collection-1-1 should not have closed it:

![screencast](https://cloud.githubusercontent.com/assets/214628/23705082/e0e82908-03ff-11e7-84b9-004532baffc7.gif)

However if allowed to remain .open, it breaks rendering on mobile. A solution here potentially requires screen-size aware javascript.

**Comment by johanneskrtek** [comment]
Didn’t this work already correctly at some point? Why does the `.open` class have to be removed when an item gets selected?

**Comment by tnajdek** [comment]
This has been fixed at some point.
