### ISSUE TITLE
Navigation regressions

### ISSUE THREAD

**Issue by johanneskrtek** [zotero/web-library#80]
@tnajdek I didn’t find a better place for that, so I opened a new issue with remarks on navigation regressions (maybe you can address these while experimenting with Jest):

* [x] On phones, the item list does not show up currently.
* [ ] On phones: the `.active` class should be removed from `.level-root` when a collection gets selected (as opposed to tablets)

**Comment by tnajdek** [comment]
@johanneskrtek currently JS is not aware of breakpoints and I was hoping to keep it this way. Could this be resolved by setting another class?

**Comment by johanneskrtek** [comment]
@tnajdek ha, good point – we already have that class: when a collection does not have subcollections it means that the item list will be shown next. And in this case we set the `view-item-list-active` on the `data-reactroot`. This way I can differentiate between phones and tablets.
