### ISSUE TITLE
Toolbar and button component

### ISSUE THREAD

**Issue by johanneskrtek** [zotero/web-library#81]
@tnajdek I added the toolbar and some buttons above the item list.

I guess we want a `<Toolbar>` component. It should be possible to pass arbitrary classes to `<Toolbar>`.

We could also have an `<IconButton>` component – in any case we will need the possibility to toggle an `.active` class on the button (e.g. while a dropdown is open).

**Comment by tnajdek** [comment]
@johanneskrtek that's mostly done.

Not closing yet as the `<IconButton />` might still change. It currently doesn't support `.active` switching for start. Also I'm considering swapping it for a more open `<Button />` component.

**Comment by tnajdek** [comment]
Replaced `<IconButton />` with `<Button>` which is less specific and can be used with text or an `<Icon />`. If `<Icon />`is among it's children and will automatically use `btn-icon` class.

It now supports `active` prop, which adds additional `.active` class.

**Comment by johanneskrtek** [comment]
@tnajdek looks good to me!

`<ToolGroup>` and `.toolbar-left` are quite similar though, I just use them to layout out the buttons in the toolbar in a generic way – I guess there is no need to have a `<ToolGroup>` component.

Question: is it considered to be good practice to add the `className` attribute to a `<Component>` (as opposed to passing classes as props)?
