### ISSUE TITLE
Styling for the creators component

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#83]
I've implemented a new component for managing creators and it desperately needs some attention in regards to styling/responsiveness/usability:

<img width="770" alt="screen shot 2017-04-06 at 14 16 29" src="https://cloud.githubusercontent.com/assets/214628/24756034/46ed3118-1ad4-11e7-9783-d9e88eb9e6c6.png">
<img width="671" alt="screen shot 2017-04-06 at 14 15 47" src="https://cloud.githubusercontent.com/assets/214628/24756033/46ea515a-1ad4-11e7-871f-24de788e8c75.png">

For comparison, here's how it looks in the desktop client:

<img width="338" alt="screen shot 2017-04-06 at 14 17 19" src="https://cloud.githubusercontent.com/assets/214628/24756053/569d5462-1ad4-11e7-9c4b-143452f4f7d1.png">
<img width="337" alt="screen shot 2017-04-06 at 14 17 14" src="https://cloud.githubusercontent.com/assets/214628/24756052/569c1232-1ad4-11e7-9b4b-0777f4bc8d81.png">

You're ok to take a stab at it @johanneskrtek?

**Comment by tnajdek** [comment]
Closing in favor of #120

**Comment by flachware** [comment]
Sorry, I totally forgot that this one was still open!
