### ISSUE TITLE
Web Library does not work on iOS < 10

### ISSUE THREAD

**Issue by flachware** [zotero/web-library#85]
@tnajdek I would like to test the web library on my iPad in order to tweak the font size for tablets.

The web library works fine in Safari 10.1, also in Mobile Safari on the iPhone (iOS 10.2.1) but not in Mobile Safari on the iPad (iOS 9.2.1). Please, could you have a look at it?

If I can be of any help, just let me know.

![img_0134](https://cloud.githubusercontent.com/assets/419747/24915311/1f74fa38-1ed7-11e7-9956-69c28bdc517b.PNG)
![screen shot 2017-04-11 at 16 46 28](https://cloud.githubusercontent.com/assets/419747/24915330/294fa792-1ed7-11e7-8b7f-e92c818b8b51.png)

**Comment by tnajdek** [comment]
This fails because we use `localeCompare` for sorting. This is supported by [all modern browsers](https://caniuse.com/#search=Intl). We can fallback and/or polyfill if we care, perhaps after 1.0?

**Comment by flachware** [comment]
Yes, let’s make this a post 1.0 issue.

**Comment by tnajdek** [comment]
While I'm open to discuss this, as it stands I don't see us supporting Safari < 10 - see #31 for explanation.
