### ISSUE TITLE
css-truncate cannot handle long urls with query arguments

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#94]
Currently we use `css-truncate` mixin in many places in the interface to truncate long values in a nice way. However, since we're not limiting the height of the truncated value, multi-line input can break the rendering. While input values being truncated should not contain an actual line-break character, browsers choose to break lines after some special chars, such as a question mark.

Steps to reproduce:
--------------------

In a desktop mode edit an item, enter the following url as a value:

http://this.is.a.long.url/Ut-dolore-excepteur-non-anim-est-aute-qui-consectetur-ex-et-ex-est-in-voluptate-culpa-laboris-velit-consequat-lorem-ipsum-dolot.with-some-query-args?arg1=2&arg3=4

Expected behavior:
---------
The value is truncated with ellipsis:
<img width="1440" alt="screen shot 2018-02-03 at 13 50 02" src="https://user-images.githubusercontent.com/214628/35767247-2e9be04c-08e9-11e8-8e5b-91be265838ff.png">

Actual behavior:
---------------
The entire right panel is shifted, so that fields are partially obscured (see screenshot). With longer strings (or smaller screens), right panel disappears completely.

<img width="1440" alt="screen shot 2018-02-03 at 13 32 55" src="https://user-images.githubusercontent.com/214628/35767230-822e7d4c-08e8-11e8-9f5c-a68b7bd12542.png">

**Comment by tnajdek** [comment]
@flachware I'm wondering if this can be fixed with a clever css solution or whether we need to use some js

**Comment by flachware** [comment]
@tnajdek I think I can fix this with CSS. CSS truncation of single lines (I can prevent line breaks) can be hard in flex layouts, but it’s possible.

**Comment by flachware** [comment]
This was actually a bit more complex. Long values have already been truncated, but the layout of one of the flexbox parents was broken due to the truncation. Should be stable now.
