### ISSUE TITLE
Attachment download url contains api access key

### ISSUE THREAD

**Issue by tnajdek** [zotero/web-library#95]
In the development version of the web-library, attachment download url contains the api access key. This is not ok, because, for example, user could potentially copy the url and inadvertently give someone else full access to his/her account.

I can think of a few possible solutions, but most likely we should employ a server-side proxy, same as used in current version of the web-library.

**Comment by dstillman** [comment]
Maybe I'm misunderstanding the problem, but why does it include the access key? All API access should use `Zotero-API-Key`.
